### ISSUE TITLE
Wondering how to implement "sub-rows"

### ISSUE THREAD

**Issue by zachdaniel** [glideapps/glide-data-grid#100]
I'm wondering if there is a way to implement sub-rows/child-rows, e.g
```
| id  |  First       | Last      |
| 1    |  Isaac     | Asimov |
  Friends:
  | id |  First     | Last        |
  | 2  |  Robert | Heinlein |
```

Now, I can see a couple ways that that design pattern may be problematic, so I'd also be interested to hear of other methodologies around showing related/grouped data if you don't think the above is a good idea. Thanks for the hard work on this project!

**Comment by jassmith** [comment]
the method we are planning to use in Glide is to set the bgCell color to a lower value on the "subtable" rows. This makes them visually children of the parent row. Your data source simply needs to flatten this out. 3.1.0 actually will include a themeOverride at the cell level specifically for this effect. Pairing it with uneven row heights may let you push it further but I don't actually see the need for that much distinction. If you want to submit a patch to the repo that contains an example of doing that it would be awesome.

**Comment by jassmith** [comment]
One of the other bits a really want to set up when I find time is a glide-data-grid-extras package which can contain a bunch of hooks for doing interesting things with events and data sources that I dont want to bloat the main package with. Things like automatically rearrangable columns, sortable data sources, filterable data sources, and things like sub rows would be great candidates. Basically hooks that you feed your args too and spread the resulting data onto the DataEditor props.

**Comment by zachdaniel** [comment]
awesome, thanks for the great explanation!
