### ISSUE TITLE
Glide data grid renderer for VSCode notebooks

### ISSUE THREAD

**Issue by RandomFractals** [glideapps/glide-data-grid#105]
Hi @schani, @jassmith, and contributors!

I am reaching out to see if you'd like to collaborate on adding your grid as one of the data output rendering options for VSCode notebooks.

You can read about Jupyter notebooks in vscode here: https://code.visualstudio.com/api/extension-guides/notebook

And custom notebooks and renderers in this post: https://code.visualstudio.com/blogs/2021/11/08/custom-notebooks

I would like to create a custom data grid renderer using your grid similar to the basic version I created this summer: 

https://github.com/RandomFractals/vscode-data-table

I like that glide data grid provides search and many nice data formatting options with storybook examples.

Can I have your permission to use `glide data grid` in that custom renderer repo name and branding when I publish it in VSCode marketplace?

You can preview my work in that space here: https://marketplace.visualstudio.com/publishers/RandomFractalsInc

Public repo created for your data grid renderer: https://github.com/RandomFractals/glide-data-grid-renderer

I do prefer to maintain and publish them on my end, if you are open to that. Otherwise, I'll probably rename it to `data-glider` with proper attributions in the intro section of that extension readme.md 🙂 

*Taras*

**Comment by RandomFractals** [comment]
nvm. I renamed it to vscode data glider. We can still collabo on it and I'll file issues in this repo if I run into problems integrating it in vscode notebooks as a custom renderer. 

New repo here: https://github.com/RandomFractals/vscode-data-glider

**Comment by jassmith** [comment]
I'd love to collab on this. Sorry I didn't see this until now, you closed it too fast :P

**Comment by RandomFractals** [comment]
@jassmith we can still do that. I just renamed it slightly. Base data renderer code setup is there already. I just need to wire your data grid with ReactDOM to wrap that proto. See here: https://github.com/RandomFractals/vscode-data-glider/blob/main/src/renderer/render.ts#L27

**Comment by RandomFractals** [comment]
btw, looks like your data grid has more peer dependencies than what's listed in your docs ...

![image](https://user-images.githubusercontent.com/656833/144494102-7c14369a-130f-4492-80b4-29db41636267.png)

**Comment by jassmith** [comment]
I'll try to get a PR ready for you this weekend! :)

**Comment by RandomFractals** [comment]
sounds good. You can see how I wired Observable Inputs table in the data table renderer for example:

https://github.com/RandomFractals/vscode-data-table/blob/main/src/renderer/dataTableRenderer.ts#L31

I added all the peer dependencies for your grid already. 

Since I don't have any docs in the repo yet, you can use this info to build it: https://github.com/RandomFractals/vscode-data-table#dev-build
