### ISSUE TITLE
Hit testing within a cell

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#109]
I see that there are events for detecting when a cell is clicked (`onCellClicked`) and hovered (`onItemHovered`), but I was wondering if it would be possible to pass along or otherwise determine *where* in the cell the click occurred?

In my case, I'm looking to build a table with a hierarchy that is collapsible. I'd like to toggle collapsing/hiding the children when clicking the triangle on the left side, but still be able to edit the title by clicking elsewhere in the cell. I would try to achieve this by using two different cells side by side, but that wouldn't work because of the indentation. Please let me know if this information is something that could be added to `onCellClicked`, or how you would recommend building something like this!

<img width="893" alt="table" src="https://user-images.githubusercontent.com/94077014/144335236-1fc5826c-1b54-47cc-bb74-97a06983f229.png">

**Comment by jassmith** [comment]
Funny you should mention that, I was just adding support for that internally. If you are using the drawCell callback (not `drawCustomCell` on the latest version of the data grid it will expose out the localEventX and localEventY to your renderer for the current mouse location on draw. You could do some hacky stuff with that to pass it up to onCellClicked but instead I will just move it one step further and make onCellClicked pass that info on directly for the upcoming 3.1.3 release.

**Comment by jassmith** [comment]
I've pushed 3.1.3-alpha1 a bit early to give you access to the API you desire. This should actually be a fairly stable version since so little has changed since 3.1.2. `onCellClicked` now has an additional argument which provides all the detail you need.
