### ISSUE TITLE
Adding support for custom header cells

### ISSUE THREAD

**Issue by norav1** [glideapps/glide-data-grid#110]
Would it be possible to add support for custom rendering of the header cells as well? 

Ideally I'd like to be able to have the capability to do something like this within the header cells:
https://codesandbox.io/s/9m9qs

I imagine the easiest way to implement this would be an additional prop such as the following:
`drawHeaderCell?: (args) => boolean;`

Otherwise, this library is perfect for my needs. Fantastic job.

**Comment by jassmith** [comment]
I'll add a draw callback, will need to sit down and work out the details

**Comment by jassmith** [comment]
Support has shipped in 3.1.3-alpha6. Please give it a try. There is an example committed to storybook for how to use it. You can return true to prevent the default drawing from happening, or you can just draw a background and return false to let the default foreground draw.

**Comment by jassmith** [comment]
There will probably be some additional args added to handle dropdown menus but I wanted to give you a chance to test.

**Comment by norav1** [comment]
Impressive how quickly you are able to build in features!
What is the name of the example in Storybook? I am flipping through each of the examples and I am not able to find it. 
Thank you for your hard work.

**Comment by jassmith** [comment]
You would need to look in the 3.1.3 branch. The production storybook wont update until I merge 3.1.3 to the main branch.
