### ISSUE TITLE
Getting absolute coordinates for hover menus

### ISSUE THREAD

**Issue by stjepangolemac** [glideapps/glide-data-grid#111]
I'm trying to implement onHover behavior where some additional info pops out if the cursor hovers over a cell for a given time. The coordinates that I get through onItemHovered are unusable as they seem to somehow relate to the document scroll position.

Do you have any suggestions?

**Comment by jassmith** [comment]
Looking into it.

**Comment by jassmith** [comment]
![image](https://user-images.githubusercontent.com/30443/145335072-e2e483cf-8314-42fc-ba12-38f43aa1ffa6.png)

I've implemented a tooltip demo in the storybook. It will be available in the public storybook when 3.1.3 goes stable. Until then you can see the code here: https://github.com/glideapps/glide-data-grid/pull/108/commits/f245ae3fee8749722e0b7c2ed8814463352c6e87

From the screenshot you can see tooltips go with the cell. Regardless of both document scroll position and the scroll position of the data grid itself.

**Comment by jassmith** [comment]
If you are still having issues please re-open the issue and I will be happy to take a look.

**Comment by stjepangolemac** [comment]
I've actually wrongly assumed that the coordinates should be relative to the canvas, not to the document. After modifying the system it started behaving correctly. Thanks for the help!
