### ISSUE TITLE
Theme override at cell level

### ISSUE THREAD

**Issue by rfdrake27** [glideapps/glide-data-grid#112]
Hi there!

I was wondering how theme overrides worked at the cell level? Using the drawCell function, I see that there is a themeOverride prop within the cell object, but it is readonly, and the function only returns a boolean. 

I can successfully use the themeOverride on the column, but I was hoping to only modify the theme on one specific cell. Is that possible?

**Comment by jassmith** [comment]
when you create the cell in your `getCellContent` callback add the theme override there.
