### ISSUE TITLE
Images flickering or not displaying

### ISSUE THREAD

**Issue by rfdrake27** [glideapps/glide-data-grid#113]
Hello, I think I've found a couple bugs. 

On the 3.1.3-alpha6 version I've had issues with images disappearing, and on prior versions I'm seeing issues with flickering. When I try to load a codesandbox with version 3.1.3, I'm unfortunately getting the following error as well: "Cannot read properties of undefined (reading 'Boolean')". On my local install it works though with the exact same configuration.

Version with images disappearing, and "Cannot read properties of undefined (reading 'Boolean')" error:
[https://codesandbox.io/s/create-react-app-template-forked-om6lm?file=/TestCanvasGrid.tsx](https://codesandbox.io/s/create-react-app-template-forked-om6lm?file=/TestCanvasGrid.tsx)

Here is a gif of the 3.1.3-alpha6 local install with the images disappearing. They return when I click on the cells. The file and package configuration used is identical to the codesandbox above. 
[Gif of images disappearing](https://giphy.com/gifs/wVeG2FXXrOOGP0vYpj)

Version 3.0.4 with images flickering:
[https://codesandbox.io/s/solitary-sunset-8t7fj?file=/src/TestCanvasGrid.tsx](https://codesandbox.io/s/solitary-sunset-8t7fj?file=/src/TestCanvasGrid.tsx)

**Comment by jassmith** [comment]
Does this only happen with freeze columns? Seems like an easy fix.

**Comment by rfdrake27** [comment]
Yes it doesn't disappear if there are no frozen columns. 

Without frozen columns I'm still seeing a tad bit of flickering on vertical scrolling, but at least the images don't disappear.

The frozen column is important for my application though. Out of curiosity what do you think is causing it?

**Comment by jassmith** [comment]
The ImageWindowLoader thinks the frozen column is out of the visible range. Easy fix.

**Comment by jassmith** [comment]
Fixed in 3.1.3 branch. Should be released to beta sometime this week, maybe stable.
