### ISSUE TITLE
Blank cell on edit

### ISSUE THREAD

**Issue by ndmt** [glideapps/glide-data-grid#114]
Hello,

There is a bug when you edit something and you clic in an other cell.
Example -> https://glideapps.github.io/glide-data-grid/?path=/story/dataeditor--add-data
You double clic Title for row 6, you change data, you don't press enter and you click for example on Title row 12, now you have you Title Row 6 updated but between row 6 and 12 you have blank cells. If you click again on an other cell it re-appears.
Now if you retry to update Title row 6, and you click on an other column then all your cells title row > 6 are blank.

I think this line is causing problem:
https://github.com/glideapps/glide-data-grid/blob/a096e6d3aad23de5c1f5f2a6c59d952744c781fa/core/src/data-grid/data-grid-render.tsx#L104
if you remove the `if` the issue disappears.

**Comment by jassmith** [comment]
Great report. Will fix ASAP.

**Comment by jassmith** [comment]
This is fixed in a 3.1.3 branch.
