### ISSUE TITLE
LocalEventX and localEventY for Hover update behavior

### ISSUE THREAD

**Issue by rfdrake27** [glideapps/glide-data-grid#115]
Thank you for adding the PositionableMouseEventArgs to the hover and click events.

I see that when I hover over a cell it updates on mouse enter, however it doesn't update when hovering different areas of the cell. I was hoping to use the hover coordinates to position a tooltip over an icon within the cell. Is there a configuration option or prop I'm missing? Or if not, is it something you were looking to add support for?

Thank you for such a wonderful library.

**Comment by jassmith** [comment]
Let's make it happen. I might have to add a toggle for it because it could come with a rather large performance cost but I kinda doubt it. It will almost certainly be a different event because I dont want to change the semantics of the item hovered event.

**Comment by jassmith** [comment]
`onMouseMove` event is now present in 3.1.3
