### ISSUE TITLE
"Lossy Copy Data" Story in Storybook has an error - not loading 

### ISSUE THREAD

**Issue by wingtao** [glideapps/glide-data-grid#122]
there is an error happened in https://glideapps.github.io/glide-data-grid/?path=/story/dataeditor--lossy-copy-data.
like this: 
![image](https://user-images.githubusercontent.com/17567845/147453296-5b353a40-c2e7-4c9f-b856-778ee4a7307c.png)

**Comment by bryhasagithub** [comment]
AH I was able to see the error as well but the good news is that it appears that lossy copy data is the only one that is affected. I'll rename the issue

**Comment by ivoelbert** [comment]
Thanks for reporting! This was an `export`ed function that storybook thought was a story. 

Fixed in https://github.com/glideapps/glide-data-grid/pull/145
