### ISSUE TITLE
Wrapperless cell editor

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#123]
I'm building a custom cell editor using the `provideEditor` attribute, but it seems that this enforces that the editor gets put inside a `DataGridOverlayEditorStyle` and  `clip-region` div which adds its own border, border radius and styles `input` and `textarea` elements.

https://github.com/glideapps/glide-data-grid/blob/6b0a04f9d6550378890580b4db1e1168e4268c54/packages/core/src/data-grid-overlay-editor/data-grid-overlay-editor.tsx#L108-L117

Would it be possible to support a version of provideEditor that handles its own borders to allow for more flexibility?

I see that I can add a `disablePadding` property to remove the padding, but it would be great if there was another attribute that could remove some of this other styling too.

https://github.com/glideapps/glide-data-grid/blob/6b0a04f9d6550378890580b4db1e1168e4268c54/packages/core/src/data-grid-overlay-editor/data-grid-overlay-editor.tsx#L71-L82

**Comment by bjgrosse** [comment]
Another vote for this!

**Comment by jassmith** [comment]
Yes this can be added, we cant get rid of the wrapper entirely but we can unstyle it.

**Comment by pzcfg** [comment]
That works for me!

One other issue I've been running into is needing more editor space below the cell. Currently there's a `max-height: calc(100vh - ${p => p.targetRect.y + 10}px)` that's preventing that from growing. I can use the `experimental.paddingBottom` to help alleviate this if the user manually scrolls down, but if they haven't, it only scrolls to the bottom of the cell itself and then keeps it clipped. Do you have a suggestion for working around that?

**Comment by jassmith** [comment]
What do you want that to do? Currently it stops the cell editor going off screen

**Comment by pzcfg** [comment]
I think in the ideal world, if the child wants to grow, it would scroll the table so that the top of the editor still lines up with the cell but the bottom of the editor isn't cut off, but that seems overly complicated. Maybe the editor could specify an anticipated max-height and the table will try to scroll that extra amount when you go to edit?

For now I think I can work around it using `paddingBottom` and `scrollTo` with `paddingY` getting added here https://github.com/glideapps/glide-data-grid/pull/139#issuecomment-1028396539

I'll give some more thought on what would be best here

**Comment by jassmith** [comment]
Fixed in 3.3.0
