### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module

### ISSUE THREAD

**Issue by SagingTime** [glideapps/glide-data-grid#124]
Hi, I have an issue with running the example getting started code. I am running Next.js if that is relevant.

## Error:
Terminal output:
`
Error [ERR_MODULE_NOT_FOUND]: Cannot find module ...@glideapps/glide-data-grid/dist/js/data-editor/data-editor' imported from ...@glideapps/glide-data-grid/dist/js/index.js
`

Console output:
```
index.js?46cb:323 Uncaught     at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
```

## Packages:
Next.js version: v12.0.7
React version: v17.0.2
Mantine version: v3.4.3
NPM version: v8.3.0
Node version: v14.17.0

## Usage:
`import DataEditor, { DataEditorContainer, GridColumn, GridCell, GridCellKind } from '@glideapps/glide-data-grid'; 
`

* The rest is copied from the example put into the Next.js boilerplate template. However, getData now has a required field displayData, which I made the same as data.

Thank you

**Comment by SagingTime** [comment]
It appears that as long I do not manually refresh the page, I can see the table. Otherwise, I have to unrender the table or restart the server to fix the error.

**Comment by SagingTime** [comment]
It seems to work if my files are in javascript but not in typescript, and I must use Next's dynamic import to import my glide components.

Strange... can anyone give any pointers for this interaction?

**Comment by SagingTime** [comment]
I have fixed this problem by dynamically importing each component that requires glide. It's kind of hacky since it seems that SSR is supposedly supported, but my issue is solved. I am closing this thread.

**Comment by thedanielforum** [comment]
I am having the same issue as well, however dynamically importing the glide components are not working for me.

**Comment by twobit** [comment]
Having the same issue. Dynamic imports worked, thanks @SagingTime!

Next: 12.0.7
React: 17.0.2
Node: 17.3.0
NPM: 8.3.0
