### ISSUE TITLE
Mouse interaction on modal spawned through custom editor

### ISSUE THREAD

**Issue by SagingTime** [glideapps/glide-data-grid#126]
I have a custom cell editor that spawns a modal through a react portal. However, this model lies outside the main div, and thus any mouse interactions are not recognized. I see a "click-outside-ignore" for ClickOutsideContainer, and  DataGridOverlayEditorStyle has a targetRect, but I don't know where to start. Can anyone give me some pointers?

Thanks

**Comment by JulianBertsch** [comment]
I have an similar case for a dropdown menu for a calendar to select months and years

**Comment by bjgrosse** [comment]
Me too!

**Comment by jassmith** [comment]
Can you please provide a repro or a video?

**Comment by bjgrosse** [comment]
With a react-select dropdown in an editor, clicking on the dropdown options closes the editor before the click can take effect: 

![wLhOimZnwk](https://user-images.githubusercontent.com/14151299/156249927-fae3d2ac-e3ad-4078-8979-f554a8f08faf.gif)

**Comment by jassmith** [comment]
Oooooh I get it, I will add an example of how to do this! Basically you just need to make sure the container of the dropdown popout has "click-outside-ignore" as its class. There maybe should be a better way.

**Comment by jassmith** [comment]
I've almost got this working but jeebus crust does react-select make you work for it. The actual code isn't that bad once you get the basics in place but man oh man do they not make it clear wtf its doing.

**Comment by jassmith** [comment]
I've finished my basic implementation. You can see it here. Feel free to swipe the code, it does not require any changes to the core package to use. Otherwise this should land in 3.5.0 glide-data-grid-cells package.

https://github.com/glideapps/glide-data-grid/pull/201
