### ISSUE TITLE
Positions Incorrect OnMouseDown When Transform Scale

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#130]
If the `glide-data-grid` in wrapped in a parent that has `scale(X)` where `X != 1`, the cells / positions from clicking on the grid are incorrectly offset-ed.

As a sketch, I think this problem can be solved within
https://github.com/glideapps/glide-data-grid/blob/6c7d1964269b531daf8bf8c1b7205a8055d94947/packages/core/src/data-grid/data-grid.tsx#L701-L715

and adding a scale factor

```js
// Alternatively, use `eventTarget` instead of `canvas`.
const scale = canvas.getBoundingClientRect().width / canvas.offsetWidth;
clientX = clientX / scale
clientY = clientY / scale
```

**Comment by jassmith** [comment]
Yeah this is going to be a hard limtation for the time being. We would need to manually unapply those tranforms. I am not saying never, but I am saying not now. Patches welcome?

**Comment by BrianHung** [comment]
> I would love a patch that instead makes it possible to mutate GDE to support this but not support it in the core.

What would a PR supporting this look like? Does a `scale` prop to data-grid suffice?

**Comment by jassmith** [comment]
The correct way to do this would be to get the canvasRef, then walk up its parent tree recursively applying the transform to the reported coordinates.

**Comment by BrianHung** [comment]
For posterity, I figured out what this comment meant!

```js
let elem = canvas // html canvas element here
while (elem != null) {
    const style = window.getComputedStyle(elem)
    const matrix = new window.DOMMatrixReadOnly(style.transform);
    if (!matrix.isIdentity) console.log(elem, matrix);
    elem = elem.parentElement
}
```
