### ISSUE TITLE
Allow custom provided editors to invoke onFinishedEditing with a value

### ISSUE THREAD

**Issue by josephschorr** [glideapps/glide-data-grid#138]
Custom provided editors are currently given an `onFinishedEditing` callback, but one that relies on the `tempValue` stored as `useState` on the overlay editor:

https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-grid-overlay-editor/data-grid-overlay-editor.tsx#L40

Unfortunately, for editors that can make "instantaneous" changes (e.g. selecting an item via an autocomplete), this callback is insufficient, as calling the `onChange` callback to update `tempValue` kicks off an async state update; attempting to call `onFinishedEditing` immediately afterward therefore uses the *old* value of `tempValue`.

I propose a change whereby the custom editor is given a variant of `onFinishedEditing`, which takes an optional new value. If specified, then that value would override the `tempValue` passed back to the parent `onFinishedEditing` callback; if not specified (i.e. `undefined`), `tempValue` would continue to be used.

If approved, I'd be happy to contribute the change

**Comment by pzcfg** [comment]
I've been running into this as well!
