### ISSUE TITLE
customize background color

### ISSUE THREAD

**Issue by bjgrosse** [glideapps/glide-data-grid#140]
I'd really like to be able to customize the background color of non data cells (ie., the cells below and to the right of my data). It seems they are always painted white and there's no way to control that or even paint over it.

**Comment by pzcfg** [comment]
Using a `ThemeProvider` and setting `bgCell: '<your color>'` colors the cells below and to the right for me.
```
<ThemeProvider theme={{ bgCell: '#FF0000' }}>
  <DataEditor ... />
</ThemeProvider>
```
<img width="758" alt="Screen Shot 2022-01-27 at 10 59 47 AM" src="https://user-images.githubusercontent.com/94077014/151426167-2af8f617-ed59-43ac-8a7b-fb193784abbb.png">

**Comment by bryhasagithub** [comment]
@bjgrosse does @pzcfg's solution resolve your issue? if not, I'll leave this issue open.

**Comment by jassmith** [comment]
You can do this by setting the root themeProviders bgCell: to whatever you want the non-data cell background to be, and then for every cell you produce out of getCellContent you can provide a different bgCell value in the `overrideTheme`.

**Comment by jassmith** [comment]
You can also do this at the column level instead for a slightly different effect (rows that are blank because there is not enough data will still color as the override color)

**Comment by bjgrosse** [comment]
@jassmith there's another reason this approach doesn't work: the bgCell of the global theme is what is used for the background of the `DataGridOverlayEditorStyle` and thus the bgCell of the themeOverride on the cell itself is not honored:

![image](https://user-images.githubusercontent.com/14151299/164429261-e807be80-8243-4d5c-ac8c-15d4a47636e5.png)
