### ISSUE TITLE
onCellClicked fires if mouse is released over grid when resizing columns

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#151]
If you start dragging a column to resize it, move the cursor down over the grid, and release, the `onCellClicked` callback is triggered.

https://user-images.githubusercontent.com/94077014/152256095-4231d736-113e-4868-a3dd-4b89ae6c270c.mp4

**Comment by jassmith** [comment]
To fix this we need to track mouseDOwn and mouseUp to ensure that they mouse went down and came up on the same cell. This would indicate a click cycle.

**Comment by ivoelbert** [comment]
This (and a related bug for onHeaderClick) was fixed in https://github.com/glideapps/glide-data-grid/pull/154. It'll be part of the v3.3.0 release
