### ISSUE TITLE
Inconsistent styling for trailingRowOptions.hint

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#157]
I have some cells with different font weight/size/etc. depending on certain conditions. I noticed that when using `themeOverride` to set the cell font styling differently it causes the trailing row hint styling to become inconsistent/flicker.

https://user-images.githubusercontent.com/94077014/152444775-bf85f770-b1cd-4521-a2b9-eb5cf68a763e.mp4

In the environment we're using it the problem seems to be even more pronounced (unfortunately I can't share more details).

https://user-images.githubusercontent.com/94077014/152444979-ea8b35b0-198a-43d6-837b-b74ac00e2452.mp4

Perhaps there are some additional `ctx.save()`/`ctx.restore()` calls that are needed? Or the styling is being pulled from one of the cell `themeOverride`s instead of the column or global theme?

**Comment by jassmith** [comment]
save/restore missing

**Comment by jassmith** [comment]
Fixed in 3.3.0
