### ISSUE TITLE
Use font styling from theme/themeOverride for input fields

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#158]
Right now it seems that the input font size is hardcoded to 13px

https://github.com/glideapps/glide-data-grid/blob/6b0a04f9d6550378890580b4db1e1168e4268c54/packages/core/src/data-grid-overlay-editor/private/number-overlay-editor-style.tsx#L3-L14

https://github.com/glideapps/glide-data-grid/blob/6b0a04f9d6550378890580b4db1e1168e4268c54/packages/core/src/growing-entry/growing-entry-style.tsx#L1-L9

<img width="155" alt="Screen Shot 2022-02-03 at 7 59 34 PM" src="https://user-images.githubusercontent.com/94077014/152469739-20ec67cc-70af-4d9a-a317-696f8ab1b59b.png">

It would be great if this could match the theme/themeOverride of the cells so it's as WYSIWYG as possible, at least optionally, or customized separately

**Comment by jassmith** [comment]
great idea let me see what can be done

**Comment by jassmith** [comment]
Merged
