### ISSUE TITLE
`SpriteMap` not exported from @glideapps/glide-data-grid

### ISSUE THREAD

**Issue by ivoelbert** [glideapps/glide-data-grid#161]
It's possible to import it like
```ts
import type { SpriteMap } from "@glideapps/glide-data-grid/dist/ts/data-grid/data-grid-sprites";
```

but it's public API (because of `headerIcons`) so we should export it from `@glideapps/glide-data-grid`

**Comment by pzcfg** [comment]
I just ran into this on Friday!

**Comment by ivoelbert** [comment]
I'll fix it later today 😄
