### ISSUE TITLE
Update editor position on scroll

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#162]
This should probably be an option since I could see people wanting the current behavior as well, but it would be nice to have the editor move when the grid is scrolled so they don't become detached like this

https://user-images.githubusercontent.com/94077014/152847486-f96c3df8-faa4-4ec2-bc55-6f6bb41d6d6e.mp4

**Comment by ivoelbert** [comment]
We chose this behavior cause it aligns with what Google Sheets does. I just checked Excel, and it does what you're suggesting, so I guess we're at a split. In our defense, the excel behavior looks terrible 😄 

We'll think about making that an option, there are a few technical considerations.

**Comment by ivoelbert** [comment]
Leaving this here as reference:

I kind of like what Google Sheets does when you scroll. They add a little overlay that refers back to the cell you're editing. Perhaps we can provide a way to add a custom overlay.
 
https://user-images.githubusercontent.com/18490534/152871750-d4e8bf4d-368d-4fd3-aaf3-a6cf841eb55a.mov

**Comment by jassmith** [comment]
We're not going to change this for the moment.
