### ISSUE TITLE
Homepage crash

### ISSUE THREAD

**Issue by twobit** [glideapps/glide-data-grid#169]
On https://grid.glideapps.com scroll down then scroll up quickly:

https://user-images.githubusercontent.com/2778/153539806-7d22767f-72c2-4b28-9835-e1a863d46003.mov

Console error: `undefined is not an object (evaluating 'a[n][i]')`

Safari: 15.2
OS: macOS Monterey 12.1

**Comment by ivoelbert** [comment]
Thanks for reporting!

Yeah... That page is wildly outdated. We put all our love into storybook.

`glide-data-grid` grew _a lot_ recently, I think we should make a new site for it that better displays its performance and design capabilities.

**Comment by ivoelbert** [comment]
Thanks for reporting!

Yeah... That page is wildly outdated. We put all our love into storybook.

`glide-data-grid` grew _a lot_ recently, I think we should make a new site for it that better displays its performance and design capabilities.

I'm closing this for now.
