### ISSUE TITLE
Spacebar doesn't scroll table

### ISSUE THREAD

**Issue by twobit** [glideapps/glide-data-grid#170]
In MacOS the spacebar can be used to scroll a page at a time.

**Comment by ivoelbert** [comment]
Huh, I've been using MacOS for years and never learned that. Thanks for noting that! I'll fix this.

**Comment by pzcfg** [comment]
shift-space also scrolls up

**Comment by pzcfg** [comment]
This could get a little ambiguous though. right now if you have an editable cell selected and start typing, it edits the field. If a field is selected should it insert a space or scroll?

**Comment by jassmith** [comment]
When faced with this dilemma I always ask myself "what does google sheets
and excel do?"

**Comment by ivoelbert** [comment]
Ha, I was just checking that

**Comment by twobit** [comment]
Same, just checked. I guess it's a matter of is the component a spreadsheet or a table?

**Comment by ivoelbert** [comment]
Both Google Sheets and Excel don't scroll on space. They start editing the selected cell. Also both _always_ have a selected cell.

I think it's reasonable to do the scrolling if you don't have a selected cell, and go into edit mode if you do?
Just going into edit mode if the selected cell is editable sounds confusing.

**Comment by jassmith** [comment]
Problem: There is no way to unselect a cell once one is selected. I would
argue escape should probably do that...

**Comment by ivoelbert** [comment]
Sounds reasonable. That was what I expected in GS and Excel, and none delivered 😄

**Comment by pzcfg** [comment]
> Problem: There is no way to unselect a cell once one is selected. I would argue escape should probably do that...

I can unselect cells by clicking the empty space to the right or bottom of the cells (if that's set)

**Comment by jassmith** [comment]
Thats fair but not reliably available.

**Comment by ivoelbert** [comment]
Huh, some notes on this:

- `esc` already clears your selection
- `space` and `shift+space` does scroll as expected, but only after a few interactions:

1. Go to [this story](https://glideapps.github.io/glide-data-grid/?path=/story/dataeditor--all-cell-kinds)
2. Click on some cell
3. Tap `esc` to clear your selection
4. Scroll down a bit (roughly half a page is enough on my setup, 2019 16' MBP on both Chrome and Safari)
5. Play around with `space` and `shift+space`

I still didn't dig too much into why it behaves this way.

**Comment by jassmith** [comment]
Its because focus is not inside the data editor until you click ;)
