### ISSUE TITLE
Smooth scroll with freezeColumns animation jank

### ISSUE THREAD

**Issue by twobit** [glideapps/glide-data-grid#171]
There's a slightly disorienting animation when smooth scroll and freezeColumns are enabled:

https://user-images.githubusercontent.com/2778/153683635-05f7a11b-6ede-4825-ae59-66b1a943e173.mov

Safari: 15.4
macOS: 12.3

**Comment by ivoelbert** [comment]
Looks like a Safari only bug (wow! who would've guessed that 🙄).

Apart from that, by looking at this in Chrome and Firefox I noticed that we're dropping a lot of frames when the shadow animation happens.

Thanks for reporting!

**Comment by jassmith** [comment]
Shadow animations causing jank... say it aint so :P

**Comment by bryhasagithub** [comment]
was able to reproduce on safari as well

**Comment by jassmith** [comment]
Fixed in main
