### ISSUE TITLE
Styling/themeOverride beyond last cell

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#175]
For one of my applications I am coloring the rows based on different criteria, and would like to be able to color the space beyond the last cell in the row.

<img width="1098" alt="Screen Shot 2022-02-15 at 12 13 14 PM" src="https://user-images.githubusercontent.com/94077014/154142790-c00b0145-a700-46c1-80ce-0f3bd63506c1.png">

The `themeOverride` for the `columns` prop already enables this in the vertical axis but I can't find a way to do it horizontally.

<img width="1113" alt="Screen Shot 2022-02-15 at 12 23 28 PM" src="https://user-images.githubusercontent.com/94077014/154143315-fe1c7769-a646-411f-a202-e75f202cf482.png">

**Comment by jassmith** [comment]
We could add a callback for that but it definitely will increase memory pressure a smidge. Lemme think if there is another option.

**Comment by jassmith** [comment]
So I think the solution here is going to look something like

`<DataEditor rowThemeOverride={row => makeThemeHere()} />`

**Comment by jassmith** [comment]
The only problem I have with this is it will get called at least twice per row so it would need to be efficiently implemented. It would be best if it was returning memoized results.

**Comment by jassmith** [comment]
other options
- `getRowTheme`
- `getRowThemeOverride`
- `describeRow`

A row theme would apply for the blank space too of course.

**Comment by jassmith** [comment]
Fixed in 3.4.0 via `getRowThemeOverride`
