### ISSUE TITLE
Show source code in storybook

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#177]
When looking through the storybook, I frequently want to see the code that was used. It looks like the `@storybook/addon-storysource` add-on supports this pretty well

<img width="1401" alt="Screen Shot 2022-02-15 at 4 19 29 PM" src="https://user-images.githubusercontent.com/94077014/154172359-b609d2b0-35b6-427c-b776-f98ac1bb730c.png">

However it would require not setting `showPanel: false` on examples without controls, and it also seems to load all ~2700 lines of the stories.tsx for each example. The "Displaying full source" section of the [docs](https://storybook.js.org/addons/@storybook/addon-storysource) mention an `injectStoryParameters` option to enable/disable this, however neither value seemed to have an effect for me.

Alternatively, if you'd prefer not to show the source inline, it would be great if it linked out to the relevant story on github, e.g. https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor-beautiful.stories.tsx#L722-L776

**Comment by jassmith** [comment]
Yeah I realized way too late that if these were all their own files... oh the glory that would have been.
