### ISSUE TITLE
Support Server Side Rending

### ISSUE THREAD

**Issue by crberube** [glideapps/glide-data-grid#19]
In order to get Glide working in a Next.js app I need to disable server side rendering for the component. This appears to be due to the usage of 'window' in the browser detect code which is not available server side.

> Server Error

> ReferenceError: window is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:/workspace/node_modules/@glideapps/glide-data-grid/dist/js/common/browser-detect.js (7:17)

**Comment by annelicia** [comment]
Hi, this issue seems to be coming up again, due to this line using document variable:

https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/use-column-sizer.ts#L82
