### ISSUE TITLE
Option to open cell overlay on hover

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#190]
Opening the cell overlay can only be done by selecting a cell first. This is a bit problematic if the cell selection itself is used to trigger certain actions. It would be great to have an option to allow the cell editor to also be opened on hovering over a cell (delayed for a few ms similar to tooltips). Here is an example from Google Sheets on how this could look like:

https://user-images.githubusercontent.com/2852129/156799562-ce25f9c2-398b-482b-b234-eed7266bfc74.mov

I would be open to implementing this feature if I have some free time in the next few weeks and if you think this would be useful for glide-data-grid.

**Comment by LukasMasuch** [comment]
Actually, I might be able to implement that with the `onItemHovered` event already. I will try this later today.

**Comment by jassmith** [comment]
I will take a look and see if this could be added as an optional hook. I am trying to make more composable behaviors added by hooks.

**Comment by jassmith** [comment]
so I have a branch that does this, and I think it's a pretty great feature but I think the "hover preview" and the open selection are fundamentally 2 different things. I currently implement it by setting the selected cell when you dwell but I dont like the interaction. Could really use some help speccing this out more fully.

**Comment by LukasMasuch** [comment]
Thanks for evaluating this 👍 I agree that the hover preview and open selection would require different treatments. But maybe it is possible to reuse the same cell overlay implementation, but use it in read-only mode for hover preview. Here is an idea: 

Hover over a cell (and maybe long-press on touch devices) opens the read-only cell overlay but does not select the hovered cell. The mouse pointer should now be within the cell overlay. Close the cell overlay as soon as the mouse pointer is moved outside of its boundaries. Only allow the hover preview if no other cell overlay is currently open (e.g. when a cell is edited). _Optionally, there could be an edit icon similar to how it is done with the URL cell editor. As soon as the edit icon is clicked, the cell gets selected and the cell overlay changes to edit mode._ Allow to enable this optional feature via an API property, e.g,. `enableHoverPreview: boolean;`.

**Comment by jassmith** [comment]
This is not going to happen for a while. Closing for now.

**Comment by chris-aeviator** [comment]
this would also be handy to get custom mouse pointers I guess
