### ISSUE TITLE
Theming is not applied for number input background

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#191]
The background color of the number input cell overlay is not adapted to the provided theme. In [this example](https://glideapps.github.io/glide-data-grid/?path=/story/dataeditor--theme-support) with the `dark` theme, the number input has a white background (and white font) while all other cell editors have the black background:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/2852129/156802275-55f961bf-9f9e-4ed7-88d6-d5b107b5ed7b.png">

**Comment by jassmith** [comment]
Fixed in 3.4.0
