### ISSUE TITLE
Hover indications on trailing row is sometimes broken

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#193]
In tables with at least a few thousend rows - in this example there are 2500 rows - the hover indication on the trailing row seems to fail to react sometimes: 

https://user-images.githubusercontent.com/2852129/156807249-76779e10-ffc0-4f66-9731-3f15a925f354.mov

Unfortunately, I haven't found a specific pattern yet on when this happens.

**Comment by jassmith** [comment]
Can you make a replay.io recording of this for me? I can't reproduce it.

**Comment by jassmith** [comment]
Fixed in 3.4.0
