### ISSUE TITLE
Change callbacks trigger even if there was no change

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#196]
The change callbacks - `onSelectedColumnsChange`, `onSelectedRowsChange`, `onGridSelectionChange` - get called also when there is no change in the respective selection. For example, `onSelectedRowsChange` gets called whenever a cell is selected,  a column is selected or escape is pressed even so no row was selected before. There is an easy workaround by checking against the current selection state (`selectedRows`, `selectedColumns`, `gridSelection`). However, I don't know if that is indeed the desired behavior? Maybe this check with the actual selection state could be implemented directly into glide-data-grid?

Btw. `onGridSelectionChange` is currently not documented in the API docs. Is it safe to use this callback?

**Comment by ivoelbert** [comment]
Good call. I think we shouldn't trigger the event if things didn't actually change.

> Btw. onGridSelectionChange is currently not documented in the API docs. Is it safe to use this callback?

Yes! We need to seriously revamp the docs. Will do.

**Comment by jassmith** [comment]
Docs are fixed, PR open to resolve eventing issues
