### ISSUE TITLE
Add callback to detect the clearing of all selections

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#197]
For my use case, I need to react to the event when all selections are cleared (when escape is pressed). This turned out to be a bit complicated to implement with glide-data-grid, since this event currently only triggers all individual selection change callbacks. I struggled a bit with detecting that indeed all selections were cleared on the basis of the individual callbacks. My hacky workaround was to also react to the escape key.

A solution for this might be to add an `onSelectionsCleared` callback that is called when escape is pressed. In addition, it might be useful to add a way to also trigger the selection clearing via the API - e.g. `clearSelections` - similar to how `showSearch` works. This could be useful to implement a clearing action in a table toolbar or on mobile where we don't have the escape hotkey.

**Comment by jassmith** [comment]
Great idea, I love it.
