### ISSUE TITLE
Cell overlay for read-only cells is not closed on escape

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#198]
Cell overlays in editing mode close when the escape hotkey is pressed. However, cell overlays in read-only mode are not closed. This can be replicated on the [storybook](https://glideapps.github.io/glide-data-grid/?path=/story/dataeditor--automatic-row-markers).

**Comment by ivoelbert** [comment]
Thanks for reporting! Looks like a bug. Will fix.

**Comment by jassmith** [comment]
There is an open PR. It's very simple yet very scary and could definitely use some testing.
