### ISSUE TITLE
Editing Cells

### ISSUE THREAD

**Issue by crberube** [glideapps/glide-data-grid#20]
After following the initial setup steps under the `HTML/CSS Prerequisites` and the code from the `using` section of the README, I am not able to enter the editing mode by clicking on a cell. In the DOM the portal element is not changing. 

Is there something that I need to enable in order to allow for the editing UI when clicking on a cell? I am using an `EditableGridCell`. If I set `allowOverlay` to true I do get an editable box which appears to work as expected.

**Comment by jassmith** [comment]
Can you show me your code?

**Comment by crberube** [comment]
Sure. I was trying to get a feel for things by following the example code in the repo.

Main body looks as follows:
```html
<body>
...
<div id="portal" />
</body
```

I have set the columns as follows:
```js
 const columns: GridColumn[] = [
        { title: 'Number', width: 100 },
        { title: 'Square', width: 100 },
    ]
```

defined the data editor container:
```js
 <DataEditorContainer width={500} height={300}>
            <DataEditor
                getCellContent={getData}
                columns={columns}
                rows={1000}
            />
        </DataEditorContainer>
```

and the `getData` function:
```js
function getData([col, row]: readonly [
    number,
    number
]): EditableGridCell {
    let n: number
    if (col === 0) {
        n = row
    } else if (col === 1) {
        n = row * row
    } else {
        throw new Error('This should not happen')
    }
    return {
        kind: GridCellKind.Number,
        data: n,
        displayData: n.toString(),
        allowOverlay: false,
    }
}
```

I am able to select cells fine, but the `<input>` elements do not appear. When changing `allowOverlay` to `true` I am able to edit in the overlay input box but the value in the cell does not change.

**Comment by jassmith** [comment]
Oh okay yes, sorry I thought your question was something else.

Set `allowOverlay` to true for cells you want to be editable. Then hook up the onCellEdited callback in your DataEditor and make sure your cells content gets updated correctly.

**Comment by crberube** [comment]
Great thank you for the clarification. 

Should the overlay be placed directly over the cell being edited by default? I am seeing behavior where it opens a few cells above such as in https://github.com/glideapps/glide-data-grid/issues/17 (but on desktop). I do not see this behavior on desktop when using the demo.

**Comment by jassmith** [comment]
Can you check and make sure your portal is positioned at 0,0? Maybe the portal is somehow being offset?

**Comment by jassmith** [comment]
Also just a working example I could look at would be very helpful
