### ISSUE TITLE
CommonJS distribution is not picked up in combination with Jest

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#206]
I use Jest for testing and had the following issue related to glide-data-grid:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    ./node_modules/@glideapps/glide-data-grid/dist/js/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { DataEditor } from "./data-editor/data-editor";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

To solve this, I added `transformIgnorePatterns = ["/node_modules/(?!glideapps)/.+\\.js$"]` to my Jest config. Since there is a viable workaround, this issue can be most likely directly be closed. However, I found it a bit strange that Jest is not able to pick up the CommonJS distribution that is shipped with glide-data-grid and instead uses the ES6 distribution in the `js` folder. So, maybe there is an issue with glide-data-grid on how it is transpiled to CommonJS?

**Comment by jassmith** [comment]
A reproduction case might be handy here. I will be the first to admit that I'm not a cjs vs modules wizard. We use jest for our own testing internally, I'm not quite sure what could be going wrong.

**Comment by LukasMasuch** [comment]
I will try to provide a reproducible example soon. There is also another issue I'm running into during build, but this might be quite likely related to my build setup:

```
Failed to compile.

./node_modules/@glideapps/glide-data-grid/dist/js/markdown-div/markdown-div.js
Attempted import error: 'marked' is not exported from 'marked'.
```

**Comment by jassmith** [comment]
you have an incompatible version of marked.

**Comment by LukasMasuch** [comment]
Thanks for the hint. I did a bit of investigation: I'm quite certain that it uses the most recent version of marked (`4.0.12`). However, I assume my problem might be related to wepack version `<5` in combination with marked, as mentioned [here](https://github.com/markedjs/marked/issues/2265#issuecomment-967254700). Strangely, I have two development machines and only one has this error. Anyways, it is mostly related to my build setup.

Would it be an option to move any cell with external dependencies (markdown & image) to the `cells` package? This could lower some of the friction that comes from external dependencies in the core package. Maybe it would be even an option to have any custom cell in its own npm package. I thinking about contributing a date cell with editor support, but this would also require yet another external dependency.

**Comment by jassmith** [comment]
What I really want to do is gracefully degrade when the dependencies are not present. Basically just fall back to the regular text entry.

**Comment by jassmith** [comment]
Closing as wont fix for now.
