### ISSUE TITLE
Return index mapping for useColumnSort and useMoveableColumns

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#207]
The new sources package is a great addition :) What I'm missing is a way to reconstruct the original row/column indices. Would it be possible to return the `sortMap` in `useColumnSort` and something similar in `useMoveableColumns`? Or is there any other way to map from the new row/column index of a cell to the original one?

**Comment by jassmith** [comment]
ah-doy what a silly oversight. Will add asap.

**Comment by jassmith** [comment]
For useMoveableColumns you should set id's on the GridColumns, they are there for this reason. useColumnSort will start returning a function `getOriginalIndex`

**Comment by jassmith** [comment]
Merged
