### ISSUE TITLE
Document preferred way for community contributions of cell types

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#209]
I'm planning to build some custom cell types soon (editable datetime cell & additional charting cells) and would love to contribute this back to `glide-data-grid`. As the package usage grows, I assume that many more developers are willing to contribute cell types as well. Is there currently a preferred way on how you would like to get cell-type contributions? I think there might be three options:

1) Encourage custom cell contributions into the `cells` package. However, with new custom cell types, the number of dependencies in the `cells` package grows as well (option 2/3 might be a more scalable option).
2) Encourage custom cell contributions into separate packages within the `glide-data-grid` repo (e.g. `glide-data-grid-cells-datetime`). 
3) Encourage custom cell contributions into separate repos outside of the glideapps organization.  

Regardless of what option is preferred, it would be great to have some documentation and/or template to lower the friction and unify the process of contributing new cell types.

**Comment by jassmith** [comment]
This is definitely something I need to both document and think about a bit. In the article-cell I added to the cells package for example I used a react.lazy to make sure we only lazy load in the editor as its quite heavy. This means that the dependency is still real, but if you never use that cell and you have a nice bundler you don't pay that cost.

example here: https://github.com/glideapps/glide-data-grid/blob/main/packages/cells/src/cells/article-cell.tsx

Will people be okay with that? No idea.

**Comment by LukasMasuch** [comment]
I think that might be sufficient. In the best case, this might also be combined with marking the peer dependencies as optional and maybe gracefully degrade to a text cell if the dependency is not installed (as you described in the [other issue](https://github.com/glideapps/glide-data-grid/issues/206#issuecomment-1068123371)). I'm a bit worried that only using the `react.lazy` might still cause trouble during development when one of the peer dependencies is not correctly installed (as my case with `marked`).

**Comment by jassmith** [comment]
Okay I played around a bit

- Use dynamic requires in a try catch works, but causes almost all bundlers to throw off nasty warnings if the optional deps are not available
- Using dynamic imports has the same problem but worse. Instead of warnings you get errors.
- Using react.lazy does cause bundlers to properly code split out the dep, but it is non-optional. Peer dep is fine, but non-optional.

I think we will need to go the react lazy route and probably create smaller packages of fewer cells.

**Comment by jassmith** [comment]
Documented in CONTRIBUTING.md
