### ISSUE TITLE
Sorting number cells as strings might cause unexpected results

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#211]
Number cells are sorted as strings when using `useColumnSort`: https://github.com/glideapps/glide-data-grid/blob/main/packages/source/src/use-column-sort.ts#L8. This might lead to unexpected sorting results since `99` as string will be sorted above `100` in a descending sort. I started a PR with a fix here: https://github.com/glideapps/glide-data-grid/pull/210

**Comment by jassmith** [comment]
Fixed in 4.0 by adding a smart sort option.
