### ISSUE TITLE
Keyboard shortcuts overhaul

### ISSUE THREAD

**Issue by jassmith** [glideapps/glide-data-grid#217]
Overhauling the keyboard shortcuts of the GDG will allow for a more consistent and accessible experience for all users.

| Shortcut | Status | Description |
|----|-----|----|
| Shift + Space | ✔ | Select row |
| Control + Space | ✔ | Select column |
| Space | ✔ | Start editing or toggle checkbox |
| Control + A | ✔ | Select the entire grid contents |
| Left/Right | ✔ | Select the cell to the left/right of the selection |
| Shift + Left/Right | ✔ | Extend the selection to include the next cell to the left/right of the selection |
| Up/Down | ✔ | Select the next cell above or below the selection |
| Shift + Up/Down | ✔ | Extend the selection to include the cell above or below the selection |
| PageUp/Down | ✔ | Select the cell one page above or below the selection |
| Shift + PageUp/Down | ❌ | Extend the selection to include the cell one page above or below the selection |
| Control+ Up/Down | ✔ | Move the selection to the first or last row |
| Control + Shift + PageUp/Down | ✔ | Extend the selection to include the first or last row |
| Home/End or Ctrl + Left/Right | ✔ | Move the selection to the first or last column |
| Shift + Home/End or Ctrl + Shift + Left/Right | ✔ | Extend the selection to include the first or last column |
| Ctrl + Home/End | ✔ | Move the selection to the first/last row and column |
| Shift + Ctrl + Home/End | ✔ | Extend the selection to include the first/last row and column |
| Escape | ✔ | Cancel current cell or row editing operation |
| Tab | ✔ | Move the selection to the next cell |
| Enter | ✔ | Exit editing mode and move the selection to the cell below the current one |
| Delete, Backspace | ✔ | Delete the currently selected rows, or clear the content of the selected cells (if the cells are writeable). |
| Control + C | ✔ | Copy the selection to the clipboard |
| Control + V | ✔ | Paste the content of the clipboard into the selected area |

## Changes required

```tsx
// Thoughts:
// rows/columns are called out as selected, but when selected they must also be added
// to the range. Handling delete events may have different desired outcomes depending on
// how the range came to be selected. The rows/columns properties retain this essential
// information.
export interface GridSelection {
    readonly cell: readonly [number, number];
    readonly range: Readonly<Rectangle>;
    readonly rangeStack: readonly Readonly<Rectangle>[]; // lowest to highest, does not include range
    readonly columns: CompactSelection;
    readonly rows: CompactSelection;
}
```

rows/columns are called out as selected, but when selected they must also be added to the range. Handling delete events may have different desired outcomes depending on how the range came to be selected. The rows/columns properties retain this essential information.

- [x] Update GridSelection
- [x] Remove `selectedRows`  and `selectedColumns` APIs
- [x] Remove `deleteRows` API
- [x] Add an `onDelete` API for all deletion, event single cell
- [x] Add `multiRange` which allows filling of the range stack with ctrl+click events
- [x] Add `multiColumn` which allows selecting multiple columns at once.
- [x] Add `multiRow` which allows selecting multiple rows at once.
- [x] Update `getCellsForSelection` to have an unambiguous API
- [x] Add `allowSelectionFromGetContent` to enable default `getCellsForSelection` callback, unsafe for virtualized data sources
- [x] `onGroupHeaderClicked` needs to be able to be cancelled and prevent group selection

**Comment by jassmith** [comment]
This change will mandate the release of a 4.0 due to the API changes. Porting for pretty much everyone should be painless except for anyone who is manipulating how selectedRows/Columns instead of just responding to them.

**Comment by jassmith** [comment]
These changes are motivated by a desire to dramatically improve the accessibility of glide-data-grid by improving the standardization of the keyboard shortcuts it uses. Currently many interactions are hard or impossible to do without a mouse. The API has led us down this path, and while I am not usually a "break API whenever" maintainer, a11y is a good reason to do it.

**Comment by jassmith** [comment]
Related to #141

**Comment by jassmith** [comment]
Fixed in 4.0.0

**Comment by mddanishyusuf** [comment]
How we can disable on Enter, add new row. I don't want to add new row with enter.

<img width="844" alt="Screenshot 2023-01-08 at 10 25 05 PM" src="https://user-images.githubusercontent.com/9165019/211208957-a579a61d-3d6b-434e-9e53-bebdc5de1734.png">

I love the data grid project. Great job @jassmith

**Comment by hyusetiawan** [comment]
want to echo @mddanishyusuf 's request, perhaps we can control the direction after pressing enter? for my use case: the next column of the same row
