### ISSUE TITLE
Build fails in CRA 5.0.0 (Webpack 5), due to ESM strict mode - "Module not found: Error: Can't resolve '../data-grid/data-grid-types'"

### ISSUE THREAD

**Issue by ewgenius** [glideapps/glide-data-grid#221]
I'm trying to use glide-data-grid in fresh application, bootstrapped by `creat-react-app@5.0.0`, but it fails to build it:

<img width="1171" alt="CleanShot 2022-03-24 at 21 19 49@2x" src="https://user-images.githubusercontent.com/827338/159984908-4ec4f67f-bcce-4564-aff7-0d24385ea70a.png">

It seems to be caused by ESM strict mode which is enabled by webpack 5 (since [v5.0.0-beta.30 release](https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.30)) which requires extensions in esm imports

### Possible solution

https://www.npmjs.com/package/typescript-esm might help here

---

### Reproduction example:

- https://github.com/ewgenius/cra-5-glide-data-grid-example - bare CRA@5 app with Typescript template
- failed build example https://github.com/ewgenius/cra-5-glide-data-grid-example/runs/5681360680?check_suite_focus=true

**Comment by jassmith** [comment]
Thank you, I will look into typescript-esm. Very annoying that they turned on strict mode in CRA 5, not sure I really see the benefit.

**Comment by ewgenius** [comment]
I've played a bit with `typescript-esm` in #222, and it seems to be working as expected:

<img width="1265" alt="CleanShot 2022-03-24 at 23 11 44@2x" src="https://user-images.githubusercontent.com/827338/160001853-54e91f85-3d57-4628-90e3-e692ef937aac.png">

Though there are still few problematic places with `data-grid/cells.mjs`, which should be `data-grid/cells/index.mjs`

![CleanShot 2022-03-24 at 23 12 45@2x](https://user-images.githubusercontent.com/827338/160002183-28ff36e1-a97e-4742-90db-4e0fe77d5768.png)

And also after manually fixing all of those imports, I've got same resolve error with `lodash`
There is [lodash-es](https://www.npmjs.com/package/lodash-es), but I'm not sure if it won't break non-es ubilds of glide-data-grid 😒

<img width="957" alt="CleanShot 2022-03-24 at 23 15 14@2x" src="https://user-images.githubusercontent.com/827338/160002355-37bdfe23-7d72-48a4-bad4-f3493e590ff3.png">

**Comment by jassmith** [comment]
If you don't mind my asking a dumb question, how are you testing this? Just copying build results into node-modules of your test project?

**Comment by jassmith** [comment]
I wonder how hard it would be to have a cra4 and cra5 test project in the repo that can be stood up with the a local build... That would make testing packaging issues like this easier.

**Comment by jassmith** [comment]
Could you test this branch? Seems to work for me: https://github.com/glideapps/glide-data-grid/pull/223

**Comment by jassmith** [comment]
Fixed in 4.0.0

**Comment by ewgenius** [comment]
Thank you for the quick fix!

> If you don't mind my asking a dumb question, how are you testing this? Just copying build results into node-modules of your test project?

I've just made local build of data-grid/core, packed it by `npm pack` and then installed in local project

Double checked branch `4.0.0` in my local app on both `react-scripts@4` and `react-scripts@5`, works without any problems 🚀
