### ISSUE TITLE
Export useCellSizer to allow automatic table width calculation

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#226]
It would be great if the `useCellSizer` hook is exported as part of this library. The use case for this would be a scenario where the table width needs to be automatically adjusted to the calculated width of all columns. For this scenario, the `useCellSizer` could be applied manually, and the calculated width of each column summarized to determine the total width of the table. Or, is there another good way for getting the calculated width?

**Comment by jassmith** [comment]
I am onboard with exporting, definitely needs a better name.

**Comment by LukasMasuch** [comment]
Replacing cell with column in the name might already give more clarity on the usage.

**Comment by jassmith** [comment]
Exported in 4.0

**Comment by LukasMasuch** [comment]
@jassmith  Thanks again for exporting it! I just implemented the table width adjustment, but actually decided to not make use of `useColumnSizer`. The reasons are 1) The hook requires quite a few parameters that are currently handled internally. This would add quite a bit of overhead 2) Determining the full canvas width can also be solved by using the `getBounds` on the data editor ref, e.g.:

```javascript
  useLayoutEffect(() => {
    setTimeout(() => {
      const firstCell = dataEditorRef.current?.getBounds(0, 0)
      const lastCell = dataEditorRef.current?.getBounds(
        columns.length - 1,
        numRows - 1
      )
      if (firstCell && lastCell) {
        const fullTableWidth = lastCell.x - firstCell.x + lastCell.width + 2

        if (fullTableWdith < propWidth) {
          setTableWidth(fullTableWidth)
        }
      } else {
        setTableWidth(propWidth)
      }
    }, 0)
  })
```

Maybe it could be useful to have another reference exposed that allows to directly access the canvas width and height since the trick above with getBounds is more of a workaround. Also, I think `useColumnSizer` is not as useful for this usecase as I thought, and I don't know if there are other usecases to have it exported. Maybe it is better to keep actually keep it internally since the interface is already a bit complicated for external usage.
