### ISSUE TITLE
Cell overlay for RowID cell is not functional

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#227]
The cell overlay for the `RowID` can be activated, but it will not contain any content. The reason is that it does not currently implement the `getEditor` property: https://github.com/glideapps/glide-data-grid/blob/47bae1e604add604e49ee34a8dc4bfbc18b6bd4f/packages/core/src/data-grid/cells/row-id-cell.tsx 
A fix would be to either change the `allowOveraly` to always be false like it is done with BooleanCell or to provide a (read-only) editor implementation for the `RowIDCell ` as well (based on the text cell editor). I would prefer that the `RowID` cell also has a cell overlay, it's probably debatable if it needs actual editing support or if read-only would be enough for most use cases.

**Comment by jassmith** [comment]
Should be easy enough to give it a full editor. Maybe default it to read only?

**Comment by LukasMasuch** [comment]
Yep, I think full editor with read-only default would be the most flexible solution 👍

**Comment by jassmith** [comment]
Fixed
