### ISSUE TITLE
More fine-grained control on column/row selection behaviour

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#228]
Glide-data-grid has very good support for column, row, and cell selection. However, it gets a bit complicated if certain selection aspects need to be deactivated. For example, the column selection can be fully deactivated via:

```javascript
selectedColumns={CompactSelection.empty()}
onSelectedColumnsChange={() => {}}
```

However, the cursor will still show click behavior even though there is nothing to select anymore. Also, deactivation of multi/range-selection of columns or rows could be theoretically achieved by a custom implementation... but it might get a bit complicated to determine the actual cell the user clicked on for enforcing a proper single row/column only selection. A solution might be to have a configuration similar to `rowMarkers` - e.g.: `columnSelectionMode?: "single" | "multi" | "none"` - that manages the selection behaviour internally.

**Comment by LukasMasuch** [comment]
I just had a look at the [changelog of `4.0.0`](https://github.com/glideapps/glide-data-grid/pull/220). Are the new multi-selection configurations (e.g. `columnMultiSelect`) intended for deactivating multi-selection behaviour and enforce single-selection?

**Comment by jassmith** [comment]
Yes that is their purpose. It still doesn't let you prevent range selection but I will fix that prior to launch of 4.0

**Comment by jassmith** [comment]
I do like being able to disable selection entirely. Will add that.

**Comment by jassmith** [comment]
I've updated the 4.0.0 selection behavior to be even more fine grained.

**Comment by LukasMasuch** [comment]
Awesome, thanks!
