### ISSUE TITLE
Minor issues with useCellSizer

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#229]
1) The maximum column width can be configured via `maxColumnWidth`. But the configured value is not used in `useCellSizer` since it uses a [hard-coded maximum of 500](https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/use-cell-sizer.ts#L85). 
2) There is a [minimum width of 50 applied to column resizing](https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-grid-dnd/data-grid-dnd.tsx#L180). However, the calculated width for `useCellSizer` can be less than 50, which can result in slightly strange behavior when resizing those columns. The optimal solution would be to also have a configurable minimum width that is consistently enforced for resizing and auto width calculation.
3) If a column contains an ascending number (1,2,3,...), the calculated width is not super useful since it only looks into the first X rows and does not take the larger numbers into consideration. Using the first X rows plus the last X rows might solve this slightly better in a few scenarios. This issue might also happen with other cell types that are presorted, e.g. a text cell that has all empty cells on top.

**Comment by jassmith** [comment]
First 9 + last 1 is a great idea. 100% making that a thing.

**Comment by jassmith** [comment]
Fixed
