### ISSUE TITLE
Feature Request: callback on user attempting to enter editor mode on cell, even if allowOverlay: false

### ISSUE THREAD

**Issue by reczy** [glideapps/glide-data-grid#230]
As the title suggests, I'd like to propose a callback for when a user presses enter or clicks on an already selected cell (ie, performs an action that would generally open up an editor), **regardless of whether the cell can enter editor mode**, and gives at least `[row, column]` information. 

My use case would be to allow the user to press enter or double click on a cell / row to open a modal or perform some other action outside the purview of glide-data-grid. `onCellClicked` misses out on the user pressing `Enter`.

I know there are a lot of moving pieces in 4.0.0 right now, but I don't think there is a callback is available to achieve this.

Potential names: onCellActivated? onCellSecondClickOrEnter?

Related to #120 

Thoughts?

**Comment by jassmith** [comment]
Any reason onCellClicked shouldn't be used?

**Comment by reczy** [comment]
Mainly because it doesn't pick up on the user pressing `Enter`. 

I think it would be easy enough to avoid first clicks (like where the user is wandering around the grid with the mouse).

**Comment by ivoelbert** [comment]
We'll trigger an `onCellActivated` event on those cases. Working on it.

**Comment by jassmith** [comment]
This is fixed in 4.0

**Comment by reczy** [comment]
Thank you. Very much appreciated!
