### ISSUE TITLE
Copy cell overlay content instead of all cells on select all keybinding

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#231]
The select all keybinding (in `4.0.0`) allows selecting all cells in the table. However, in case a cell overlay is open, it might be more intuitive to select all (text) content in that cell overlay. Otherwise, it has a bit of overhead for the user to quickly copy the content of a specific cell: 

https://user-images.githubusercontent.com/2852129/160715331-ec2f392b-3a97-45ab-bc15-e3b36b39087d.mov

**Comment by jassmith** [comment]
hmm interesting problem which may be hard to handle consistently with all use cases.

**Comment by LukasMasuch** [comment]
It seems to be a bit inconsistent since sometimes selectall keybinding selects the selectable text content (especially if it is not read-only) and sometimes it selects all cells. I assume that it might depend on the `textarea` in the cell overlay having focus or not. 

But I think it is not really too problematic since there is also the normal copy keybinding that can be used to quickly copy the content of a single cell. However, I think that for cells that have some a textarea (text cell, number cell, ...), it's slightly more intuitive if `select all` always selects all the cell content.

**Comment by jassmith** [comment]
Fixed in branch 4.0
