### ISSUE TITLE
Column sizer tries to access non existing rows

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#232]
There might be an issue with the computation of the `tailGetResult` in `useColumnSizer` (`4.0.0-alpha2`) here: 

https://github.com/glideapps/glide-data-grid/blob/v4.0.0-alpha2/packages/core/src/data-editor/use-column-sizer.ts#L75

I have a table with 1000 rows, but this line of code triggers requests in my `getCellContent` for rows `1001-1008`. I assume that `tailRows` needs to be used here instead of `computeRows`, or?: https://github.com/glideapps/glide-data-grid/blob/v4.0.0-alpha2/packages/core/src/data-editor/use-column-sizer.ts#L71

**Comment by jassmith** [comment]
Yup also doesn't account for trailing row correctly.

**Comment by jassmith** [comment]
Fixed in 4.0
