### ISSUE TITLE
Number input in cell overlay is not centered

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#233]
The number input in the cell overlay is not centered in my application while the text editor works fine. The difference seems to be that the text input uses a `line-height: 16px` (https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/growing-entry/growing-entry-style.tsx#L6) while the number input does not configure a `line-height`: https://github.com/glideapps/glide-data-grid/blob/v4.0.0-alpha2/packages/core/src/data-grid-overlay-editor/private/number-overlay-editor-style.tsx. Adding `line-height: 16px` to the number input seems to fix this issue. 

<img width="305" alt="image" src="https://user-images.githubusercontent.com/2852129/160737079-d624cf7b-d44f-4bc4-aa1e-121e06271143.png">

**Comment by jassmith** [comment]
Fixed in 4.0
