### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by vientang** [glideapps/glide-data-grid#24]
More of a question than an issue, but how much support is there for IE11? According to caniuse, the canvas api is supported in IE11 but I'm not familiar with any limitations if there are any. 

I realize there's not a huge demand for IE11 support but it'd be great to know, just in case.

**Comment by dvdsgl** [comment]
If you have access to IE11, you can try opening https://grid.glideapps.com/

**Comment by jassmith** [comment]
Yeah it definitely crashes.

**Comment by jassmith** [comment]
We wont be supporting IE11
