### ISSUE TITLE
Click on column header automatically selects the first cell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#240]
Clicking on the column header automatically selects the first cell in case no cell is selected in the table. I think this issue only started to happen with changes in the `4.0.0` branch. 

https://user-images.githubusercontent.com/2852129/161294105-aabac929-922f-4821-bba3-73130fdf508b.mov

**Comment by jassmith** [comment]
Which version of the 4.0.0 branch are you using? I think I fixed this
already.

**Comment by jassmith** [comment]
Can you get a reproduction case for me? I can't trigger it in our storybook.

**Comment by LukasMasuch** [comment]
Yep, I can try to construct a reproducible example later today 👍  

btw. it seems to only happen if `columnSelect={"none"}` is configured.

**Comment by jassmith** [comment]
Oh that makes sense now. Hmmmm lemme think about what to do about that.

**Comment by jassmith** [comment]
Fixed in 4.0
