### ISSUE TITLE
Provide a reference to access the canvas size

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#241]
It would be helpful if there would be a direct way to access the height and weight of the canvas. Maybe the `canvasRef` could be added to the exported `DataEditorRef`?

I'm currently using this workaround with `getBounds` to calculate the size:

```javascript
  useLayoutEffect(() => {
    setTimeout(() => {
      const firstCell = dataEditorRef.current?.getBounds(0, 0)
      const lastCell = dataEditorRef.current?.getBounds(
        columns.length - 1,
        numRows - 1
      )
      if (firstCell && lastCell) {
        const fullTableWidth = lastCell.x - firstCell.x + lastCell.width + 2
		// do something with fullTableWidth
	}
    }, 0)
  })
```

**Comment by jassmith** [comment]
The canvasRef bounds are not the height and width of the canvas anyway. In fact there may not be a DOM element which has the same bounds as the virtual scrolling region. I could add a method DataEditorRef which returns the virtual size but its implementation will be pretty much exactly what you have.

**Comment by LukasMasuch** [comment]
Alright, thanks for the information. So what actually reflects the total size of the table is the virtual scrolling region which is probably calculated [here](https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/scrolling-data-grid/scrolling-data-grid.tsx#L76) on the fly as well? I think in that case the `getBounds` workaround seems to be fine. `getBounds` looks like a bit complicated computation, but I assume that there is nothing computational heavy happening there, or?

**Comment by jassmith** [comment]
The actual virtual size can be computed by computing the width as the sum of all column widths and then the height as the totalHeaderHeight + height of all rows which can definitely be expensive if you have a lot of uneven rows.

**Comment by jassmith** [comment]
I've decided not to add this for now. It's too easy  to get otherwise when needed and generally speaking the computation shouldn't be slow enough to matter unless you are using it real time for some reason.
