### ISSUE TITLE
Issue with column resizing in combination with auto sized grid columns

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#246]
There appears to be an issue with column resizing in combination with automatically sized grid columns (`AutoGridColumn`). This can be reproduced with the glide-data-grid demo table:

https://user-images.githubusercontent.com/2852129/161433310-2ee6ef6e-c08c-4ad5-a487-538e3483dc92.mov

This does not happen if the width of the columns is specified (`SizedGridColumn`).

**Comment by jassmith** [comment]
Will fix

**Comment by jassmith** [comment]
Fixed in 4.0.1
