### ISSUE TITLE
Grid selection jumping between cells

### ISSUE THREAD

**Issue by matthewtorgerson** [glideapps/glide-data-grid#248]
When using the `DataEditor` version 4.0.0, changing the selected cell (via click or keyboard) will cause the grid to cycle between the newly selected cell and the previously cycled cell forever.  I am using Chrome Version 99.0.4844.84 in macOS Big Sur.  See attached video and stackblitz.

https://user-images.githubusercontent.com/1891714/161602807-76a9007d-30e3-4ec7-9c86-b24d3e06e3e0.mov

https://stackblitz.com/edit/vitejs-vite-hqbbed?file=src/App.tsx

**Comment by jassmith** [comment]
Appears to be an issue specific to React 18. Can you please confirm?

**Comment by matthewtorgerson** [comment]
I am using React 18.  I tried in both concurrent mode and normal mode, the issue appears in both.

**Comment by matthewtorgerson** [comment]
Just confirmed, the bug does not occur when I downgrade to React 17.

**Comment by jassmith** [comment]
could you please make a replay.io recording?

**Comment by jassmith** [comment]
There is a fix in https://github.com/glideapps/glide-data-grid/pull/247

**Comment by jassmith** [comment]
4.0.1-beta2 is available now, if you wouldn't mind giving it a test. There are likely more react 18 related issues as it is new and has a lot of subtle behavioral changes.

**Comment by matthewtorgerson** [comment]
Thank you for the quick turnaround and the excellent library!  Sorry I did not have time to do a replay.io recording yesterday, I will verify the changes today and keep an eye out for other React 18 bugs.

**Comment by jassmith** [comment]
Fixed in 4.0.1
