### ISSUE TITLE
Adding new row using right-most column results in error

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#249]
When adding a new row at the bottom of the grid (through `trailingRowOptions`) on the right-most column, there's an uncaught promise error: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')` 

Replication Steps:
1. Navigate to this storybook demo https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--trailing-row-options
2. Open developer console
3. Add a new row using the "+"  under `Column 59`

**Comment by jassmith** [comment]
Fixed in 4.0.1

**Comment by jassmith** [comment]
You can great 4.0.1-beta2 to test the fix if you want.
