### ISSUE TITLE
getCellContent is invoked for row past end after editing a cell on the last row

### ISSUE THREAD

**Issue by ssvendsen** [glideapps/glide-data-grid#255]
Hi. See e.g. the example project for editing cell content:
https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-docs--editing-data
Select a cell on the last row. Edit it's content and press enter to close the cell editor. The example crashes. 
I think it happens because the cell below the one that was edited receives focus, and getCellContent is invoked for it. 
Is there a way to prevent this behavior when editing cells on the last row (and possibly rightmost column)?
Thanks for making this impressive component available!

**Comment by jassmith** [comment]
Great find will fix and release a package asap

**Comment by jassmith** [comment]
This is fixed in 4.0.3-alpha1
