### ISSUE TITLE
Add example code to documentation.

### ISSUE THREAD

**Issue by infinitepr0** [glideapps/glide-data-grid#258]
Maybe use something like this - https://github.com/storybookjs/storybook/tree/master/addons/storysource?

**Comment by jassmith** [comment]
I'll try to get a single full example up with code. The problem is the code for a fully interactive data grid with editing and sorting and the works can be 200 lines or so. Not a great example.

**Comment by infinitepr0** [comment]
A link in the storybook to the corresponding file/folder on github works too.

**Comment by jassmith** [comment]
Not going to action right now. I am instead going to continue expanding the docs section of storybook which has code inline with examples and explanations.

**Comment by JoeVanGundy** [comment]
@jassmith 
Hi there! A little confused by the documentation. Is there a way of seeing the inline examples in the Storybook?
For example, I want to see the code for this example `https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--stretch-column-size`.

Do I just need to search the repo looking for the story file with the example in it?
Or is there an easier way?

**Comment by JoeVanGundy** [comment]
> I will see if I can't get this done soonish. The problem is the sources are all mangled into a single source file.

That would be super appreciated! Just getting starting switching over from the Antd table and liking everything we've seen so far!

Another question, do you have a Codesandbox or even just a sample file that you can point us to?
For example, trying to figure out to use the `grow` property. Do I need to include it in the column object passed to me from my server, or do I need to inject it client side into the `columns`?
It would be super useful to see a practical example of a table that's reading in real data and using some of the features.

**Comment by jassmith** [comment]
You can inject it client side or pass it from the server the grid does not care so long as the grow flag is set by the time it gets the GridColumn[]

**Comment by JoeVanGundy** [comment]
> You can inject it client side or pass it from the server the grid does not care so long as the grow flag is set by the time it gets the GridColumn[]

Gotcha, so something like this is the best way to handle letting the columns fill the empty space?
If so then all good!
```
  const formattedColumns = useMemo(
    () =>
      columns.map((c) => {
        return { ...c, grow: 1 };
      }),
    []
  );
```

**Comment by JoeVanGundy** [comment]
> yup thats exactly how we handle it in our product.

Sweetness, thanks again! Really pumped about this project!
