### ISSUE TITLE
Custom cell usage

### ISSUE THREAD

**Issue by infinitepr0** [glideapps/glide-data-grid#260]
Can you please provide an example on how to use the custom cells from `glide-data-grid-cells`? Also, how would I implement my own cell in my project?

**Comment by infinitepr0** [comment]
I did go through [this](https://github.com/glideapps/glide-data-grid/blob/main/packages/cells/src/cell.stories.tsx), but it doesn't work in NextJS.
```
./node_modules/@toast-ui/editor/dist/toastui-editor.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@glideapps/glide-data-grid-cells/dist/js/cells/article-cell-editor.js
```

**Comment by infinitepr0** [comment]
Would it be possible to create a plugin system, where only the necessary custom cells are loaded and registered? Similar to how [handsontable](https://handsontable.com) does it.

**Comment by jassmith** [comment]
Look into how this is done here for dynamic loading in next. https://github.com/glideapps/glide-data-grid/tree/main/test-projects/next-gdg

**Comment by infinitepr0** [comment]
Yep, I used `next/dynamic` to load the grid, which works well until `useExtraCells` is imported.

**Comment by jassmith** [comment]
is your usage of `useExtraCells` inside of the dynamic or outside of it? I don't think next should be loading it unless its outside the dynamic?

**Comment by infinitepr0** [comment]
Yep, I'm using it within the component file loaded using `next/dynamic`.

**Comment by jassmith** [comment]
wtf is going on with next loading the dep server side if its inside a dynamic. I thought the entire point of the dynamic was to prevent that...

**Comment by jassmith** [comment]
I like it, `glide-data-grid-cells` should keep its current super export but it can grow individual exports as well. This way we can maintain back compat.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/commit/45fce27fe671de87da8440ef9d29c9ef9cedd356

**Comment by infinitepr0** [comment]
Any way I can test the update? Maybe a beta release?

**Comment by jassmith** [comment]
4.0.3-alpha2 should be out in 2 to 3 minutes

**Comment by infinitepr0** [comment]
Can confirm (from limited testing) that `useCustomCells` works as intended.
However, importing just `DropdownCell` from `glide-data-grid-cells` causes NextJS to throw the above mentioned error, so I suppose article cell editor is still being imported in some way or the other.

**Comment by infinitepr0** [comment]
Would making each cell type a dedicated package (`glide-data-grid-cells-dropdown`, `glide-data-grid-cells-star` etc) be ideal? I can think of several advantages, including isolation of components and reduction of dependencies.
Can't think of any real downsides apart from having to publish several packages than one unified module.

**Comment by jassmith** [comment]
how are you importing DropdownCell? you should be able to do `import DropdownCell from "@glideapps/glide-data-grid/cells/dropdown-cell"`

**Comment by infinitepr0** [comment]
Oh, I did `import { DropdownCell }` from `@glideapps/glide-data-grid`. Will give that a spin, thanks!

**Comment by jassmith** [comment]
Looking forward to hear if it works. I can't see why next wouldn't tree-shake that correctly.

**Comment by infinitepr0** [comment]
It's works well, thanks for the quick help!

**Comment by jassmith** [comment]
Yes of course it is possible, when using with Next however it is
recommended to wrap the data grid in a component which is then imported as
a `dynamic`. Canvas doesn't really render on the server correctly anyway.
