### ISSUE TITLE
How to get Custom Cell / Extension to work?

### ISSUE THREAD

**Issue by Dawesign** [glideapps/glide-data-grid#262]
In your docs you are showing some custom cells such as dropdowns. I can't find any hints about getting them to work. Can you please let us know how one would implement a dropdown cell?

**Comment by jassmith** [comment]
I have updated the readme [here](https://github.com/glideapps/glide-data-grid/tree/4.0.3/packages/cells) to show how to `useExtraCells` from the `@glideapps/glide-data-grid-cells` package to get the dropdown cell if you desire.

You can also go look at the source of the dropdown cell in that package if you want to see how to do it yourself.
