### ISSUE TITLE
Better importing of official custom cells

### ISSUE THREAD

**Issue by infinitepr0** [glideapps/glide-data-grid#267]
Would making each cell type a dedicated package (`glide-data-grid-cells-dropdown`, `glide-data-grid-cells-star` etc) be ideal? I can think of several advantages, including isolation of components and reduction of dependencies.
Can't think of any real downsides apart from having to publish several packages than one unified module.

_Originally posted by @infinitepr0 in https://github.com/glideapps/glide-data-grid/issues/260#issuecomment-1099939224_

**Comment by infinitepr0** [comment]
Or maybe exporting each cell file to be imported like `import StarCell from "@@glideapps/glide-data-grid-cells/star-cell`

**Comment by jassmith** [comment]
It’s a pretty big downside to be fair…

**Comment by jassmith** [comment]
We're going to stick with the current plan.

**Comment by infinitepr0** [comment]
No plans to export the individual files?

**Comment by jassmith** [comment]
I can do that.

**Comment by jassmith** [comment]
`import StarCell from "@glideapps/glide-data-grid-cells/cells/star-cell` works
