### ISSUE TITLE
Freeze horizontal scroll when scrolling vertically on mobile

### ISSUE THREAD

**Issue by feketegy** [glideapps/glide-data-grid#27]
It's hard to use when trying to scroll down the list on mobile because it also scrolls horizontally too. Freeze horizontal scrolling if the intent is to vertical scroll and vice-versa.

See this sample, tried to scroll down the list, also scrolled horizontally, lost track of the position I was looking for: https://imgur.com/a/eFBvWHC

**Comment by jassmith** [comment]
To fix this we would need to dramatically override the default scrolling behavior of browsers. At this time we are not going to do this.

**Comment by jassmith** [comment]
This works now if you enable `preventDiagonalScroll`
