### ISSUE TITLE
cannot override row border color

### ISSUE THREAD

**Issue by bjgrosse** [glideapps/glide-data-grid#270]
It seems that no matter what I set to `borderColor` or `horizontalBorderColor` in my `getRowThemeOverride`, the border color values from the global theme are used instead. Other values from `getRowThemeOverride` are applied fine.

**Comment by jassmith** [comment]
which border would you expect to be overridden by the row themes border color props? Top or bottom?

**Comment by bjgrosse** [comment]
Either one. Currently nothing changes with the row border overrides

**Comment by bjgrosse** [comment]
Also overriding the borderColor in the cell theme override has no effect.

**Comment by jassmith** [comment]
Due to performance reasons the borders cannot be overridden at the cell
level. One of the major optimizations of the grid is drawing the borders in
a single pass. Changing even the row theme border color will have some
negative impact but not nearly as bad as doing it per cell.

**Comment by jassmith** [comment]
Fixed on 4.0.3
