### ISSUE TITLE
Can't import DataEditor in codesandbox.io

### ISSUE THREAD

**Issue by bjgrosse** [glideapps/glide-data-grid#271]
I know it's best for you guys to have a working example of a problem when reported. I'm trying to set up a base codesandbox.io project that I (and others) could use for this purpose, but I can't even import the DataEditor from glide:

https://codesandbox.io/s/epic-gates-wmexlr?file=/src/App.js

![image](https://user-images.githubusercontent.com/14151299/163793555-d6c993fd-0f45-4723-9e7c-e2bf3e95ac5d.png)

Any ideas?

**Comment by jassmith** [comment]
This is a bug in codesandbox unfortunately: https://github.com/codesandbox/codesandbox-client/issues/6435
