### ISSUE TITLE
Request: more flexibility to custom draw the trailing row

### ISSUE THREAD

**Issue by bjgrosse** [glideapps/glide-data-grid#272]
It appears that right now the only cell of the trailing row which we have a chance to custom draw is the row header. Would love the ability to draw the cells in that row myself.

**Comment by jassmith** [comment]
What are you wanting to put there, just out of curiosity.

**Comment by bjgrosse** [comment]
My goal: be able to color the trailing row cell backgrounds, _but not the empty area to the right of the last column_. If I use the row theme override to set the bgCell, then it colors the whole row, not just the cells of my columns. I just want to color the cells of the columns, not the white space.

**Comment by jassmith** [comment]
Im going to punt this to 4.0.4, I dont have time to get this to 100% and I really want to get 4.0.3 out the door due to it having crash fixes.

**Comment by bjgrosse** [comment]
This would be brilliant! Thank you @jassmith!

**Comment by jassmith** [comment]
Fixed in 4.0.4
