### ISSUE TITLE
New `onColumnResize` is not showing the resize indicator on hover

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#289]
When using the new `onColumnResize` instead of the deprecated `onColumnResized`, the resize indicator is not displayed on hover.

`onColumnResized`:

https://user-images.githubusercontent.com/2852129/165134103-1bb9f562-a796-4102-99bb-2ec50b973bae.mov

`onColumnResize`

https://user-images.githubusercontent.com/2852129/165134074-a842d87b-6d13-42de-a5f8-1b45a1ccd97d.mov

**Comment by ivoelbert** [comment]
Thanks for submitting that PR!
