### ISSUE TITLE
handle for custom / extra cells disappears on mouse move

### ISSUE THREAD

**Issue by Dawesign** [glideapps/glide-data-grid#303]
I have implemented several custom cells that are provided to the data grid via `useCustomCells`.
I have set the `fillHandle` prop true on the data grid.

The handle renders as expected on "normal" cells as soon as you click them but on custom cells it only renders when the cell gets clicked and vanishes upon mouse move within the cell. To me it appears as if as soon as the `draw` method of the `CustomCellRenderer` is called, the issue occurs. The functionality of the handle however remains. It appears that only the visual rectangle itself is not getting rendered.

I am using version 4.0.3 but have also encountered this issue on 4.0.2.
I am also having this issue for the extra cells using `useExtraCells`.

**Comment by jassmith** [comment]
A temporary fix is to not overdraw that region but yeah this is a problem I
will solve.

**Comment by jassmith** [comment]
Fixed in main

**Comment by jassmith** [comment]
A temporary fix is to not overdraw that region but yeah this is a problem I
will solve.
