### ISSUE TITLE
selectColumn doesn't work on MacOS

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#304]
glide currently uses `primary+space` to select a column.
https://github.com/glideapps/glide-data-grid/blob/e6117af1d4a93a3f8a8f01d8a4a8db1d0f2f51bd/packages/core/src/data-editor/data-editor.tsx#L1926

On MacOS, `command+space` is reserved to open spotlight by default. As a result, both Google Sheets and Excel map select column shortcut to `ctrl+space` instead.

https://support.google.com/docs/answer/181110?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cmac-shortcuts

https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f#bkmk_selectcells&PickTab=macOS

**Comment by jassmith** [comment]
Fixed in main
