### ISSUE TITLE
rowMarkers affect column index

### ISSUE THREAD

**Issue by ssvendsen** [glideapps/glide-data-grid#306]
Ref https://github.com/glideapps/glide-data-grid/blob/main/packages/core/API.md#rowmarkers, displaying row markers should not affect column indexes. But I think either the updateCells request or the getCellContent callback is affected.
Given a request to update the cell at column 1 row 0 by invoking updateCells([ {cell: [1, 0]} ]).
With rowMarkers not set, the getCellContent callback is invoked with cell = [1, 0]
With rowMarkers set to "number" the getCellContent callback is invoked with cell = [0, 0]
Is the column index change in the callback expected?

**Comment by jassmith** [comment]
Fixed in main

**Comment by ssvendsen** [comment]
Thanks for addressing this.
Too late for my demo but since I made it it I'll post it :)
https://github.com/ssvendsen/glide-data-grid-row-markers

**Comment by ssvendsen** [comment]
I can confirm that it works as expected with 4.0.4-alpha1 :thumbsup:
