### ISSUE TITLE
Unused `showUnchecked` property of boolean cell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#308]
The `showUnchecked` property of boolean cell seems to not have any actual usage. It is only used in some tests/stories:

https://github.com/glideapps/glide-data-grid/blob/fabca8608293d9649cc7b45d503078a9192c6d7f/packages/core/src/data-grid/data-grid-types.ts#L391

**Comment by ivoelbert** [comment]
Not sure why this property is there, and I'm also not sure if removing it is a breaking change and thus requires a major bump. Anyways I'm making a PR for that cause it's trivial.

**Comment by jassmith** [comment]
Should be marked as deprecated

**Comment by jassmith** [comment]
Fixed in 4.0.4
