### ISSUE TITLE
Support for null/undefined value in boolean cell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#309]
The boolean cell currently is only able to show a checked or unchecked checkbox. However, in case the cell value is actually null or undefined, it would be great if it would hide the checkbox. This is useful for tables that contain missing data.

**Comment by ivoelbert** [comment]
Little behavior change proposed by @jassmith:

https://github.com/glideapps/glide-data-grid/pull/310#discussion_r862117930

**Comment by LukasMasuch** [comment]
Yep, that sounds good :)

**Comment by jassmith** [comment]
Fixed in 4.0.4
