### ISSUE TITLE
Column sizer calculates wrong width in some cases

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#312]
There seems to be an issue with the column sizer. In some cases, the calculated width is completely wrong. I believe there is a bug in this line:

https://github.com/glideapps/glide-data-grid/blob/02a6a57c3146615fab32f2cee6a8a650bb9347f3/packages/core/src/data-editor/use-column-sizer.ts#L136

I'm not sure why the `average * 2` is used here, but I think it should either be:

```
const biggest = sizes.reduce((a, acc) => (a > average * 2 ? a : Math.max(acc, a)));
```

or:

```
const biggest = sizes.reduce((a, acc) => Math.max(acc, a));
```

**Comment by jassmith** [comment]
It's meant to prevent outliers from completely throwing off what a "decent" size might be. Basically it ignores any cell which is twice the size of the average cell width. This way if you for example have a bunch of cells with true/false, but one cell with the entire works of shakespear you don't end up with a silly column size for the sake of one cell.

**Comment by LukasMasuch** [comment]
Got it! That makes sense 👍  However, there still is a problem with how the outliers are ignored. I have opened a PR here to fix that: https://github.com/glideapps/glide-data-grid/pull/313 
Also, I think that for tables with only very few items (e.b. <5) it is better to not apply the outlier removal.
