### ISSUE TITLE
Allow configuration of text alignment for number/text cells

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#315]
Numbers are usually right aligned in spreadsheet software (e.g. Excel and Google Sheets) since it makes it easier to compare numbers:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/2852129/166839291-574b26f1-7ed2-4507-b316-f43eada7827c.png">

 I would love to have an option in glide-data-grid as well to right-align the rendered text in a cell. I build my own custom cell to do this using the `textAlign` canvas configuration, but I love to have this integrated directly into the core of glide-data-grid. I think there are two good options for this:

- Option 1 (preferred): Provide the text alignment as part of the theme.  This would allow the most flexibility since the theme can be already overwritten for any column, row, or individual cell.

- Option 2: Provide an alignment property for `NumberCell` (or other text-based cells) which is applied to that cell.

**Comment by BrianHung** [comment]
Here's how I'm handling it in my custom text cell, but +1 maybe out of the box configuation.

```ts
    const textWidth = metrics.width;
    const textHeight = metrics.actualBoundingBoxAscent + metrics.actualBoundingBoxDescent;

    let xOffset = x + theme.cellHorizontalPadding + 0.5;
    if (cell.format?.horizontalAlignment === "right") {
      xOffset = x - theme.cellHorizontalPadding + w - textWidth + 0.5;
    } else if (cell.format?.horizontalAlignment === "center") {
      xOffset = x + (w - textWidth) / 2 + 0.5;
    }

    if (cell.format?.textFormat?.strikethrough) {
      ctx.fillRect(xOffset, y + h / 2, textWidth, 1);
    }

    if (cell.format?.textFormat?.underline) {
      ctx.fillRect(xOffset, y + (h + textHeight) / 2, textWidth, 1);
    }

    ctx.fillText(data, xOffset, y + h / 2);
```

**Comment by jassmith** [comment]
What should the overflow behavior of a right aligned number be? Show
trailing text or show leading text?

**Comment by LukasMasuch** [comment]
I would expect to see the leading text in a case of overflow. That's at least how Google Sheets handles it: 
![image](https://user-images.githubusercontent.com/2852129/167036561-7a88223e-ebea-4263-ad8e-24e6ea88e0cb.png)

**Comment by jassmith** [comment]
So after some digging about I think the solution is to provide both a textDirection and textAlign in the base cell. Changing this may have some serious performance impacts if it changes regularly from cell to cell when scanning column by column. This is because the cavnas will reload the font each time if that happens. Also mixed textDirection and textAlign (e.g rtl + right align) cannot be done without measuring the text which will also introduce some mild overhead. This should not impact default options but its worth knowing.

**Comment by LukasMasuch** [comment]
@jassmith I did a small draft implementation today on this feature (see this PR: https://github.com/glideapps/glide-data-grid/pull/331) and I think we might not need any text measurement at all. If the user has provided a `textAlign` -> apply this and ignore the text direction. If no `textAlign` is set, use `end` as default for RTL text and `start` as default for everything else.

**Comment by jassmith** [comment]
This is now in 4.0.4
