### ISSUE TITLE
[Feature Request] Custom keybindings

### ISSUE THREAD

**Issue by jerebtw** [glideapps/glide-data-grid#318]
It would be nice if you can add a custom onKeyDown event (or something like the onKeyDown event) for example for a custom search

But also restricted to a special site/view like when you edit a cell or just viewing the grid

**Comment by jassmith** [comment]
Im sorry can you give me more details? I'm a bit confused about what you are asking for.

**Comment by jerebtw** [comment]
I would like to add custom key bindings

**Comment by jerebtw** [comment]
Yes that would be great

**Comment by jassmith** [comment]
That is the eventual idea

**Comment by jassmith** [comment]
This is fixed by #831

**Comment by jassmith** [comment]
Fix now merged in 6.0.0
