### ISSUE TITLE
Add Storybook Source Code Addon

### ISSUE THREAD

**Issue by nandorojo** [glideapps/glide-data-grid#319]
Currently, when browsing the story book, it's really difficult to find the source code for a given example.

Maybe this plugin could help? https://storybook.js.org/addons/storybook-source-code-addon

I'm not too familiar with Storybook, but it would be nice to easily access the actual source for the examples to know how to implement them. Thanks so much for making this open source!

**Comment by jassmith** [comment]
Yeah its something I mean to do at some point but right now the limiting factor is I shoved all the source for the stories in one file and it makes that plugin very very unhappy :P

**Comment by nandorojo** [comment]
haha fair enough, once i found that file it got a little easier. maybe linking to that file somewhere would be enough

**Comment by city17** [comment]
> 

Which file is this, I'm having trouble finding it? I can see a few files for the first Storybook pages, but not for all the special use cases.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/stories/data-editor-beautiful.stories.tsx

**Comment by irisjae** [comment]
> https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/stories/data-editor-beautiful.stories.tsx

Hi, I can only find this file on the branch `5.2.1`, which does not seem to contain examples such as `SearchAsFilter`; where should I be looking to find it?
