### ISSUE TITLE
Bulk Edit

### ISSUE THREAD

**Issue by nandorojo** [glideapps/glide-data-grid#320]
Is there a way to edit multiple cells at once? For example, if you highlight ten cells that have a checkbox, and you want to check/uncheck them all? Thank you!

**Comment by jassmith** [comment]
Check the top checkbox, highlight a bunch of cells under, press Ctrl + D
assuming you enabled the downfill keybind. You can also enable the fill
handle to allow doing this with mouse.

**Comment by nandorojo** [comment]
Wow awesome thanks for the fast reply. I'll try this out!

**Comment by nandorojo** [comment]
PS, I was in YC W'19!

**Comment by nandorojo** [comment]
Okay, so this did work @jassmith. However, I have one open question. Is there a way for a bulk edit to fire as a single event? As it stands, editing 50 cells in one swipe will fire `onCellEdited` 50 times. 

It would be nice if this could be paired into a single callback to avoid firing multiple mutations to the backend. I worry that sending many different ones could result in some working, but not others. How do you handle batching for these cases?

Thanks!

**Comment by nandorojo** [comment]
One solution to this would be if there is a callback for whenever someone selects different cells. This way, I could do the editing outside of the table. 

Is there a way to track which cells are selected?

Thanks!

**Comment by nandorojo** [comment]
I'll move this into a separate issue.

**Comment by jassmith** [comment]
React 17 or 18?

**Comment by nandorojo** [comment]
i’m currently on 17

(i assume react 18 will batch the updates resulting in fewer renders, but presumably it still requires firing individual requests)

**Comment by jassmith** [comment]
I believe that would be the case yes.

**Comment by jassmith** [comment]
Sorry a thought occurs to me that I forgot to mention. onPaste() already gives you the raw data its about to dump at you via the onCellEdited results. You can directly handle that. That said I am going to add onCellsEdited which will give you an aggregate callback to use instead and if you return `true` out of there it wont make the individual calls.

**Comment by nandorojo** [comment]
thoughts on changing `return true` to something more like `e.preventDefault()`? this would allow you to prevent an event, do some async info to validate it, and then conditionally continue it. allowing boolean promises could probably achieve this too

**Comment by nandorojo** [comment]
for real events you can’t. I should have phrased this better — it would be nice to have the option for the function to return `Promise<boolean> | boolean`. disregard the `preventDefault()` suggestion

**Comment by jassmith** [comment]
I don't currently see the value as you can trivially implement this on the consumer side if its valuable to your use case. All the lib does is loop over the thing its going to send to onCellsEdited and send them one at a time to onCellEdited.

**Comment by jassmith** [comment]
Fixed on 4.0.4
