### ISSUE TITLE
Allow configurable padding for the ideal width/height

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#321]
The computation of the `idealWidth` and `idealHeight` of the DataEditorContainer container is quite useful. 

https://github.com/glideapps/glide-data-grid/blob/3b28c362125aaf12641266063793bd9fcd9eaa10/packages/core/src/data-editor/data-editor.tsx#L2518

However, it would be awesome if there were an option to configure a custom padding instead of using the scrollbar width. The reason is that the scrollbar width computation does not work reliable across all browsers, operating systems, and scrollbar configurations. For example:

Firefox:
![image](https://user-images.githubusercontent.com/2852129/167213024-ae17fc1e-d5cc-4f05-9404-a2fe781ae967.png)

Chrome (here the scrollbar is configured to just overlay the content):
![image](https://user-images.githubusercontent.com/2852129/167213133-784aa754-5898-40ea-83dd-5e990212cd0f.png)

In my implementation, I would prefer to actually not have any padding added. I would be happy to implement that. I assume a good way would be to have an additional `containerPadding` property for the `DataEditor`, which is used instead of the `getScrollBarWidth` if it is provided.

**Comment by jassmith** [comment]
Yeah the scrollbar width computation is definitely a special one... I would love to make it actually work but I'm happy to add it to the theme as an option.

**Comment by LukasMasuch** [comment]
Yep, having this option in the theme would be awesome.

**Comment by jassmith** [comment]
In 4.0.4 there is an experimental `scrollbarWidthOverride` flag.
