### ISSUE TITLE
Allow custom cells to be searched

### ISSUE THREAD

**Issue by xsduan** [glideapps/glide-data-grid#328]
Currently I am heavily using the custom grid cell functionality. I'd like to be able to search for my cells, but it seems like the search functionality is limited to the built-in functionality. This greatly limits the usefulness of the search functionality.

It seems like there simply needs to be a new case in [this switch case](https://github.com/glideapps/glide-data-grid/blob/fabca8608293d9649cc7b45d503078a9192c6d7f/packages/core/src/data-grid-search/data-grid-search.tsx#L136). I think a simple optional `getSearchValue(): string` or something similar would be adequate for my use case at least.

Thanks!

**Comment by jassmith** [comment]
any reason it shouldn't just be the copy data?

**Comment by xsduan** [comment]
Personally I don't care too much but I can imagine in the future there might be a distinction between copy text being rich text and the search text being plain. 

For now I think appropriating the copy text should be fine.

**Comment by jassmith** [comment]
Great this will be resolved in 4.0.4
