### ISSUE TITLE
Pasting on custom cells not working

### ISSUE THREAD

**Issue by Dawesign** [glideapps/glide-data-grid#333]
I have set `copyData` on the cells correctly (copying values to the clipboard works as intended) but I can't seem to get the pasting working. `onPaste` is set to `true` on the Grid. Can't find more information or a way how to get it to work in the source code. Am I missing something?

**Comment by jassmith** [comment]
are you responding to the onCellEdited event?

**Comment by Dawesign** [comment]
Yes, I am. If I print the `newValue` the method received to console when pasting a value it appears to be the same as the cells original value.

**Comment by jassmith** [comment]
I cannot reproduce this issue. When I paste into a custom cell I receive back a custom cell whose `copyData` has the value which has been pasted. Are you trying to read out the copy data in the onCellEdited?

**Comment by jassmith** [comment]
Please re-open if you have a reproduction case. For the time being it seems to me that you are not checking the copyData value. This is admittedly non-intuitive.
