### ISSUE TITLE
Copy pasting custom cells

### ISSUE THREAD

**Issue by infinitepr0** [glideapps/glide-data-grid#341]
Currently, there seems to be no clean way of copying/pasting custom cells.
A simple approach to copying would be to run `JSON.stringify()` on the cells `copyData` value. Also provide an `onPaste` function for cells that allows us to specify how to update the cell data.

**Comment by infinitepr0** [comment]
Even better, provide `onCopy` and `onPaste` fields to cells.

**Comment by infinitepr0** [comment]
My idea is to provide generic hooks - so, instead of defining `copyData`, we could instead have `onCopy`, and similarly `onPaste`.

**Comment by jassmith** [comment]
Moving the scope of those events to the cell doesn't make sense in some cases. A paste event may write to cells which are offscreen and thus not even realized.

**Comment by jassmith** [comment]
You're right, this is overly complicated, I am sorting this out now.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/pull/345

This is my proposal for making this much MUUUCH easier. In general it means things just work. In the event you need to change the paste algorithm for any given cell type you can.

**Comment by jassmith** [comment]
Will be fixed in 4.0.4
