### ISSUE TITLE
Animation options within Grid

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#346]
Does Data-Grid support animations inside its cells, for example a spinner, whether it's through drawing on canvas, animated SVGs, or animated GIFs?

If so, do you have any examples of how this would be implemented, or any pointers to how this might be implemented? Thanks!

**Comment by jassmith** [comment]
So I've implemented a demo by creating a spinner cell. I am curious what exactly you are wanting to use animations for. They are easy enough if its just a looping thing, however if you have a more complicated use case I would like to hear it.

**Comment by jassmith** [comment]
One of the things I want to understand here is if 30FPS is more than enough or if targeting 60FPS is ideal. By my testing a 4k display with a full size data grid running an intel iGPU can do a lot of 60FPS animations, but it will eat battery life a bit compared to running them at 30FPS where its impact is much more marginal. If the animations are transient 30FPS is better. Maybe a better approach is to do 60FPS for 10 seconds and then drop to 30 FPS until 10 seconds of idle happens.

**Comment by jassmith** [comment]
Ok this is merged to 4.0.4. The current behavior is to allow 600 frames of unmitigated animations and the move to every other frame until an idle frame is found. The counter then resets.

**Comment by png262** [comment]
@jassmith Thanks for getting an example out so quickly, appreciate your fast response! Our main use case is pretty straightforward, we have kind of a "status" column where a given row might be performing something in the background (mostly via API calls behind the scenes) and when that happens, we want to present that to the user via a spinner cell to indicate something is happening. This typically will only last maybe several seconds, after which we will probably switch to some kind of "success" cell indicator.

For the spinner cell, it would be nice to have animation as that is what most users are typically used to seeing (loading screens, etc). I saw you implemented your example via a custom cell -- If I wanted to tweak that spinner animation, will I be able to create my own custom cell with my tweaked spinner? Thanks again!
