### ISSUE TITLE
How to load data from the server

### ISSUE THREAD

**Issue by faheemhameed** [glideapps/glide-data-grid#348]
Hi there,

Sorry, this is a naive question. 

I am working on a React project which is my first React project.
I am wondering how can I load data into the grid from the server asynchronously.
I can load the data from a static array of objects using the grid's getCellContent callback.
I have gone through the provided API docs and the Storybook examples for the glide-data-grid but still couldn't figure out how to get it to work.

I do understand that the "Data Grid is agnostic about the way I load/store/generate/mutate my data."
A simple example would be greatly helpful for beginners like me.

Many thanks for your help!

Hameed

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/blob/main/packages/source/src/use-async-data-source.ts

You should be able to either directly use that or copy and modify it.

**Comment by faheemhameed** [comment]
Thanks for this.

Actually, I am using the same file and playing around with it at the moment.

Once I got it working, I will share the code here.

**Comment by jassmith** [comment]
Sounds good!

**Comment by faheemhameed** [comment]
I was able to get the data into the grid using the code which looks something like it is shown below.

Unfortunately, the data shows in the first column only but the rest of the columns would only show after I have clicked into the grid using the mouse. Any idea why it's happening? 

```
const { getCellContent } = useAsyncDataSource(
100,
100,
getRowData,
toCell,
null,
dataEditor
);

const getRowData = useCallback(async (r, page) => {
  let data;
  try {
    data = await strapi.get();
  } catch (error) {}
  return data;
}, []);

const colNames = pageUtil.getColNamesForGrid();

const toCell = useCallback((rowData, col) => {
  const colName = colNames[col];
  const cellData = rowData[colName].toString();

  return {
    kind: GridCellKind.Text,
    allowOverlay: true,
    readonly: false,
    displayData: cellData,
    data: cellData,
  };
}, []);


return (
  <DataEditor
    getCellContent={getCellContent}
    ref={dataEditor}
    columns={columns}
    headerHeight={50}
    rowHeight={50}
    rows={100}
  />
);

```

Many thanks.

**Comment by jassmith** [comment]
This means you are not sending the damage event for the updated cells or
your getCellContent callback is giving back the wrong data.

**Comment by faheemhameed** [comment]
Just figured out that I missed passing onVisibleRegionChanged to the grid which was returned from useAsyncDataSource

Thanks for the heads up about damageList[]

```
  const { getCellContent, onVisibleRegionChanged } = useAsyncDataSource(
    100,
    100,
    getRowData,
    toCell,
    null,
    dataEditor
  );

 <DataEditor
    getCellContent={getCellContent}
    ref={dataEditor}
    columns={columns}
    headerHeight={50}
    rowHeight={50}
    rows={100}
    overscrollX={10}
    overscrollY={10}

    onCellEdited={onCellEdited}
    onVisibleRegionChanged={onVisibleRegionChanged}
  />
```

**Comment by jassmith** [comment]
Glad to hear you got it working
