### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by frapsMatheus** [glideapps/glide-data-grid#35]
Hi, I'm having an issue importing the library using Next.js.

NPM version: 6.14.11
Node version: v14.16.0
Next.js version: v9.4

# Error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/fraps/Coding/looselyhub/looselyhub/node_modules/direction/index.js
require() of ES modules is not supported.
require() of /home/fraps/Coding/looselyhub/looselyhub/node_modules/direction/index.js from /home/fraps/Coding/looselyhub/looselyhub/node_modules/@glideapps/glide-data-grid/dist/js/data-grid/data-grid-lib.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/fraps/Coding/looselyhub/looselyhub/node_modules/direction/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fraps/Coding/looselyhub/looselyhub/node_modules/@glideapps/glide-data-grid/dist/js/data-grid/data-grid-lib.js:19:41)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fraps/Coding/looselyhub/looselyhub/node_modules/@glideapps/glide-data-grid/dist/js/data-editor/data-editor.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

# How I'm importing:
```javascript
import DataEditor from '@glideapps/glide-data-grid' 
import { DataEditorContainer, GridColumn, GridCell } from '@glideapps/glide-data-grid'; 
```

**Comment by jassmith** [comment]
any chance you have a minimal repro case?

**Comment by stephensilber** [comment]
I'm also using Next.js and have run into the same issue in an empty project. I found a solution to fix the above error message here: [https://stackoverflow.com/a/65978156](https://stackoverflow.com/a/65978156). My `next.config.js` looks like this:

```
// next.config.js

const withTM = require('next-transpile-modules')(['@glideapps/glide-data-grid', 'direction', 'marked', 'react-responsive-carousel']);
module.exports = withTM({});

```

Beyond that, there are issues with window not being defined, so it seems like this framework may not be SSR friendly yet. I don't mean to hijack the thread, but I do suspect that all of these errors will fall under the same underlying problem. Once you get through the transpile/import issues, you're hit with `window is not defined`. I've attempted solve that below by dynamically importing the component (as suggested by Next.js [here](https://nextjs.org/docs/advanced-features/dynamic-import).



Here's a sample component I made:

```


import DataEditor from "@glideapps/glide-data-grid";
import {
  DataEditorContainer,
  GridColumn,
  GridCellKind,
} from "@glideapps/glide-data-grid";

export default function SampleDataGrid({ data }) {

  if (!window) {
    return null
  }

  const columns = [
    { title: "Number", width: 100 },
    { title: "Square", width: 100 },
  ];

  function getData([col, row]) {
    let n;
    if (col === 0) {
      n = row;
    } else if (col === 1) {
      n = row * row;
    } else {
      throw new Error("This should not happen");
    }
    return {
      kind: GridCellKind.Number,
      data: n,
      displayData: n.toString(),
      allowOverlay: false,
    };
  }

  return (
    <DataEditorContainer width={500} height={300}>
      <DataEditor getCellContent={getData} columns={columns} rows={1000} />
    </DataEditorContainer>
  );
}
```

and here's my `index.js` page in my empty Next.js project:

```
import Head from "next/head";
import dynamic from 'next/dynamic'

import "react-responsive-carousel/lib/styles/carousel.min.css";
const DynamicTable = dynamic(() => import('../components/SampleDataGrid'))

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DynamicTable />
      </main>
      <div id="portal" />
    </div>
  );
}
```

I believe this solves the window issue, but now I'm stuck on the following error:

`TypeError: (0 , _direction.default) is not a function`




I'm happy to move this to a separate issue, but as I mentioned above, I believe this all has to do with Next.js and SSR. One other note for the project is that it's not using TypeScript if that's useful.

**Comment by andrecrts** [comment]
i'm in the same position as you, i don't know if theres something we are missing

**Comment by stephensilber** [comment]
I was able to get it working in my Next.js repo by making sure the component was imported using `next/dynamic` and made sure to opt-out of webpack 5. 

Here's my dynamic import:
```
import dynamic from "next/dynamic";
const DynamicSheet = dynamic(() => import("./Glidesheet"), { ssr: false });
```


I did not need any custom loaders or transpile settings

**Comment by andrecrts** [comment]
thanks from y side i set the same version of the direction package and it works, now i have the issue that i cant click or edit any cell on the table but thats another problem. thanks! 👍

**Comment by phillipleblanc** [comment]
> I believe this solves the window issue, but now I'm stuck on the following error:
> 
> `TypeError: (0 , _direction.default) is not a function`
> 
> I'm happy to move this to a separate issue, but as I mentioned above, I believe this all has to do with Next.js and SSR. One other note for the project is that it's not using TypeScript if that's useful.

@stephensilber - I had the same issue you were seeing, but in a create-react-app. The peer dependencies that `glide-data-grid` uses were incorrect in my project, once I fixed the warnings in `yarn` I was able to see the data grid show up.

**Comment by itchii-06** [comment]
I have the same error:
`TypeError: (0 , _direction.default) is not a function`
I am using Next.js with Typescript.  So I add  `@types/direction@1.0.0`. I was able to see the data grid show up.

#### Versions I've added
- direction@1.0.4
- @types/direction@1.0.0

**Comment by dvdsgl** [comment]
The README has been updated with `direction@1`
