### ISSUE TITLE
onColumnResize example

### ISSUE THREAD

**Issue by faheemhameed** [glideapps/glide-data-grid#350]
Hi there,

Another naive question:

```
onColumnResize

onColumnResize?: (column: GridColumn, newSize: number) => void;
onColumnResize is called when the user is resizing a column. newSize is the new size of the column. Note that you have change the size of the column in the GridColumn and pass it back to the grid in the columns property.
```

According to the doc, I need to " pass the column back to the grid in the columns property."

I am quite not sure how to do it.

```
  const onColumnResize = (column, newSize) => {
    console.log(column)
    console.log(newSize)
    column.width = newSize;

    return column;
  };

```

I am just trying to return the column in the onColumnResize handler.

Any lights on this would be huge for me.

Thanks.

**Comment by jassmith** [comment]
Think of it like the `value` property for an `<input>` element. When you get an onChange event you must update the value you pass to the input on the next render or it wont actually show the update. Same rule applies to resizing columns. When a `onColumnResize` event happens, it gives you the new size for the column, you must re-render the grid, but now the `columns` property should have a list of columns one of which is the resized column at its new size.

**Comment by faheemhameed** [comment]
Thanks for your reply. I understand how to update a value for an input property.

```
class NameForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: ''};

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    this.setState({value: event.target.value});
  }

  handleSubmit(event) {
    alert('A name was submitted: ' + this.state.value);
    event.preventDefault();
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <label>
          Name:
          <input type="text" value={this.state.value} onChange={this.handleChange} />
        </label>
        <input type="submit" value="Submit" />
      </form>
    );
  }
}
```

But I really couldn't get how to re-render the grid with the changed column width. A simple example would be of huge help.

Also if you can share the source code of all your storybook thing, it could have saved a lot of time for you. Or if you have already shared the storybook source code somewhere, please let me know.

Many thanks!!

**Comment by faheemhameed** [comment]
I have figured it out after looking into the examples here:

https://github.com/glideapps/glide-data-grid/tree/main/packages/core/src/data-editor/stories

Basically, I have to use a state variable to hold the columns and send it to the DataEditor via it's columns property so that we can update it to make the Grid re-render. I kept forgetting about the state variables as I kept using normal javascript variables.

```
const onColumnResize = useCallback((column, newSize) => {
setColumns(prevCols => {
    const index = _.findIndex(prevCols, { id: column.id });
    const newCols = [...prevCols];
    newCols.splice(index, 1, {
        ...prevCols[index],
        width: newSize,
    });
    return newCols;
});
}, []);

<DataEditor
  getCellContent={getCellContent}
  ref={dataEditor}
  columns={columns}
  headerHeight={50}
  rowHeight={50}
  rows={20}
  onColumnResize={onColumnResize}
  overscrollX={10}
  overscrollY={10}
  onCellEdited={onCellEdited}
  onVisibleRegionChanged={onVisibleRegionChanged}
  getCellsForSelection={true}
  smoothScrollX={true}
  smoothScrollY={true}
  rowMarkers={"both"}
/>
```

**Comment by adamerose** [comment]
The online examples [[1](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--resizable-columns), [2](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--stretch-column-size)] let me double click the edge of a column header to auto-size their width to fit content, but when I try it myself using `onColumnResize` the same as faheemhameed above or the storybook files, double clicking does nothing. I don't see anything about auto-sizing on double click in the API docs, how can I enable that?

**Comment by homanp** [comment]
> The online examples [[1](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--resizable-columns), [2](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--stretch-column-size)] let me double click the edge of a column header to auto-size their width to fit content, but when I try it myself using `onColumnResize` the same as faheemhameed above or the storybook files, double clicking does nothing. I don't see anything about auto-sizing on double click in the API docs, how can I enable that?

Same issue here, any ideas how to solve?

**Comment by jassmith** [comment]
I believe this is working reliably now.
