### ISSUE TITLE
Image cell customisation (beautification)

### ISSUE THREAD

**Issue by faheemhameed** [glideapps/glide-data-grid#353]
Dear there,

How can I show the images for ex: with rounded corners and embossing?

I can see rounded corners in this story but wondering how to implement it.

https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-data-to-top

Thanks.

**Comment by jassmith** [comment]
Are you not getting rounded corners on your image cells? It's built in.

**Comment by faheemhameed** [comment]
You are right. The rounded corners are showing. I had white cell background and the image backgrounds were also white.

BTW, can we do further customization? like having borders etc? Any CSS effects?

Thanks.

**Comment by jassmith** [comment]
You could add them with drawing commands but CSS in general doesn't work against HTML canvas
