### ISSUE TITLE
Typescript error when importing custom cells

### ISSUE THREAD

**Issue by msdrigg** [glideapps/glide-data-grid#359]
When I try to import any of the custom cells like 
```ts
import type { DropdownCell } from "@glideapps/glide-data-grid-cells";

const d: DropdownCell = {
    kind: GridCellKind.Custom,
    allowOverlay: true,
    copyData: "4",
    data: {
        kind: "dropdown-cell",
        allowedValues: ["Good", "Better", "Best"],
        value: "Good",
    },
};
```
I get a typescript error at the line `const d: DropdownCell` saying 

> 'DropdownCell' refers to a value, but is being used as a type here. Did you mean 'typeof DropdownCell'?ts(2749)

I can attach my tsconfig if that would be helpful.

**Comment by jassmith** [comment]
the type you want is in
`import type { DropdownCell } from "@glideapps/glide-data-grid-cells/cells/dropdown-cell";`

**Comment by msdrigg** [comment]
I tried that as well (sorry, I should have specified).

When I try this import 

```ts
import type { DropdownCell } from "@glideapps/glide-data-grid-cells/cells/dropdown-cell";
```
I get this error

> Cannot find module '@glideapps/glide-data-grid-cells/cells/dropdown-cell' or its corresponding type declarations.ts(2307)

It's strange because there is a `cells` directory within `node_modules/@glideapps/glide-data-grid-cells/dist/ts/cells`, but it isn't being found for some reason.

I have googled the error, but nothing is moving forward.

My tsconfig is follows if you see anything obviously wrong

```json
{
    "compilerOptions": {
        "target": "es2020",
        "lib": ["es2020", "dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "noImplicitAny": false,
        "strictPropertyInitialization": false,
        "noStrictGenericChecks": true,
        "strictNullChecks": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "types": ["@cloudflare/workers-types"]
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules"]
}
```

**Comment by jassmith** [comment]
you're right, I will get this fixed ASAP. Sorry.

**Comment by msdrigg** [comment]
Thank you for the quick communication on this. I will look forward to an update

**Comment by jassmith** [comment]
I've pushed 4.1.1-alpha1 which should let you import `DropdownCellType` as well.

**Comment by hyusetiawan** [comment]
apologies for bringing up an old thread but I am having this same exact issue:
my versions are:
```
"@glideapps/glide-data-grid": "^5.2.1",
"@glideapps/glide-data-grid-cells": "^5.2.1",
```
it's higher than 4.11 but i still I experience the same error message.

**Comment by jassmith** [comment]
can I see your imports?

**Comment by hyusetiawan** [comment]
@jassmith 
```import type { DatePickerCell } from '@glideapps/glide-data-grid-cells```
this is per the readme: https://github.com/glideapps/glide-data-grid/tree/main/packages/cells#:~:text=Step%202%3A%20Use%20the%20cells%20in%20your%20getCellContent%20callback

the one that actually works is this following import:
`import { DatePickerCell } from '@glideapps/glide-data-grid-cells/dist/ts/cells/date-picker-cell'`

**Comment by jassmith** [comment]
both DatePickerCell (the actually renderer) and DatePickerCellType (the type of the cell the renderer uses) are available on the root export.
