### ISSUE TITLE
Resize last column

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#360]
It is extremely difficult to enlarge the last column.

https://user-images.githubusercontent.com/94077014/172454630-fa917e57-b562-4e91-9c95-20247d49ed80.mp4

Could you special case the drag between the last and second-to-last to also enlarge the last column when reducing the second-to-last?
Edit: Hmm, I guess this wouldn't let you then re-enlarge the second-to-last column after. :-/ Is the only good way to do this to add overscroll?

Alternatively it could expand when dragging past the bounds of the table, but if the table uses the full width of the page or is otherwise flush to the right, this wouldn't work.

**Comment by jassmith** [comment]
The padding option is there for this reason.
