### ISSUE TITLE
How do you add a group to another group?

### ISSUE THREAD

**Issue by ScarletJack** [glideapps/glide-data-grid#361]
Hi,

Is there a way to have a third+ group level to the columns?
I'd like to add a group header to columns that are already grouped.

**Comment by jassmith** [comment]
Not currently. Patches welcome :)

Possible API

```
interface GridColumn {
  // ...snip...
  group: string | [string] | [string, string]
}
```

Passing a string array sets the group hierarchy and to be honest with you the rendering part of this is a nightmare but hey the fundamental idea is straightforward.

**Comment by jassmith** [comment]
Closing now as I don't intend to work on this in the near term future.
