### ISSUE TITLE
Resize cursor shown when dragging non-resizable headers

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#363]
When the columns are resizable, a resize cursor is shown when hovering over the header borders.

This is not shown on hover when columns are not resizable, but the cursor is still shown if you still click and drag anyway. This should probably not change the cursor at all, or show some sort of forbidden cursor instead.

https://user-images.githubusercontent.com/94077014/172462366-c18c6b94-41b8-40e5-a64b-61d2b123de9f.mp4

**Comment by jassmith** [comment]
Oopsie poopsie, good catch

**Comment by jassmith** [comment]
Fixed in 4.1.1
