### ISSUE TITLE
Show multiline text in cell

### ISSUE THREAD

**Issue by awesomeunleashed** [glideapps/glide-data-grid#368]
Is there a way to show multiple lines of text in a cell? I can make my my rows grow as needed with `rowHeight`, but I don't see a straightforward way to render all of the text into the additional space.

I imagine I could do this with a custom cell renderer, but I'd rather not duplicate all of the existing behavior of text cells just to add extra lines if there's a way to avoid it.

**Comment by jassmith** [comment]
Creating a multi-line text cell is possible but it's far from cheap.  We will want to architect in a layout cache for string/font combos to avoid performing the same layout many times in a row with a LRU eviction policy to avoid bloat. If you want to work on this together I'm more than happy for the help.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/pull/373

- So I did this. Still has some problems. The cache does not ever get evicted so it's effectively a memory leak.
- The placement algorithm is not really great yet
- No control for line height externally
- The line segmentation algorithm which I extracted and improved from `canvas-txt` is actually extremely inefficient. We need to binary search the line length with some kind of bias. The fewer measurements the better.
- There isn't a storybook story to really play with this yet.

**Comment by jassmith** [comment]
This implementation also requires clipping per cell with potential vertical overflow. I don't think I can fix that and it does impact performance if you do a lot of these.

**Comment by awesomeunleashed** [comment]
Thanks for looking at this. If it helps with the segmentation issue, I'm not primarily trying to do text wrapping by width--I'm looking to split the text on newlines (ideally although not required, in a way that auto column sizing still works). So, for my use case, perhaps you could split the text on newlines and then just do what is currently done for only the first line for every line?

> This implementation also requires clipping per cell with potential vertical overflow. I don't think I can fix that and it does impact performance if you do a lot of these.

Since in my use case I know what the row height will be, clipping wouldn't necessarily be a requirement, although it's true that I imagine consumers of a multiline text cell would expect it to clip rather than overflow.

If you were *only* implementing split on newlines, though, rather than text wrapping, then I'm guessing you could just see how much vertical space you have left in the cell and stop rendering rows if there isn't enough?

**Comment by jassmith** [comment]
Okay I've fixed all the remaining outstanding issues in my PR. I just need to add some tests and it should be ready to merge. The original canvas-txt implementation I based on is shockingly inefficient. It would be nice if we could contribute back the performance increase to be good samaritans. 

The only problem is I think that lib has been unmaintained for 2 years now, maybe we can extract and make a fork that will better server the community.

**Comment by jassmith** [comment]
I've taken this some steps further by adding a concept I am calling `hyperWrapping`. If `experimental.hyperWrapping` is set to true, once the grid has rendered 50k wrapped characters and collected enough metrics, it generates a hyper-map which it can then use to perform pretty good wrapping without doing any text measurement. This reduces the performance overhead of wrapping to near zero with the tradeoff that it sometimes will wrap a word too early.

I think most users should consider enabling the flag if they are heavily using wrapping when this is released, it should also be enabled if you know your grid will never need native wrapping and only needs newline character support. In this case hyperwrapping will work perfectly and have zero overhead once warmed.

**Comment by jassmith** [comment]
Another extra swanky thing we could do for hyper speed wrapping

- Spin up a web worker with an offscreen canvas. 
- Generate lots of sample strings. 
- Measure sample strings and backprop changes into a character map. 

This approach would yield even more accurate results with very low spin up time and the generation of random strings could be offloaded to the user so they can optimize for their data set and language.

**Comment by awesomeunleashed** [comment]
Thanks for your work on this! If you put out an alpha release with these changes once you're done with them, I can test them for our usage, if you'd like.

**Comment by jassmith** [comment]
Fixed in 4.1.1, alpha with this going out today

**Comment by vivek-dhanade** [comment]
@jassmith Hi there, can this word wrap feature be extended to Column headers too? Its hard to adapt when headers are more than 2 words and column data is way smaller. drawHeader function to custom draw is an extra baggage in code
