### ISSUE TITLE
Checkbox for select/deselect all rowMarkers

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#369]
When we have `rowMarkers` enabled for checkboxes, I noticed that the top left corner is clickable which performs the "select all" / "deselect all" functionality for all rows. Is it possible to make this into a checkbox, so it is a little more intuitive for users to know that the functionality is there? Thanks!
![Screen Shot 2022-06-09 at 10 07 47 AM](https://user-images.githubusercontent.com/13039917/172867789-e064e7a7-0c6f-4ae7-95c7-1e89ec489a0d.png)

**Comment by png262** [comment]
This might be a personal UI preference, but I was thinking of something even simpler than needing to factor in hover state. My thinking is that we want to make it very apparent that there is a "Select all" functionality available, and it's this checkbox you are seeing. By making it only render on hover, that might might it less obvious for users, and only some might stumble onto that functionality.

I can totally see it making sense to have hover for the row markers though, because otherwise it would feel cluttered seeing a checkbox for every row. The difference is that this is a single checkbox in the top left corner so that doesn't apply. 

In any case, I think your proposal makes sense. If you wanted to simplify it without hover state, then it would be something like this:
| State | Effect |
| --- | --- |
| No rows checked | Empty checkbox |
| Some rows checked | Empty checkbox |
| All rows checked | Filled checkbox |

**Comment by amiregelz** [comment]
I think this is a great idea. 
I also think it will solve the issue where users are not aware of the ability to select rows - since the checkboxes only appear on hover. 

In my opinion having a master checkbox in the upper left corner would not clutter the UI and at the same time would make it clear that selecting rows is possible. Therefor I would make it always visible and not only on hover.

**Comment by jassmith** [comment]
Fixed in 5.0.0. I may open this behavior up for customization in the future.

**Comment by amiregelz** [comment]
@jassmith Is there a way to always show the checkboxes? I think this should be possible, most of my users are confused about rows selection since they only appear on hover.

**Comment by amiregelz** [comment]
@jassmith

**Comment by jassmith** [comment]
uh, if not I will add a mode.

**Comment by jassmith** [comment]
can you file a new bug?

**Comment by amiregelz** [comment]
@jassmith 
https://github.com/glideapps/glide-data-grid/issues/558
