### ISSUE TITLE
Dragging and releasing on headers/cells incorrectly triggers onHeaderClicked / onCellClicked

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#371]
If you click on one header or cell and then drag to another, it triggers the `onHeaderClicked` or `onCellClicked` of the header/cell you release on. Typically mousing down on an item and dragging away to another element should cancel the "click".

https://user-images.githubusercontent.com/94077014/172959514-0bd3dd1d-64c5-4238-b798-781cb31f6f98.mp4

**Comment by ivoelbert** [comment]
Wait, it's triggering `onCellClicked` for headers? Pretty sure that shouldn't happen.

**Comment by pzcfg** [comment]
It triggers whichever you release on, regardless of where the click starts

**Comment by BrianHung** [comment]
Huh, does `lastMouseDownCol === col && lastMouseDownRow === row` not work to prevent that?

**Comment by jassmith** [comment]
Fixed in 5.0.0
