### ISSUE TITLE
Dropdown cell not respecting custom styling

### ISSUE THREAD

**Issue by msdrigg** [glideapps/glide-data-grid#375]
Hey, I don't know if this is user error, but the editor on the `drop-down` cell isn't respecting the styling that I am supplying

See the Difference Here

1. Expected Styling (something like this) 
    - ![image](https://user-images.githubusercontent.com/45189381/173093316-c05f5f7e-b322-4b1d-9f7a-0a4cc550fd1b.png)
2. Actual styling 
    - ![image](https://user-images.githubusercontent.com/45189381/173092992-f9ddb452-73a4-48f8-9cb3-6f670f137168.png)

Is there some theming I can apply or does this need to be added to the component somehow?

**Comment by jassmith** [comment]
I suspect we just need to map the `theme` to the `React.Select` theme object. Surely there will be a perfect 1 to 1 mapping with nooooo compromise.

**Comment by msdrigg** [comment]
I can play around with this one to try to fix. I know im bring a lot of issues here and this seems like one I can try to find a fix for

**Comment by jassmith** [comment]
Awesome! Let me know if you have questions or get stuck.

**Comment by msdrigg** [comment]
Just letting you know that I have something due tuesday morning so I won't get to work on this until tuesday afternoon. I know its only like a 10 line fix, but its not an urgent fix either.

**Comment by jassmith** [comment]
Fixed in 4.1.1
