### ISSUE TITLE
fix nextJS example (args is not defined)

### ISSUE THREAD

**Issue by chris-aeviator** [glideapps/glide-data-grid#376]
The provided example will result in a failing build since `args` is not defined 
`args` rather needs to be defined when exporting the function

Expected:
```
export default function Grid(args) {
    return <DataEditor {...args} />;
}
```

Actual:
```
export default function Grid() {
    return <DataEditor {...args} />;
}
```

**Comment by jassmith** [comment]
The args there is intended to be a standin for "you need to pass some args to this DataGrid but I'm not going to fill them all out for this example because its not the important information."

I will see about maybe changing that.

**Comment by jassmith** [comment]
There is an example next project here if you want: https://github.com/glideapps/glide-data-grid/tree/main/test-projects/next-gdg
