### ISSUE TITLE
Provide getting-started example that actually compiles

### ISSUE THREAD

**Issue by chris-aeviator** [glideapps/glide-data-grid#377]
When using your storybook documentation  a user cannot run glide-data-grid by following the provided "getting started" example

the example doesnt wallk a user through setting up griddle as well leads to compiler errors.

```
const getContent = React.useCallback((cell: Item): GridCell => {

    const [col, row] = cell;

    const dataRow = data[row];

    // dumb but simple way to do this

    const indexes: (keyof DummyItem)[] = ["name", "company", "email", "phone"];

    const d = dataRow[indexes[col]]

    return {

        kind: GridCellKind.Text,

        allowOverlay: false,

        displayData: d,

        data: d,

    };

}, []);

```

is missing 

- imports
- types
- GridCellKind (???)
- data

A getting started example should give a user the chance to get started with the project with as low of a barrier as possible & without further understanding the logic behind decisions made. Therefore the getting started example should be updated to reflect a real getting started experience.

**Comment by jassmith** [comment]
Thank you for the feedback. I think we will link to the example projects more aggressively.
