### ISSUE TITLE
Support emotion/chakra-ui

### ISSUE THREAD

**Issue by kibs** [glideapps/glide-data-grid#378]
Stumbled upon this project today, and I am really impressed with the speed, UX, DX and everything.

My main concern is about depending on styled-components, as it would require us to include that only for this component.

Would it be possible to split the styled-components usage into some kind of adapter pattern, making it possible to create other adapters, like emotion / chakra-ui, or something else?

**Comment by jassmith** [comment]
The plan is to do this for 5.0 and eliminate the dep all together and just use CSS variables.

**Comment by jassmith** [comment]
This is resolved in the 5.0.0 branch which no longer has any runtime dep for styling.
