### ISSUE TITLE
autofit / autosize column width on double click

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#380]
![CleanShot 2022-06-13 at 17 00 32](https://user-images.githubusercontent.com/15721634/173466392-99725e3a-0951-4a0b-819a-0fb6b50b861f.gif)

should probably call `onColumnResize` or `onColumnResizeEnd` instead of being its own callback

**Comment by BrianHung** [comment]
@jassmith Is there a utility method for calculating the width of a column? I know there's `useColumnSizer` but that gets width for all columns and columns that are autosized only, and its a hook instead of a function.

**Comment by jassmith** [comment]
There is not currently a function, let me see how expensive that would be to factor out. I may not export it but you would at least be able to steal the code. It would let me implement the double click feature which I like. I am REALLY curious how well Google Sheets handles this when you have 10k rows with unique text.

**Comment by BrianHung** [comment]
Noticed you've implemented multi-line wrapping: https://github.com/glideapps/glide-data-grid/pull/373 That's also something Google Sheets takes into account when autofitting; looks like they take the longest width line in a multiline text cell.

**Comment by jassmith** [comment]
Implemented in 4.1.1
