### ISSUE TITLE
Borders around rows/cells

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#384]
Hi, is it possible to expand some functionality around borders, more specifically:

1. Borders around rows _on hover_ (see row 3 in screenshot)
2. Solid line borders on cells (see row 1 in screenshot). I know there is `highlightRegions` functionality but that currently only does dotted lines.

![](https://cdn.zappy.app/7edfb2685d434ca22c04a6b924043f9c.png)

**Comment by jassmith** [comment]
I will make highlight regions able to draw solid lines :)

**Comment by jassmith** [comment]
Added in 4.1.1
