### ISSUE TITLE
Rendering of line between row markers and content

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#385]
Hi,

I noticed that the vertical line separating the row markers and the normal content seems to be a little off when scrolling up and down:

For example, when scrolling down, the last row (or two) is missing that vertical line.
![](https://cdn.zappy.app/f876161139ac5d31feefc2b91a2b4c87.png)

And when scrolling up, the top row is missing that vertical line.
![](https://cdn.zappy.app/6fd9600a9fe55a24c891aecfe897dde5.png)

**Comment by jassmith** [comment]
I am having trouble reproducing this, can you provide a demo?

**Comment by jassmith** [comment]
Fixed in 4.1.1
