### ISSUE TITLE
Prevent onRowAppended from entering Cell Edit Mode (allow default value)

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#387]
I want to append a new row but not have it enter cell edit mode immediately (instead, I'm trying to set a default value for the cell).

When I'm clicking the "+ New Row" under the **1st column**, it automatically opens the Edit Cell overlay and deletes the value I set in `onRowApended` (it shows up for a brief second and disappears the moment the cell is entering edit mode).

If I append the new row using the "+ New Row" under the **2nd column**, then the default value (which is on the 1st column) - is saved and everything is fine.

```
    const getEmptyRow = () => _.reduce(columns, (result, column) => {
        return _.assign(result, { [column.id]: column.defaultValue ? column.defaultValue(data) : emptyCell(column) })
    }, {});

    const onRowAppended = React.useCallback(() => {
        setData([...data, getEmptyRow()]);
    }, [data]);
```

I suggest we add another prop, for example `enterEditOnRowAppended` (which defaults to `true`).
If I'm not mistaken, the relevant code to change is at `data-editor.js` > `const appendRow = React.useCallback...` and then change:

```
      if (cell.allowOverlay && isReadWriteCell(cell) && cell.readonly !== true) {
        window.setTimeout(() => {
          focusCallback.current(col, row);
        }, 0);
      }
```
to
```
      if (cell.allowOverlay && isReadWriteCell(cell) && cell.readonly !== true && cell.enterEditOnRowAppended) {
        window.setTimeout(() => {
          focusCallback.current(col, row);
        }, 0);
      }
```

**Comment by amiregelz** [comment]
Also - checked on Windows and it doesn't happen. It only happens on my Macbook (both running Google Chrome).

**Comment by jassmith** [comment]
Can you make a recording for me using replay.io? I am having trouble reproducing this.

**Comment by amiregelz** [comment]
It happens on all of your examples in Storybook as well - when I click the "+ New Row...", it add a new row and then opens the overlay edit popup instantly for the cell under.

For example here: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-data

**Comment by jassmith** [comment]
Thanks, that's enough, will figure it out.

**Comment by jassmith** [comment]
Fixed. The edit mode will no longer nuke what value you place in there. It still opens the editor but if you placed a value in there it will be displayed and highlighted.

**Comment by amiregelz** [comment]
@jassmith Awesome! thanks ❤️
