### ISSUE TITLE
Blurry trailingRowOptions.addIcon

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#388]
`SpriteManager` seems to have a fixed render size of 40

https://github.com/glideapps/glide-data-grid/blob/7b8ca94a98684ed5c1caac2f2b911150f5d70380/packages/core/src/data-grid/data-grid-sprites.ts#L13

but `drawNewRowCell` draws the sprite as `height - 8`

https://github.com/glideapps/glide-data-grid/blob/91b2843ba5b248b7485293b8bc9f6fe53fb3a1fd/packages/core/src/data-grid/data-grid-lib.ts#L406-L411

this means that if the row height is not 28, the icons are drawn blurry.

<img width="198" alt="lock" src="https://user-images.githubusercontent.com/94077014/174156998-907ac399-7077-4b06-a3bc-fa5904c28206.png">

<img width="57" alt="circle" src="https://user-images.githubusercontent.com/94077014/174157009-fc8476ea-fae0-46b3-8c87-4bf5c6aba028.png">

It would be great if icons could be drawn at specified sizes instead of a hardcoded 40. It would also be great if `drawNewRowCell` didn't enforce a 4px padding, would it be possible to let `addIcon` specify the exact placement and size, or at least draw the whole height so positioning can be controlled in the icon rendering?

Additionally, should `headerIcons` become just `icons`? Or maybe that can be in addition, and ideally allow sizing.

**Comment by jassmith** [comment]
This is more complicated to fix. The sprite map needs to be adjusted to:

A) Be dynamically loading/updating
B) Allow for ranges of sizes

Dynamic loading seems not too hard but mildly inefficient, ranges of sizes seems to be potentially massively inefficient unless we cap the size of each sprite. I'll need to spend some time working on this.

**Comment by jassmith** [comment]
Fixed in 5.0.0
