### ISSUE TITLE
`themeOverride` for non-sticky `trailingRowOptions`

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#389]
Is there a reason why this is only allowed when `isSticky`? I'd like to do some of these overrides to my non-sticky trailing row.

https://github.com/glideapps/glide-data-grid/blob/91b2843ba5b248b7485293b8bc9f6fe53fb3a1fd/packages/core/src/data-grid/data-grid-render.tsx#L1180-L1183

**Comment by jassmith** [comment]
Trailing rows originally were always sticky, this is vestigial and needs to be fixed, not on purpose.

**Comment by jassmith** [comment]
Fixed in 5.0.0
