### ISSUE TITLE
Formatted Cell

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#392]
One of my projects needs cells that requires both a float/"Number" cell, as well as integers, and may need a hexadecimal cell as well.

Instead of creating custom cells/editors for each of these, I was wondering if it would be possible to create a customizable `GridCellKind.Formatted` cell that accepts functions to:
- format/restrict the text in the editor
- format the display data
- format the underlying data

This could let you do the `NumberFormat` formatting similar to the `GridCellKind.Number` such as showing the thousands separator when editing but not `data` or `displayData`, or enforce things like only `/[0-9]/` for integers, or `/[0-9A-Fa-f]/` or add spacing for a credit card like `1234 5678 1234 5678` etc. and let you decide how this is represented in the editor, display, and actual data.

The editor callback may also need a system to read/set the cursor position to handle commas/spaces/etc. properly

**Comment by jassmith** [comment]
Implementation proposal for `TextCell`

```ts
readonly validate?: (input: string) => boolean | string;
```

When validate is unset or returns true it behaves as today. When it returns false the value in the text editor still updates but it underlines in red. This allows for example someone to type their way through intermediate values (like please enter an email address). It's still on you to validate the value in your data source, this is display only.

If you return a string the value will be coerced to whatever you return. e.g. `#faceCaFe` to `#FACECAFE`

**Comment by jassmith** [comment]
4.1.1 now contains a `validateCell` callback which enables both the ability to coerce a value and to indicate an invalid state.
