### ISSUE TITLE
Support Undo (Command/Ctrl Z)

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#395]
This is a big issue when pasting (and overriding) multiple cells.
Is there any way to support Undo?

**Comment by jassmith** [comment]
The data grid does not retain a copy of your data in any way, your data source itself would need to support an undo operation, you could do this by getting the newly pasted values in `onPaste` and then keeping a buffer of what is about to be overwritten and pushing that onto an undo stack. Then when you trap an undo, you can just roll it back.

**Comment by amiregelz** [comment]
Does it mean that I'll have to implement the `onPaste` logic myself?

**Comment by jassmith** [comment]
the `onPaste` logic literally is just a loop over the data calling `onCellEdited`. So I guess in that sense yeah you would need to implement that, but it would be far more efficient to directly send that data to your data source without proxying it through a `GridCell`. You can be far more efficient that way.
