### ISSUE TITLE
API to clear rows selection

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#397]
When deleting rows, the selection stays. 
Even though the rows were deleted, now there are two unrelated rows which are selected. 
It's confusing in terms of UX.
I want to clear the selection after detecting rows deletion.
Is there an API for that?

**Comment by ivoelbert** [comment]
You can use the controlled `gridSelection` property [(docs)](https://github.com/glideapps/glide-data-grid/blob/main/packages/core/API.md#gridselection) and modify it based on `onDelete` [(docs)](https://github.com/glideapps/glide-data-grid/blob/main/packages/core/API.md#ondelete)

**Comment by jassmith** [comment]
Ivo has the correct answer. This is not free.

**Comment by amiregelz** [comment]
@ivoelbert @jassmith Awesome, done! Thanks 🙏

**Comment by amiregelz** [comment]
@jassmith I implemented it this way:

```
const [gridSelection, setGridSelection] = React.useState(undefined);
...
const onGridSelection = (newVal) => {
        setGridSelection(newVal);
    };
    
const onDeleteRows = React.useCallback(({ current, rows }) => {
       ....
       setGridSelection(undefined);
    }, [data]);
...
<DataEditor gridSelection={gridSelection} onGridSelectionChange={onGridSelection} .../>
```

The rows selection are cleared correctly.
However it still **sometimes** selects (focuses) on a cell (index `[0, 0]`) afterwards which is a bit weird. So If I `console.log(gridSelection)`, I see the rows selection, then it's changed to `undefined`, and then it gets a new value (of the top most left cell). 

It's odd since it's not consistent - it happens once every few row deletions.

Is there a way to avoid it?

**Comment by jassmith** [comment]
If I had to guess this is caused by whether or not the selected cell is in the rows that were deleted. See what happens if you just set the `GridSelection.rows` to `CompactSelection.empty()` instead of setting the grid selection to undefined.

**Comment by jassmith** [comment]
The top left cell becoming selected implies the grid thinks it just received keyboard focus from not having focus.

**Comment by amiregelz** [comment]
@jassmith I tried `setGridSelection({ current: undefined, rows: CompactSelection.empty(), columns: CompactSelection.empty() });` but it acts the same.

I now see it reproduces only when I select a cell (doesn't matter which one), then select the entire row by checkbox, then delete it.
