### ISSUE TITLE
showSearch doesn't work with x to close search popup

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#399]
The x on the search popup only works with the search keyboard shortcut, but if I use the `showSearch` prop then clicking the x doesn't do anything which looks extremely buggy.

**Comment by jassmith** [comment]
Pressing the `x` button should result in `onSearchClose` being emitted from your DataEditor.

**Comment by amiregelz** [comment]
Got it! Thanks 🙏
