### ISSUE TITLE
Search control causes overflow

### ISSUE THREAD

**Issue by dvdsgl** [glideapps/glide-data-grid#4]
![image](https://user-images.githubusercontent.com/108197/103044927-1bb8f480-4548-11eb-8658-de1c182f3426.png)

**Comment by jassmith** [comment]
The wrapper needed the following css props

position: relative;
overflow: hidden;

**Comment by dvdsgl** [comment]
Does this need to be added to some documentation? Can we please include the wrapper in the package somehow?
