### ISSUE TITLE
Error: "AttValue: " or ' expected"

### ISSUE THREAD

**Issue by cdeutsch** [glideapps/glide-data-grid#40]
On your demo page, when I scroll to the bottom I get the following errors:

https://grid.glideapps.com/

```
Uncaught (in promise) Error: This page contains the following errors:error on line 3 at column 66: AttValue: " or ' expected
Below is a rendering of the page up to the first error.
```

```
TypeError: Cannot read property 'row' of undefined
```

I'm using Chrome on Mac  
Version 90.0.4430.85 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/404765/116154405-3cd45200-a6ae-11eb-906d-28b03bf6f412.png)

**Comment by jassmith** [comment]
Fixed
