### ISSUE TITLE
Option to have both rowMarkers numbers and selection checkbox together

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#400]
Currently I'm using the `both` option.
I think the current UI is super cool, but in terms of UX it's a bit confusing since my users don't understand there's an option to select the rows unless they accidentally hover over the row number.

I can switch to the `checkbox` option, but then the UX for `onRowMoved` is super weird - you would need to drag over the checkbox which is very unusual.

I like the UI of the row numbers and it would be awesome to add a fourth option, to have both the numbers and the checkboxes - on their left.

Another good solution would be to add some kind of indication when starting to move (drag) rows to reorder them, instead of leaving the checkboxes as they are.

What do you think?

**Comment by jassmith** [comment]
I think if checkboxes are enabled at all and onRowMoved is defined we should move to a UI like this MSPaint mockup:

![image](https://user-images.githubusercontent.com/30443/174495370-83e0fcea-ae57-4517-997b-3673a8085a87.png)

**Comment by jassmith** [comment]
the drag handle is very MSPain please forgive, margins also kinda suck, but you get the idea I hope.

**Comment by amiregelz** [comment]
@jassmith Looks perfect! I think it makes it very clear. I think it can also be useful to add with any `rowMarkers` mode, whenever `onRowMoved` is defined.

**Comment by jassmith** [comment]
I really don't want to have to display the drag marker next to the text as
it would force me into doing text measurements which has performance
considerations. I try very hard to keep this grid lightning fast at all
costs.

**Comment by amiregelz** [comment]
I think as long as it shows on hover and as long as it doesn't select the checkbox when you click it to start dragging, then it will be good enough.

**Comment by jassmith** [comment]
that is the tricky part :P

**Comment by jassmith** [comment]
![image](https://user-images.githubusercontent.com/30443/174537660-e9e95fa4-ed0d-4cfd-83e0-533cdfedf5f1.png)

The real thing. The screenshot didn't capture my mouse but it is over the one with the handle visible.

**Comment by jassmith** [comment]
Will be fixed in 4.1.1
