### ISSUE TITLE
Support Select All in Tags Custom Cell

### ISSUE THREAD

**Issue by amiregelz** [glideapps/glide-data-grid#404]
I'm using `tags-cell` to show tags and I need an option to Select All.
I implemented it using workarounds - tried both options but both have UX issues:
1. Have a default value of `[]`, and if value is `[]`, render `All` tag. The issue with that is that it's not clear to my users that if you deselect all tags in the edit overlay, then it will change back to `All`.

2. Have a default value of `['All']` and have `All` in `possibleTags` as well. The issue with that is that to select a specific tag you have to select the desired tag but then also deselect `All`, otherwise both will be selected.

Is there an easy way for you to add support for `Select All` in the tags cell edit popup? 
Or maybe give any callback API for when a user selects a tag in that popup, so that I can deselect `All` whenever any other tag is selected?

Thanks a lot ❤️

**Comment by jassmith** [comment]
I just added validateCell which should allow you to fix this.

**Comment by amiregelz** [comment]
@jassmith I'm trying to implement this using the new `validateCell` but ran into some issues.

I cannot distinguish between some states because I don't know which option was currently clicked - therefore I'm unable to tell when a user clicks the "All" when it's already selected, in order to deselect all.

Can you pass the currently selected value to `validateCell` callback? or is there any way to support the `All` natively?

This is my code:
```
    const validateCell = (cell, newValue) => {
        const { data } = newValue;
        let newData = data;
        if (data.kind === 'tags-cell') {
            const { tags, possibleTags } = data;
            const allValues = _.map(possibleTags, 'tag');
            const allWithoutAll = allValues.slice(1);

            if (_.isEqual(tags, [ALL])) {
                newData.tags = allValues;
            }
            else if (arraysHaveSameValues(tags, allWithoutAll)) {
                newData.tags = allValues;
            }
            else if (_.size(tags) > 1 && tags.includes(ALL)) {
                // All clicked
                if (tags.at(-1) === ALL) {
                    newData.tags = allValues;
                } else {
                    newData.tags = _.without(tags, ALL);
                }
            }
        }
        return _.merge({}, newValue, { data: newData });
    };
```

https://user-images.githubusercontent.com/1956341/176487251-b51718bb-241b-4890-b24f-6df3f0ef43a2.mov

**Comment by jassmith** [comment]
Thank you, I will see what the right approach here is.

**Comment by jassmith** [comment]
The preview value is now passed as the third argument.

**Comment by amiregelz** [comment]
Thank you 🙏 
Is it possible to create a minor release for this (https://github.com/glideapps/glide-data-grid/pull/416/commits/3045070b87018c1c8bc4e3fec691167f7a32c274)? e.g 4.2.1 ?

**Comment by jassmith** [comment]
4.2.1-beta1 is released. Please test it and let me know fi you find issues. If you find no issues I will promite it to stable. This is the only change.
