### ISSUE TITLE
scrollTo with enough space for the editor

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#407]
In #150 @ivoelbert added support to pass in padding to the `scrollTo` which is useful, however I need this to happen when `appendRow` is called as well. In my fork I'm just adding `overscrollY` to the `scrollY` here

https://github.com/glideapps/glide-data-grid/blob/91b2843ba5b248b7485293b8bc9f6fe53fb3a1fd/packages/core/src/data-editor/data-editor.tsx#L850

but it might be better to make this configurable or solve my issue at a higher level.

The main reason I need this one of our custom editors has suggestions listed below it, and if the added row is near the bottom they get cut off. If custom editors could provide some sort of `minHeight` and/or `preferredHeight` this could get added to the scroll.

Alternatively, making a way to configure adding `overscrollY` in `scrollTo`, or adding a new `scrollPaddingY` value would solve the problem.

**Comment by jassmith** [comment]
5.1.0 contains a vastly improved scrollTo API that can handle this need.
