### ISSUE TITLE
onGroupHeaderClicked not fired for touch devices

### ISSUE THREAD

**Issue by msdrigg** [glideapps/glide-data-grid#417]
This is most easily seen by going to [this storybook link ](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--column-group-collapse) on any iOS browser or turning on touch within the firefox developer mode.

I am able to click the headers to select a column, but I cannot click on the group headers.

**Comment by jassmith** [comment]
Fixed in 5.0.0
