### ISSUE TITLE
FillHandle very hard to use

### ISSUE THREAD

**Issue by capsloq** [glideapps/glide-data-grid#426]
You need surgical accuracy to fill down a column using the handle.
The cursor becomes a cross once the handle square is hovered anywhere, however actually dragging down the data only works if one hits the upper left corner of the square:

![image](https://user-images.githubusercontent.com/73945900/177048996-753e9842-cc71-4437-9b0d-13f31e570da3.png)

If you don't hit that specific spot the data will not fill downwards once the dragging is released.

This is the case in the [storybook demo](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--fill-handle) and a fresh install of the latest version. 

Tested on Chrome Version 103.0.5060.66 (64-Bit) and Firefox 102.0 (54-Bit)

However the datagrid example on the [official landing page](https://grid.glideapps.com/) does not have this bug / does not require the super high precision. So this might came with a certain version, depending on what version is displayed on the official landing page.

**Comment by jassmith** [comment]
Ah woops wonder when that broke! Will fix ASAP.

**Comment by jassmith** [comment]
Fixed in 5.0.0
