### ISSUE TITLE
empty columns that are sized by useColumnSizer don't show the full title

### ISSUE THREAD

**Issue by ralake** [glideapps/glide-data-grid#429]
Ive been playing around with removing the hardcoded widths for columns in a project I'm working on. If a column has no data, its width is often made narrow enough to chop off a portion of the title of the column, eg...

<img width="79" alt="Screenshot 2022-07-07 at 13 07 55" src="https://user-images.githubusercontent.com/8901119/177769879-47164a93-f5bd-4b37-9d1a-1e8e56d174df.png">

<img width="96" alt="Screenshot 2022-07-07 at 13 07 49" src="https://user-images.githubusercontent.com/8901119/177769882-0adb47c6-b469-410a-b869-c0e46878aed4.png">

I'd like to be able to always have the title of the column shown in full... is that possible? So the min width of the column is always the width of the title itself, then the resize logic can grow the column if there are tonnes of longer values...

**Comment by ralake** [comment]
4.2.1

**Comment by jassmith** [comment]
Fixed in 5.0.0
