### ISSUE TITLE
[Next.js] Using TypeScript enum outside of dynamic component causes styled.div is not a function

### ISSUE THREAD

**Issue by codeBelt** [glideapps/glide-data-grid#430]
We get the `TypeError: styled.div is not a function` when using the `GridCellKind` enum outside of the dynamic component in Next.js.

I understand why we need to dynamically import `DataEditor` in Next.js but is there a way to import the enum's independently from the React code?

The work around for us is to copy the enum(s) from the `data-grid-types.d.ts` and put them in our code directly to prevent the TypeError.

**Comment by codeBelt** [comment]
Testing with `4.99.0-alpha4` I get the `ReferenceError: window is not defined` error.

```ts
// My import
import { GridCell, GridCellKind, Item } from '@glideapps/glide-data-grid';
```
 If I remove the `GridCellKind` import and do the work around where I copy the enum(s) into my code it works as expected.

<img width="975" alt="Screen Shot 2022-07-07 at 12 38 24 PM" src="https://user-images.githubusercontent.com/2893563/177835807-b800b74e-300e-44f7-9a8e-c60a3f90bce6.png">

**Comment by jassmith** [comment]
If you want to go the extra mile, modify the next-js project test in this repo to reproduce this on the 5.0.0 branch so I never break this again :)

**Comment by codeBelt** [comment]
Ok, give me an hour or so.

**Comment by jassmith** [comment]
Alpha 5 is rolling now with a fix for that build error

**Comment by codeBelt** [comment]
@jassmith one thing I didn't test was doing a production build with Next.js. I just tested that the error wasn't in the browser anymore but now I noticed Next.js will not build a production version of the app because of the `ReferenceError: document is not defined` error.

Next.js Example
https://github.com/codeBelt/my-next.js-starter/pull/11/files

The issue is when I try to import the `GridCellKind` enum into another file that is not wrapped with `next/dynamic`. I'm also using util functions like `measureTextCached` outside of  `next/dynamic` causes the issue.

Since this is `v5` and a major change is there a way to separate the code that uses `window.document` into its own package namespace? I am not sure if that would fix the issue but an idea.

For example:
```tsx
import { DataEditor, DataEditorProps } from "@glideapps/glide-data-grid/editor";
import { GridCellKind, measureTextCached } from "@glideapps/glide-data-grid/support";
```

**Comment by jassmith** [comment]
We just need to be more careful about not calling window. anything on
import unless we know we are in a browser.

**Comment by codeBelt** [comment]
Should this issue be re-opened?

**Comment by jassmith** [comment]
It would be extremely helpful if you could create a PR which reproduces the issue in your test project.

**Comment by jassmith** [comment]
This is once again resolved in 5.0.0. Unfortunately the test doesn't work well becuase next build doesn't actually produce and error code when this error happens... which sucks.

**Comment by codeBelt** [comment]
Can you create beta release for these changes so I can test out it out

**Comment by jassmith** [comment]
5.0.0-beta1 is releasing now

**Comment by codeBelt** [comment]
Looks like everything is building correctly in Next.js. Thanks
