### ISSUE TITLE
Editing a number cell sometimes produces NaN

### ISSUE THREAD

**Issue by schani** [glideapps/glide-data-grid#44]
This seems to happen only when tabbing from the column to the left.  In the number column, type some letters and press enter:

![2021-06-01 16 23 49](https://user-images.githubusercontent.com/61363/120385776-d8806000-c2f5-11eb-9aca-46245a6912b4.gif)

![image](https://user-images.githubusercontent.com/61363/120385627-a8d15800-c2f5-11eb-81c2-9e00c40574b0.png)

**Comment by jassmith** [comment]
Fixed in 3.0
