### ISSUE TITLE
Increase size of hitboxes for row selection

### ISSUE THREAD

**Issue by raymeskhoury** [glideapps/glide-data-grid#440]
The hitboxes when clicking row markers only include the checkbox which can feel quite clunky as a user trying to select multiple rows (if you click fast and miss the hitbox, the row won't get selected). Ideally the clickable area would just include the entire row marker. In fact it would be nice to have a rowMarkers option that allows rows to be selectable without the checkboxes even being visible. 

I tried implementing something custom using the onCellClicked callback and modifying selection, but it means that I would need to reimplement the logic for adding and removing rows when shift/ctrl-clicking (and I don't have easy access to the keyboard modifiers to do that).

If it's not too hard, I could possibly help with a PR with some guidance.

<img width="56" alt="image" src="https://user-images.githubusercontent.com/8130584/179921258-21e99186-51b0-4ae2-8d02-9b733e74bdf0.png">

PS Thank you for this awesome library. I tried just about every library that is out there for displaying data grids and they didn't come close to this, not even the paid ones. You've done an amazing job.

**Comment by jassmith** [comment]
Fix here: https://github.com/glideapps/glide-data-grid/pull/441

**Comment by raymeskhoury** [comment]
Wow that was quick! Thanks you! I will test it out when it hits beta - those seem to get published pretty frequently?

**Comment by jassmith** [comment]
Beta is already published with this fix
