### ISSUE TITLE
onDelete - how it works?

### ISSUE THREAD

**Issue by dawidbak** [glideapps/glide-data-grid#442]
Hi, I am trying to do a row deletion and I see that there is something like onDelete, it works so that there is just 1 cell selected in the row and the user presses "Delete" and the row is deleted from the grid? If so can I somehow hook this up to the button?

**Comment by dawidbak** [comment]
How can I call onDelete prop to delete a single row from the grid? I set this up in DataEditor `onDelete(sel => sel)` but I don't understand how to use it.

**Comment by jassmith** [comment]
`onDelete(() => ({ current: undefined, rows: CompactSelection.fromIndex(12), columns: CompactSelection.empty() }))`
