### ISSUE TITLE
Scrolling by dragging selection up causes the entire column to be selected

### ISSUE THREAD

**Issue by raymeskhoury** [glideapps/glide-data-grid#444]
Repro:

1. Click to start a selection and then drag up, which causes the grid to scroll up and the selection to grow
2. Release the click outside the grid area (or on the header row)
3. Scroll up and notice that all of the cells above the cell you started at get selected, rather than just the on-screen ones

The screen recording below demonstrates. In particular it first show the issue, then it shows that the same issue doesn't occur when dragging/scrolling down to select cells, then it demonstrates the issue again.

[screen-capture (5).webm](https://user-images.githubusercontent.com/8130584/180169569-bcf1d50b-22af-4c9a-a9eb-7751e8b5e720.webm)

Repro sandbox: https://codesandbox.io/s/glidedatagrid-demo-forked-9g4brb?file=/components/DataGrid.tsx

**Comment by jassmith** [comment]
Fixed in 5.0.0
