### ISSUE TITLE
CompactSelection - items property

### ISSUE THREAD

**Issue by dawidbak** [glideapps/glide-data-grid#445]
Hi, is there a chance to make the property 'Items' in CompactSelection public? This could, for example, be used with rowMakers to select rows and pass an array of indexes to be removed from the grid.

**Comment by jassmith** [comment]
I am not understanding why this is preferable to the iterator provided.

**Comment by dawidbak** [comment]
If we have, for example, rowMarkers using checkbox. Then when you click on the checkbox, the whole row gets selected and GridSelection returns an array of indexes in the rows.items property and this can be used in your way. I've searched a bit of code and haven't found another way to pull this off.

**Comment by jassmith** [comment]
So if I give you a `gridSelection` you want to have

```ts
function getTheDataIWant(selection: GridSelection): T {
```

What is the value of T you want to see there assuming rows 3, 4, 5, 22, 24, and 25 are selected?

**Comment by dawidbak** [comment]
number[], [2,3,4,21,23,24] - I just only want selected row indexes

**Comment by dawidbak** [comment]
I'm talking about the situation as below when I click on the checkbox. If I clicked on a regular cell then I could retrieve the row index from the current property but in this case it is undefined
![image](https://user-images.githubusercontent.com/75274385/180250143-70e46fe7-9818-4710-84d1-7e0d24963286.png)

**Comment by dawidbak** [comment]
I have this message: `Type 'CompactSelection' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.`

**Comment by jassmith** [comment]
does
```ts
const arr: number[] = [];
for (const i of selection.rows) {
  arr.push(i);
}
```

work in your env? Modern js accepts the syntax I put above but your bundlers flags are preventing it from working.

**Comment by dawidbak** [comment]
Same message, but are you sure i can iterate over it? It's single object `GridSelection.rows: CompactSelection`

**Comment by jassmith** [comment]
yeah it has an iterator defined on it, but it seems you wont have access to it with your current target flags. I will add a toArray method.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/pull/416/commits/c417afedbe31a9f8a72f2433101919f212fd0484

**Comment by dawidbak** [comment]
Okey, as I understand correctly, I will get the row index with each iteration?

**Comment by jassmith** [comment]
yessir, though in the api i've added in 5.0 it will also let you dump out an array which contains the indexes of all the rows which are in the selection

**Comment by dawidbak** [comment]
> yessir, though in the api i've added in 5.0 it will also let you dump out an array which contains the indexes of all the rows which are in the selection

Thank you for your help, really appreciate it

**Comment by jassmith** [comment]
I appreciate you using our project! Cheers. Come back if you need more help1
