### ISSUE TITLE
[Feature] Disable onCellClicked on cells

### ISSUE THREAD

**Issue by codeBelt** [glideapps/glide-data-grid#449]
Would it be a good idea to add a property on `BaseGridCell` that disable the `onCellClicked` property on `DataEditor` from triggering. When using the `GridCellKind.Loading` cell or a custom cell it would be nice to disable the callback.

On a side note can `allowOverlay` be optional? I don't see any documentation for `allowOverlay` and I don't know why I need to set it.

Thanks! Your Library Rocks!

**Comment by jassmith** [comment]
I've added better documnetation for allowOverlay in preparation for the 5.0 release. I don't think I am going to add a control for disabling `onCellClicked` at this time. I get the desire but it seems very easy to do without.
