### ISSUE TITLE
Choose either onCellEdited or onCellsEdited

### ISSUE THREAD

**Issue by pho7on** [glideapps/glide-data-grid#450]
From what I could understand, in the current implementation (even with a 5.0 fix for `onCellsEdited`), we would still have to maintain 2 functions. My question is, would it be possible to use only `onCellsEdited` for all updates to the table, to avoid breaking the DRY principle

**Comment by pho7on** [comment]
thanks @jassmith

**Comment by jassmith** [comment]
This was a great and obvious suggestion, thank you so much for the push to make sure this got done before 5.0. I would have regretted it. Merged into 5.0 now. onCellsEdited will always be called before onCellEdited, even for single cell edits.
