### ISSUE TITLE
Outside click event listener for cell editor

### ISSUE THREAD

**Issue by gentrithumolli** [glideapps/glide-data-grid#451]
In my current project, we have a custom cell editor that we use for the glide grid, and inside it, we have a popover menu (rendered outside cell editor) that withholds some cell actions (see image below).

<img width="1364" alt="Screen Shot 2022-07-29 at 17 04 07" src="https://user-images.githubusercontent.com/19568340/181788635-18fa7241-5f66-4df3-85df-daa856ea95ec.png">

The issue is that when the menu item is clicked, the cell editor closes and the onClick of that element doesn’t fire at all. It looks like there’s an active event listener that watches for clicks outside the editor and closes it, but I think it would be nice to have this controlled or disabled.

The same issue is also with modals — if there’s a modal that’s opened over the grid and we have an active cell opened, when the user clicks on the modal backdrop, the active cell closes.

**Comment by gentrithumolli** [comment]
I was looking through your codebase on how the outside click was implemented and found out that I can add a `click-outside-ignore` to ignore the click of the element that's rendered outside the cell editor, and it resolved my issue.
You should definitely add this to your documentation, as it might be very useful to someone with similar issues.

**Comment by jassmith** [comment]
good point, Im just not madly in love with it :P

**Comment by gentrithumolli** [comment]
Hahah, nice loophole though :)

**Comment by pho7on** [comment]
@gentrithumolli can you provide an example for your solution?

**Comment by jassmith** [comment]
just add the class "click-outside-ignore" to any container you want to not trigger clickoff

**Comment by pho7on** [comment]
@jassmith thanks

**Comment by twelve17** [comment]
@jassmith by chance, has there been another way to work around this? I've been trying to add the "click-outside-ignore" but it doesn't seem to work for me.
