### ISSUE TITLE
Backspace not working

### ISSUE THREAD

**Issue by pho7on** [glideapps/glide-data-grid#452]
When trying to delete cell content with `backspace`, nothing happens, no event is being fired. Is there some custom prop I have to pass to enable it?

The current implementation I am using as a workaround is:

```ts
const deleteWithBackspace = (e: KeyboardEvent) => {
    if (e.code === "Backspace") {
      dataTableRef.current?.emit("delete");
    }
};
```

p.s This was tested on Linux and Windows machine, if that is relevant

**Comment by jassmith** [comment]
Backspace is used in OSX and Delete is used in all othere OS's right now.
