### ISSUE TITLE
Deleting multiple cells - firing onCellEdited but not onCellsEdited

### ISSUE THREAD

**Issue by city17** [glideapps/glide-data-grid#454]
When deleting several cells, there is an event fired for every `onCellEdited` (with an empty string as new value for that cell). That way I can handle the update of data in one function, instead of also needing to use onDelete.

But when deleting multiple cells, `onCellsEdited` doesn't fire at all. 

If I understand it correctly in 5.0.0 it will be possible to use just `onCellsEdited` instead of `onCellEdited`, which is a bit cleaner to prevent duplicate code. It would be nice if it could handle the delete event as well.

Or would you recommend using the `onDelete` call? In my case I would set the values in the backend to empty strings, not delete them entirely, so being able to reuse `onCellsEdited` code would be nice.

**Comment by jassmith** [comment]
onCellsEdited in 5.0 fires for delete. It *may* fire multiple times depending on your selection for different subsections.

**Comment by city17** [comment]
> onCellsEdited in 5.0 fires for delete. It _may_ fire multiple times depending on your selection for different subsections.

Thanks @jassmith. Do you know when approximately you'll release v5.0? (Just trying to get a rough idea when to plan some time to implement some changes)

**Comment by jassmith** [comment]
this week
