### ISSUE TITLE
Changelog uses rightElementSticky when it should use rightElementProps

### ISSUE THREAD

**Issue by wodin** [glideapps/glide-data-grid#457]
Should this not be as follows?

```tsx
<DataEditor
    rightElement={el}
    rightElementProps={{
        sticky: true,
    }}
/>
```

https://github.com/glideapps/glide-data-grid/blob/bd3a01a49ccb66716e9eeb84e2dfefda8364473d/packages/core/CHANGELOG.md?plain=1#L107-L112

**Comment by jassmith** [comment]
thanks, fixing!
