### ISSUE TITLE
Preventing delete on custom cells with editors and allowOverlay

### ISSUE THREAD

**Issue by ralake** [glideapps/glide-data-grid#458]
Currently, if you have a custom cell with an editor but with `allowOverlay: false` it will still be able to have its value deleted. this is because there is no check for allowOverlay to be true at this line...

https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L2057

should this be

```JS
if (isObjectEditorCallbackResult(editor) && cellValue.allowOverlay) {
```
??

Might be missing some context, but happy to PR if this is indeed a bug.

**Comment by jassmith** [comment]
Fixed in main
