### ISSUE TITLE
Multiples of the same image only display after hover

### ISSUE THREAD

**Issue by awesomeunleashed** [glideapps/glide-data-grid#46]
[CodeSandbox Repro](https://codesandbox.io/s/spring-waterfall-utkub)

When multiple references to the same image are in different cells in the grid, only the first one is displayed on initial load until any grid cell is hovered over.

I'd be happy to contribute to a fix for this if you can point me in the right direction, but I don't know Canvas well enough to know what might be the cause at the moment.

**Comment by jassmith** [comment]
Thanks for the report, will fix!
