### ISSUE TITLE
Numbers ending up as `NaN` in certain circumstances when editing cell

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#460]
If you double-click a cell to open the number editor, type non-numeric characters and hit enter, the cell gets set to 0, but if you single-click (without opening the editor) and start typing non-numeric characters and hit enter, this gets populated with a `NaN` value.

https://user-images.githubusercontent.com/94077014/183222545-c7f6d936-3ccd-42ea-ba70-c498454afa4e.mp4

**Comment by jassmith** [comment]
fun...

**Comment by jassmith** [comment]
Why you gotta report this the day after 5.0.0 goes stable, what did I ever do to you :P

**Comment by pzcfg** [comment]
sorry 🙈 we just happened to update today 😅

**Comment by jassmith** [comment]
Fixed in main
