### ISSUE TITLE
Custom 'tags-cell' editor not rendering properly

### ISSUE THREAD

**Issue by city17** [glideapps/glide-data-grid#463]
Since the 5.0.0 update, it seems the custom 'tags-cell' no longer renders properly when editing. 

The styling of both the pills and inputs are no longer there. They do have classnames (`pill` and `gdg-input`), but these apply no CSS properties, so maybe those got lost somehow in the update?

<img width="147" alt="Schermafbeelding 2022-08-09 om 09 16 05" src="https://user-images.githubusercontent.com/13391662/183588212-6d807f5a-a397-436c-9cba-fc382c02e30d.png">

**Comment by jassmith** [comment]
looking into it

**Comment by jassmith** [comment]
I just double checked, I did it right in the first place. Whew ya scared me! Yeah you just need to import "@glideapps/glide-data-grid-cells/dist/index.css"

**Comment by city17** [comment]
Thanks Jason! I imported the CSS for the overall data grid, but somehow missed that this also needed to be done for the cells package. Working perfectly again now.
