### ISSUE TITLE
scrollTo move to exact location (cell)

### ISSUE THREAD

**Issue by babakansari** [glideapps/glide-data-grid#468]
Feature Request

`scrollTo` method does not have a way to move to an exact (Top, Left) location (cell). Could `scrollTo` move to the cell at the top left corner of the gird?

Thanks!

**Comment by ivoelbert** [comment]
We should add options similar to `Element.scrollIntoView` (but with friendlier names 😄 ) https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by babakansari** [comment]
@ivoelbert -I guess `scrollTo` could have a mode to behave like [JS ](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo) with the exception of using Row or Column for the coordinates.

cc @jassmith

**Comment by jassmith** [comment]
this has been fully implemented in 5.1.0
