### ISSUE TITLE
onPaste does not fill all selected rows

### ISSUE THREAD

**Issue by DusanNikcevic** [glideapps/glide-data-grid#470]
Currently, I am working on a table with a company that expects almost identical Excel behavior. One missing thing is copying and pasting one row into multiple selected rows. Is this a feature that you intend to add or is this something you might delegate to devs using your library to implement themselves due to some technical complexity/edge cases?

Also if I am not mistaken, `onPaste` is currently working with `onCellEdited`, is this something that can be moved to `onCellsEdited`? That would greatly improve DX

**Comment by pzcfg** [comment]
In my quick test `onCellsEdited` gets called for both `onPaste` and `fillHandle`

**Comment by pho7on** [comment]
> In my quick test `onCellsEdited` gets called for both `onPaste` and `fillHandle`

that is good to know. thanks @pzcfg !

**Comment by jassmith** [comment]
So sounds like this is not an issue?

**Comment by jassmith** [comment]
Implementation proposal:

```ts
interface DataEditorProps {
  ...otherCrap,
  onPasteBehavior: undfined | {
    demuxRows: boolean,
  }
}
```

**Comment by jassmith** [comment]
I dont understand why you think that would be better.

**Comment by pho7on** [comment]
Now we have to maintain both `onCellsEdited` and `onCellEdited`. Sure, we can prevent `onPaste` from triggering `onCellEdited` but IMO `onCellEdited` is kinda redundant anyway, since we have to maintain basically two functions to handle data change. I believe that it would be best if we could decide if we want to use one or the other, for example I would rather handle everything in `onCellsEdited`

**Comment by jassmith** [comment]
`onCellsEdited` was updated in 5.0.1 to always trigger, you can not implement `onCellEdited` at all if you like. `onCellEdited` will always trigger if `onCellsEdited` triggered.

**Comment by pho7on** [comment]
Ah well, in that case, everything is solved basically. Great stuff!

**Comment by jassmith** [comment]
This is as good as its going to get for a bit in 6.0.0. It now handles ranges much better. We might do more improvements in the future with pattern filling and handlng demuxing.
