### ISSUE TITLE
Don't trim `onPaste` input

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#472]
Currently if you paste in text like
```




hello
```
(with leading newlines) the current cell gets its value set to "hello", instead of the first four cells being set to an empty value, and then "hello"

If I copy and paste a similar selection from the grid, this works as expected (I think because it uses the HMTL format instead of text? I still need to look into the code). But if I instead convert this to plain text by pasting and copying it into a plain text editor, the same trimming occurs.

https://user-images.githubusercontent.com/94077014/185250222-eab63df9-98b9-492d-bea8-e67df0a7c697.mp4

**Comment by jassmith** [comment]
Good catch will fix

**Comment by jassmith** [comment]
Fixed in 5.0.1
