### ISSUE TITLE
Date picker editor does not autofocus

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#473]
How to reproduce:

start from example in storybook:
https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cells

try to edit date using only keyboard, not mouse. I can't do that in Chromium and Firefox because after editor is created it does not autofocus

**Comment by jassmith** [comment]
Yup

**Comment by jassmith** [comment]
Fixed in 5.0.1
