### ISSUE TITLE
[Feature Request/Question] Is there a way to get a Button in a cell

### ISSUE THREAD

**Issue by jerebtw** [glideapps/glide-data-grid#475]
I want to add an edit button in a cell at the end so I can redirect the user to a special edit page

**Comment by arogozhnikov** [comment]
Grid itself uses canvas, so you need to render button on a canvas. 

For the click detection, you can use `onCellClicked` callback.

**Comment by jassmith** [comment]
Yes and no. We are adding a newer, better, bigger, badder, more awesome API for creating custom cells where you will be able to do this with ease. Until then, you have to do what @arogozhnikov suggested.

**Comment by jerebtw** [comment]
> Yes and no. We are adding a newer, better, bigger, badder, more awesome API for creating custom cells where you will be able to do this with ease. Until then, you have to do what @arogozhnikov suggested.

Do you know when this API will arrive?
(Btw love this library ♥️)

**Comment by jassmith** [comment]
You can track progress here: https://github.com/glideapps/glide-data-grid/pull/481
