### ISSUE TITLE
move `getBounds` into `DataEditor`

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#478]
Would it better to move `getBounds` into `DataEditor`? 

All of its [dependencies](https://github.com/glideapps/glide-data-grid/blob/4a1867f1381f3816093664a88cd8d861efba43ec/packages/core/src/data-grid/data-grid.tsx#L322-L334) are essentially props passed from `DataEditor`.

And as of the current implementation, `getBounds` requires an additional render (?) to work after a `scrollTo` call since its dependency list has to update instead of depending on "ref" values.

```ts
const prevBounds = gridRef.getBounds(col + rowMarkerOffset, row);
gridRef.scrollTo(col, row); 

const currBounds = gridRef.getBounds(col + rowMarkerOffset, row);
console.log("does bounds update immediately", prevBounds.x != currBounds.x) // false

requestAnimationFrame(() => {
  const nextBounds = gridRef.getBounds(col + rowMarkerOffset, row);
  console.log("does bounds update eventually", prevBounds.x != nextBounds.x) // true
})
```

**Comment by jassmith** [comment]
We would take a PR that does a good job of doing this and does not break anything (or have a horrible hackery to it) but at this time this is not a priority for this project.
