### ISSUE TITLE
Search scrolls to the wrong place

### ISSUE THREAD

**Issue by raymeskhoury** [glideapps/glide-data-grid#484]
Repro:
1) go to https://grid.glideapps.com/
2) Click "lots of rows" toggle
3) Ctrl+f on grid
4) Enter a search (I tried "fantas")
5) Hit enter a few times and notice that the selected cell isn't scrolled into view

This doesn't happen as much when there aren't as many rows in the grid, but I'm not sure if the root cause is related to that or it's just triggered more often in that case.

Any ideas on where to start with debugging?

**Comment by raymeskhoury** [comment]
Sorry I spoke too soon - it doesn't repro on  https://grid.glideapps.com/ but I can repro locally. Let me try to come up with another repro case.

**Comment by raymeskhoury** [comment]
Small repro case with 100 rows: https://codesandbox.io/s/trusting-waterfall-hl53tz?file=/src/App.js

Enter the search "12" and keep hitting enter. Notice that some results do not show up on the screen:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/8130584/187067118-b48d0b93-1aa9-4902-a0c5-3b1dab2f5d1a.png">

It is more apparent if you increase the number of rows.

Also, notice that if you comment out the following 2 lines, things work well:
`gridSelection={selection}
onGridSelectionChange={setSelection}`

So I suspect it's related to setting selection. I suspect that when selection gets set in the grid, it's triggering another scroll to event (for some reason) which is causing things to go to the wrong place. It's possible it's a race.

**Comment by jassmith** [comment]
What browser are you using? Even in your code sandbox when I type 12 and hit enter I get taken to the result.

**Comment by raymeskhoury** [comment]
Chrome. Note that it doesn't happen on the first result, you have to cycle through a few results. In particular, result 8 and 9 in the example

**Comment by raymeskhoury** [comment]
I made the example clearer by setting rows to 10000. Now try searching for "1234". It scrolls to the wrong place for almost every result.

https://codesandbox.io/s/trusting-waterfall-hl53tz?file=/src/App.js

**Comment by jassmith** [comment]
Okay thank you for the reproduction case. I see the error now, it has to do with using a controlled gridSelection vs an uncontrolled one. I don't know why yet.

**Comment by jassmith** [comment]
Fixed in 5.0.1

**Comment by raymeskhoury** [comment]
Thank you for the quick fix!!
