### ISSUE TITLE
Scrolling to the bottom of the list in the linked demo breaks the site.

### ISSUE THREAD

**Issue by louisnow** [glideapps/glide-data-grid#49]
https://grid.glideapps.com/
Simply scroll to the bottom of the grid. The screen goes blank as react doesn't know what to render anymore.

![2021-06-22-234638_412x348_scrot](https://user-images.githubusercontent.com/6024271/122978509-37486f00-d3b4-11eb-9619-23b77b20e929.png)

**Comment by dvdsgl** [comment]
Thank you! Fixed by updating the core package deployed on the site.
