### ISSUE TITLE
Double enter resets dropdown to the first value

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#493]
How to reproduce: start from [this](https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cell-editing) page,

then select any cell and change its value from 'A' to 'C'. 
Then press enter to start editing the cell, and dropdown will appear:
<img width="277" alt="Screen Shot 2022-09-08 at 10 09 07 PM" src="https://user-images.githubusercontent.com/6318811/189264134-4c180d96-811f-4c02-a612-963f61712560.png">

Strangely, while dropdown is aware that correct value is C, and C is in the cell, the 'selected' value is the first one in the list, i.e. 'A'.
When user presses 'enter', it is quite intuitive to expect that cell's value will not change (as with sting input, enter starts editing and enter exits editing, so double enter does not change value). However in case of dropdown value 'A' will be set.

**Comment by jassmith** [comment]
Fixed in 5.1.0
