### ISSUE TITLE
Wrong overlay editor font color in Safari when read-only

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#494]
Safari seems to grey out the font color in the overlay editor when the cell is read-only:

Chrome:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/2852129/189349287-2f7905b9-c851-44df-9db9-cb6c059460e7.png">

Safari:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/2852129/189349309-57e7a8cc-03fc-4381-aa3b-ebd0a613f50a.png">

Also, not sure if this is a bug... the images do not seem to load for me in chrome in the current storybook.

**Comment by jassmith** [comment]
Huh... the images is more concerning to be frank, anything strange in the console?

**Comment by LukasMasuch** [comment]
Images seem to be blocked by my Adblock chrome extension (Adblock Plus). Everything is fine in incognito mode. But I don't think this was happening the last time I checked the Storybook website:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/2852129/189379952-305ba590-45fe-4764-ac24-0c5f56d9df31.png">

**Comment by jassmith** [comment]
Fixed in 6.0.0
