### ISSUE TITLE
Feature request: Make glide-data-grid handle css transform:scale(x)

### ISSUE THREAD

**Issue by fakob** [glideapps/glide-data-grid#495]
Thanks for doing such an amazing job @jassmith. It is rare to come across such a feature rich and well documented open source project.

Now to my question/feature request.
The scaling of your data-grid using `transform:scale(x)` works well. However, when trying to select/edit the table, it seems that there is an offset between where the mouse clicked and which cell/row/column was selected.

<img width="710" alt="Screenshot 2022-09-09 at 18 42 38" src="https://user-images.githubusercontent.com/4619772/189401610-9a5f79be-0866-4c1a-ae11-23e4a687df0f.png">

I understand that my use case is a rare one, but I thought I still ask/make this feature request.

We are developing an open source node based prototyping toolkit where we need a table node which is nicely editable while scaled. You can see an example of our current implementation below. Unfortunately is the data-grid component not as well done as yours. We would love to switch over to using glide-data-grid, but we want to support the ability to edit the data-grid while scaled up or down. Or is there another way of doing the scaling which would support or use case?

https://plugandplayground.dev/?loadURL=https://raw.githubusercontent.com/fakob/plug-and-play-examples/dev/Drawing%20examples.ppgraph

<img width="1260" alt="Screenshot 2022-09-09 at 18 49 02" src="https://user-images.githubusercontent.com/4619772/189401168-5dddfa61-6354-44e5-a149-cd2019e9b06c.png">

**Comment by jassmith** [comment]
I think this should be easy enough to do.

**Comment by jassmith** [comment]
Done and dusted in 5.1.0

**Comment by fakob** [comment]
Wow, amazing. Thank you @jassmith, I really appreciate this! I will keep a look out for the 5.1.0 release.

**Comment by jassmith** [comment]
You can play with it right now. There is a 5.1.0-beta1 with the fix.

**Comment by fakob** [comment]
Thanks for the fix. I have tested the scaling in a basic setup and it works well!

Unfortunately, I have trouble getting the whole glide-data-grid to work in our application. For this I have opened a ticket. I am not sure what I am doing wrong. If you have an idea, any help would be appreciated. https://github.com/glideapps/glide-data-grid/issues/496
