### ISSUE TITLE
[Feature Request]: Angular Support

### ISSUE THREAD

**Issue by rrekapalli** [glideapps/glide-data-grid#497]
Hi Team:

This grid looks very promising as we have tons of data to be displayed for one of our analytics solution.  However, all our UI code base in Angular.  Is there plan to support Angular as well? 

Thanks!

**Comment by jassmith** [comment]
Not at the moment. We have been thinking about doing a web-component version which you could embed in angular as you see fit.

**Comment by rrekapalli** [comment]
Hi @jassmith, is there any timeline on when we can expect the web component version? 

Thanks in advance!

**Comment by jassmith** [comment]
Nope. Though running it inside react inside angular will probably still be lighter than most other comparable grids out there in terms of package size.
