### ISSUE TITLE
[Feature Request]:  Column Grouping & Column Pivots

### ISSUE THREAD

**Issue by rrekapalli** [glideapps/glide-data-grid#498]
Hi Team:

Are there any plans to implement:
- Column Grouping (similar to GROUP BY in SQL, not like the current grouping feature when a set of columns are given a group name)
- Column Pivot (similar to Excel Pivot tables)
- Column level data filtering
- Column Selection (visibility control to display selected columns in the grid)

Thanks

**Comment by jassmith** [comment]
Column grouping is planned, column pivot is also planned but more distant, column level filtering is planned, column selection is pretty easily implemented using the `rightElement` and not something I plan to bring in as first class.
