### ISSUE TITLE
Redraw Header

### ISSUE THREAD

**Issue by ricosw** [glideapps/glide-data-grid#499]
I added using the drawHeader prop some custom filters with icons.
Also, I am using the onHeaderClicked to track the header cell click and change some filter settings.
Is there a function to force redraw the header (cell) so that my icons are also updated, like the updateCells function, but for the header?
The header cell is only redrawn when I re-hover the cell again. 

I am currently using the version: 5.1.0-beta1

**Comment by jassmith** [comment]
Hey Rico, I will make sure you can do this.

**Comment by jassmith** [comment]
You can actually use the existing updateCells API. The header is just the cell at row -1 :)
