### ISSUE TITLE
EditableGridCell should have a common newValue property

### ISSUE THREAD

**Issue by dvdsgl** [glideapps/glide-data-grid#5]
```ts
type EditableGridCell = TextCell | ImageCell | BooleanCell | MarkdownCell | UriCell | NumberCell;
```

`EditableGridCell` does not have a common property across union types that represents the new value, so you have to do clumsy checking in `onCellEdited` (for example). It would be nice to be able to:

```ts
onCellEdited={([col, row], editedCell) => console.log(editedCell.newValue)}
```

**Comment by schani** [comment]
I think the naming is just bad:

* Most cells have `data`, except for `BooleanCell`, which has `checked`.
* Some cells also have `editData`, which is the actual underlying value, whereas their `data` is the display value.

I think we should

* Make `data` always be the underlying value, and have an optional `displayData` when appropriate.
* Rename `checked` in `BooleanCell` to `data`.
