### ISSUE TITLE
Fill handle does not fill when dragged past last row

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#501]
If you drag the fill handle past the last row it does not trigger `onCell(s)Edited`, you have to stop at exactly the last row for it to fill to the bottom, but being able to overshoot like this makes it easier to use.

https://user-images.githubusercontent.com/94077014/191622562-4f2883b1-179b-4542-861a-acb3fe99a0af.mp4

Additionally, if you drag the the fill onto the trailing row, it attempts to edit that. This row should probably be skipped when calling the `onCell(s)Edited` callbacks.

https://user-images.githubusercontent.com/94077014/191622821-212e6d51-c8c8-42ac-962c-9ffffe58b256.mp4

**Comment by jassmith** [comment]
Fixed in main, look for it in 5.1.3
