### ISSUE TITLE
Column group top-left header cell draws unnecessary border

### ISSUE THREAD

**Issue by dominik-zeglen** [glideapps/glide-data-grid#505]
When using column groups, top-left header cell renders additional border, which is barely unnoticeable on demo:
<img width="794" alt="Zrzut ekranu 2022-09-23 o 12 39 37" src="https://user-images.githubusercontent.com/6833443/191943919-20aedec9-85c1-4447-8f91-2074f55405ea.png">

but after some theme customization it becomes really visible:
<img width="821" alt="Zrzut ekranu 2022-09-23 o 12 35 35" src="https://user-images.githubusercontent.com/6833443/191944004-c0a87dcd-8f6e-4930-9c1f-1425a82fb10a.png">

**Comment by jassmith** [comment]
Thank you for the report, will fix

**Comment by jassmith** [comment]
Fixed in main, look for it in 5.1.3
