### ISSUE TITLE
Regression in 5.x: up/down arrows events are bubbled out of grid

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#506]
How to reproduce:
open page: https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cells

1. zoom in (cmd+ or ctrl+) multiple times so that table does not fit into the page and scroll bars appear.
2. use arrows to move up and down - active cell changes as expected, but additionally all the table is scrolled

This issue appeared after migrating from 4.x to 5.1

**Comment by jassmith** [comment]
Fixed in 5.1.1
