### ISSUE TITLE
Regression in 5.x: string data replaced on enter 

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#507]
How to reproduce: 

open https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-data

1. focus on some text cells, press enter. Not only enter activates editing, enter keypress is received by textbox, so original editor content is lost and replaced by newline
2. double click on any text field - editing works as normal

**Comment by jassmith** [comment]
Fixed in 5.1.1
