### ISSUE TITLE
Bug: Focus leaves grid on tab events

### ISSUE THREAD

**Issue by reczy** [glideapps/glide-data-grid#508]
5.1 was a great update - thank you for the continued work and features! One bug I noticed:

1. Visit https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-columns
2. Click on cell in first column
3. Click and hold the `tab` button (or just keep clicking it)

The result is that focus will escape the grid and move through the rest of the links on the page before going back to the grid (in repetition).

![CleanShot 2022-09-26 at 13 58 49](https://user-images.githubusercontent.com/1100860/192359026-62c41c23-3758-4650-9df1-f87547d402cc.gif)

**Comment by jassmith** [comment]
This is some kind of race with the accessibility tree it seems. If you slow down and tab at a slower rate it doesn't happen. Not sure how to fix yet.

**Comment by jassmith** [comment]
This is fixed in 5.1.1, tab now only escapes focus when hitting the last cell.
