### ISSUE TITLE
onGridSelectionChange behaviour

### ISSUE THREAD

**Issue by mihaildu** [glideapps/glide-data-grid#515]
Hello!

I am curious about what `onGridSelectionChange` prop should do. From documentation [here](https://grid.glideapps.com/docs/interfaces/DataEditorProps.html#onGridSelectionChange)
> Emitted whenever the grid selection changes.

What I understand from this is that I can get a callback every time the grid selection changed, so I can do my own extra logic there, the same way I can with [onSelectionCleared](https://grid.glideapps.com/docs/interfaces/DataEditorProps.html#onSelectionCleared).

However, this is not currently the case. Adding a `onGridSelectionChange` prop will break the app, it becomes unresponsive. This is because of these lines here https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L826-L831

It means I have to implement my own `setGridSelectionInner` which I'm not sure it's possible, since it updates the inner state of glide data grid.

If this prop was meant to be just a way to get a callback whenever selection changes, then the `else` bit there has to be removed (I could make a PR!)

Thank you!

**Comment by jassmith** [comment]
if you set `onGridSelectionChange` you should also be passing a `gridSelection` value. I am considering making this not required, but at this time it is not a bug.
