### ISSUE TITLE
Missing rightmost cell borders when scrolling right with smoothScrollX

### ISSUE THREAD

**Issue by gkn** [glideapps/glide-data-grid#519]
The last vertical cell borders disappears when scrolling right using keyboard arrow right on this small sample:

[https://playcode.io/974328](https://playcode.io/974328)

You can see it flash before it disappears. Needs to have 5 or more rows to trigger the bug it seems.

**Comment by jassmith** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/30443/193298586-5c8e95c9-6677-446c-b2aa-eebb51ce6d70.png)

**Comment by gkn** [comment]
No, in that last column the left border is missing on all rows. Impossible to take a screen shot/snip as the border will be drawn as soon as the grid lose focus. You should see it when scrolling using the keyboard right arrow key (selecting cell). Tested on Windows 10+11, latest Chromium browsers.

**Comment by gkn** [comment]
Thats it :)

**Comment by jassmith** [comment]
Found the issue, it will be fixed in 5.1.3

**Comment by gkn** [comment]
Great :)
