### ISSUE TITLE
how to create a custom cell renderer?

### ISSUE THREAD

**Issue by hyusetiawan** [glideapps/glide-data-grid#521]
I see the example here: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--draw-custom-cells
but i am not sure how to read the example code? Is there a tutorial somewhere perhaps?

**Comment by jassmith** [comment]
Consider reading these custom cells here. They use the more modern API and are better encapsulated. Am closing issue but I will continue watching it for questions.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/tree/main/packages/cells/src/cells forgot the link.

**Comment by hyusetiawan** [comment]
@jassmith is there documentation for the various properties? such as `needsHover` or `drawPrep`, tried searching the property name but can't find any lead

**Comment by jassmith** [comment]
I will add those asap, oversight. Long and short of those two, `drawPrep` is only needed if you are doing expensive setup. `needsHover` should only be set true if you are going to respond to the hover values in the draw event. When set to `false` we optimize away some drawing calls.

**Comment by hyusetiawan** [comment]
@jassmith thank you, I appreciate it! 

If you don't mind, on top of the couple of threads I already brought up in the issues tab, I have even more questions? :D

For my use case is for a custom cell to dynamically `draw()` and `provideEditor()`, for example, draw: a checkbox but provideEditor is an `<input type="date" />`  or provideEditor is a dropdown and draw is an image of the selected dropdown. My thinking is that we need to get the common denominator of cell config, so for example, I'll just turn on `needsHover` for the custom cell whether I may or may not need it just in case I need it. Would you be able to provide guidance on how to achieve this setup? I came up with he following pseudo code:

```

export const DisplayCell: CustomRenderer<DisplayCell> = {
  kind: GridCellKind.Custom,
  isMatch: (cell: CustomCell): cell is DisplayCell => (cell.data as any).kind === 'display-cell',
  draw: (args, cell) => {
    const { data } = cell
    switch(data.display.type) {
         case 'string':
              return AllCells[GridCellKind.Checkbox].draw(arg, {mock the structure to contain text}) //should i call drawTextCell directly?
         case 'checkbox':
              return AllCells[GridCellKind.Checkbox].draw(arg, {mock the structure to contain boolean})
    }

  },
}
```

Hope I am making sense!

**Comment by jassmith** [comment]
Okay so you're one step ahead of me here, for now I would just copy the relevant methods out of data-grid-lib. It is my intention to make that drawing of "common" cell types easy, but I haven't done that because its a large amount of API to review.

**Comment by hyusetiawan** [comment]
@jassmith thank you for the tips! Once the documentation for those properties is available, I think I can somewhat guess my way to a common renderer. You mentioned there is a perf cost with `needsHover`, how costly is it if I set it to true for all of my renderers?

**Comment by jassmith** [comment]
Not at all costly :P

I'm just insane about making things fast so when I want to make things nice, I have the overhead.
