### ISSUE TITLE
cellVerticalPadding doesn't seems to work

### ISSUE THREAD

**Issue by yestoall** [glideapps/glide-data-grid#524]

**Comment by jassmith** [comment]
cellVerticalPadding is used for the button cell, sparkline cell, tags cells, user profile cell, text cell, and image cell to control the maximum height of cells. Where are you having issues?

**Comment by yestoall** [comment]
I have issues with TextCell, I doesn't works... with horizontalPadding works ok but not with verticalPadding

**Comment by jassmith** [comment]
Closing due to lack of info.
