### ISSUE TITLE
No Callback Function to get Selected Rows

### ISSUE THREAD

**Issue by mattruddy** [glideapps/glide-data-grid#528]
There doesn't seem to be any callback function to get the selected rows in the grid. 

![Untitled-2022-10-09-2307](https://user-images.githubusercontent.com/30830407/194794280-3fb7cc3a-7fd7-4c89-8258-5144571fcfa9.png)

**Comment by jassmith** [comment]
`gridSelection` and `onGridSelectionChange` are what you are looking for. The new gridSelection has a rows property.
