### ISSUE TITLE
`themeOverride` for marker column

### ISSUE THREAD

**Issue by mr-winter** [glideapps/glide-data-grid#531]
We recently added Glide Data Grid to our web application and it works very nicely. Great work! In particular it solves the performance issues that the previously used library was giving us for large datasets. 

There are a few minor issues that we haven't been able to solve yet though. 

One of them is the ability to style the marker column on the left. There doesn't seem a way to draw custom things into these cells or to pass a theming override. 

Perhaps I am missing something. Otherwise, would you consider adding this feature?

**Comment by jassmith** [comment]
What would you like to do?

**Comment by mr-winter** [comment]
Just give it a different background colour from the cells, like here

<img width="105" alt="image" src="https://user-images.githubusercontent.com/5445640/195199297-31d737d3-0f79-42f7-b4cc-2d12112e4eea.png">

**Comment by jassmith** [comment]
It would be easy enough to add a `rowMarkerTheme` prop

**Comment by jassmith** [comment]
Okay this will be allowed in 5.2.0

**Comment by mr-winter** [comment]
I gave it a quick test. It works! Thank you
