### ISSUE TITLE
Extended cell mouse events

### ISSUE THREAD

**Issue by mr-winter** [glideapps/glide-data-grid#532]
Is there any way to access the `mousedown` or `mouseup` events, similar to the click event with `onCellClicked`?

The reason I'm asking is that we're keen to implement a multi row selection by clicking on a marker column cell and dragging the mouse down / up, similar to what Google Sheets or Apple Numbers does.

**Comment by jassmith** [comment]
There is no access to these events. That said this is a great idea and I will add this to 5.2.0 prior to launch. No reason I can think of not to.

**Comment by mr-winter** [comment]
Amazing! Thank you

**Comment by jassmith** [comment]
This is fixed in 5.2.0-beta2

**Comment by mr-winter** [comment]
Works nicely 👌

**Comment by jassmith** [comment]
This is related. I guess it should only select if it’s not already a
selected cell.

**Comment by jassmith** [comment]
Please try 5.2.0-beta3

**Comment by mr-winter** [comment]
Yes, that works, maintaining the selection when right clicking on one. 

One thing that doesn't _quite_ make sense to me is that when you right click on the marker cell, it selects the first column. Should this select the whole row instead?
