### ISSUE TITLE
Horizontal Scrolling on Mac

### ISSUE THREAD

**Issue by Sam-2** [glideapps/glide-data-grid#533]
Is there an existing way to make horizontal scrolling of a data grid on Mac easy?

On Mac, scrollbars only show when scrolling (depending on settings in system preferences) and so I can only get the horizontal scrollbar to show up after I have already scrolled horizontally in some other way like clicking and dragging. By the time I have moused down to try to grab the horizontal scrollbar it has already disappeared. If I try and click near the bottom of the table, sometimes I can grab the horizontal scrollbar, but it's not easy.

Thanks.

**Comment by jassmith** [comment]
There is nothing planned about this right now. The scrollbars are owned by the OS and largely out of our control.
