### ISSUE TITLE
Hide columns with spans (merged cells)

### ISSUE THREAD

**Issue by connorproctor** [glideapps/glide-data-grid#537]
Is there an easy way to hide/filter columns from being displayed while accounting for cells that span across those columns?

Currently I'm filtering out hidden columns before passing them into DataGrid, but it's tricky to have spans account for the hidden columns.

For example, if I have a span [4, 6], and then I hide column with index 5, the new span should be `[4, 5]`. But this can be tricky to figure out when hiding arbitrary numbers of columns.

**Comment by jassmith** [comment]
instead of removing the column from the grid have you tried settings its width to 0?
