### ISSUE TITLE
Border sometimes not visible

### ISSUE THREAD

**Issue by ColmanHumphrey** [glideapps/glide-data-grid#540]
Fantastic library all!

One small issue I sometimes see is a missing border. Here's a video, where I have six rows at regular zoom, and the line between rows 6 and 7 isn't visible until I scroll (but side-scrolling brings it partly into view):

https://user-images.githubusercontent.com/6945891/199630568-4d8a55a9-9909-487a-97ba-41362eff5d6c.mp4

Then at 110% zoom I have five rows, and the line between 5 and 6 isn't visible:

https://user-images.githubusercontent.com/6945891/199630630-d0cda6d8-0b76-4071-8760-f253d46a2191.mp4

It's a bit annoying to repro, but I am able to recreate it whenever the border lines up with the edge of the containing div. Here's me doing it by resizing my screen, using https://slight.run/datasets/amaris/annual_co2_emissions_per_country:

https://user-images.githubusercontent.com/6945891/199630850-4cddd0ca-a5ba-4463-865f-e4c3b46bf8c3.mp4

You can see that when I get the resize down to where the table is exactly 13 rows, the border disappears.

Thanks! If you think more details could help (our css etc) let me know.

**Comment by ralake** [comment]
I have also encountered this issue when adding new rows. Occasionally the horizontal border between the newly created row and the original last row is missing until i scroll. Again, it seems to line up with that row being at the bottom of the container

**Comment by jassmith** [comment]
What version of the grid do you see this on? Can you try the 5.2.0 beta?

**Comment by ralake** [comment]
5.1.4 for me. Can try and update this week and see if the issue is still there...

**Comment by jassmith** [comment]
I cannot reproduce this behavior. If anyone has a reliable reproduction I need to have the OS, browser, screen DPI, and GDG version to fix this.

**Comment by ColmanHumphrey** [comment]
I'll work on a repro too!
