### ISSUE TITLE
getCellContent called for cells out of range of the rows prop

### ISSUE THREAD

**Issue by ralake** [glideapps/glide-data-grid#543]
I'm seeing some issues with getCellContent being called with a row index greater than or equal to the `rows` prop passed in. This happens only occasionally, often at points when the rows change size significantly such as bulk deletions or additions, and the user is hovering over the grid. It's not easily replicable right now but I will try and get a screen recording and some evidence. Just wondering if this has been reported before or is known about?

I have a temporary fix in place to return an uneditable text cell from `getCellContent` if the row index >= rows.

**Comment by ralake** [comment]
![Screenshot 2022-11-03 at 16 11 03](https://user-images.githubusercontent.com/8901119/199774017-9d7b838d-8dd1-4a83-b844-7ed38cce95f0.png)

`rowCount` is the value we pass as the `rows` prop to the grid. Can see here that the rowIndex requested is equal to rowCount. Appreciate this is a snippet from my code rather than proving this is happening within glide, i can try get a screenshot of that too

**Comment by ralake** [comment]
<img width="588" alt="Screenshot 2022-11-04 at 10 53 09" src="https://user-images.githubusercontent.com/8901119/199956097-71631806-8a7d-4001-9ea8-abd5ecdeae30.png">

Added a condition and debugger to where this was happening inside the data grid. This screen grab shows that getCellContent is being called with `row` `14` even though the `rows` prop is `1` - https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L1144

**Comment by jassmith** [comment]
Thank you I will get to this ASAP

**Comment by jassmith** [comment]
In the experimental flags there is a mode called "strict" which will prevent this. Unfortunately, it will also sometimes trigger flashing. I am still working out why.

`<DataEditor experimental={{strict: true}} />`

**Comment by jassmith** [comment]
This is fixed in main
