### ISSUE TITLE
Feature request: Row menu

### ISSUE THREAD

**Issue by fakob** [glideapps/glide-data-grid#544]
Your implementation of a column menu works really great and has all there is to implement adding column actions.

Now I was wondering if the same is possible for a row. A row menu would allow to easily implement adding rows above/below or delete them. Or is that something I could implement myself. For example via a right click option?

I have added the option to add rows at the end, but having an "embedded" way to add rows in between would be really helpful.

**Comment by jassmith** [comment]
I will make this easier.

**Comment by amiregelz** [comment]
@jassmith This would be extremely helpful - both delete and insert above/below 🙏

**Comment by jassmith** [comment]
The `onCellContextMenu` event is already emitted, initially by mistake but now as a feature, with the column index of -1 when right clicking on a row. You can then implement the menu in the same way as the column menu example.

**Comment by fakob** [comment]
Ah, nice. Thanks @jassmith for pointing this out. 

There is one small UX caveat, but not a big issue. If I am not mistaken, there is no context click for the header. This means that the user has to
* left click the header menu icon for getting the header menu
* right click a row/cell to get the context menu
I checked google sheets and they provide both a left and right click option for the header. 

Again, not a big issue. I just wanted to point this out.

**Comment by jassmith** [comment]
`onHeaderContextMenu`

**Comment by fakob** [comment]
Ah, sorry @jassmith. My bad. This I had overlooked. Thanks!
