### ISSUE TITLE
Gradient fade support

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#546]
We're using a gradient fade to truncate text in some of our cells, but we're running into some issues because the canvas needs‡ to know the cell's background color. We've been able to approximate what the background should be using the `highlighted` property from `DrawArgs`, but once highlighting is combined with custom background colors or various gridSelections, this breaks down. Would it be possible to provide the "flattened" background color in `DrawArgs`?

https://user-images.githubusercontent.com/94077014/200645895-9e57d93a-57c5-4ff4-acf9-e95b25cd6275.mp4

‡ There isn't a way to draw with a gradient mask in canvas directly, but one way to achieve that is to draw into an offscreen canvas, apply the gradient with the right `globalCompositeOperation`, then pull that out as an image and draw it to the onscreen canvas. https://stackoverflow.com/a/28779849 We could go with this approach, but I think the performance would be far worse than drawing the colored overlay over the cell directly.

**Comment by jassmith** [comment]
instead of overdrawing the cell, fill the text with a gradient that fades out at the end.
