### ISSUE TITLE
Cannot open menu using react-laag example (storybook docs 09)

### ISSUE THREAD

**Issue by sergeykimaia** [glideapps/glide-data-grid#553]
I've copied the code that was used in [the menu example (docs 09 in the storybook)](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-docs--menus)

and the menu never opens, react-laag's `onOutside` click happens immediately after `onHeaderMenuClick` happens

heres a reproduction:
https://codesandbox.io/s/inspiring-mirzakhani-qpw7rh

**Comment by jassmith** [comment]
Seems to be an issue with react 18. Will try to figure out how to fix. Works fine in React 17 and down.

**Comment by jassmith** [comment]
So I have a branch that fixes this. Something changed in react 18 about how click events work. Yay....

Problem is it is a *pretty* invasive change, will require lots of testing. Would you be willing to pitch in helping test interactions on an alpha package?

**Comment by sergeykimaia** [comment]
@jassmith im willing to test if it works fine in my code

**Comment by chunming-c** [comment]
umm seems this issue is still happening 🤔
