### ISSUE TITLE
Gradient fade support pt. 2

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#561]
This is a follow-on to #546

We have used gradient fade for some of our text drawing, but we'd also like to be able to fade other things like the backgrounds/borders/etc. for things like these drilldown cells. Do you have any suggestions for how to do that?

Current:

<img width="1098" alt="Current" src="https://user-images.githubusercontent.com/94077014/203371106-3d2d91c8-3e9f-4436-9c42-ec0ec6398fa9.png">

Preferred:

<img width="1098" alt="Preferred" src="https://user-images.githubusercontent.com/94077014/203371151-12676635-6e0e-4ce1-a39d-28f2e15c7fb5.png">

**Comment by jassmith** [comment]
okay I will figure out a mechanism to do this efficiently

**Comment by jassmith** [comment]
So it seems to me there are 3 types of cells for this feature

- Text cells
- Checkboxes / Sparklines
- Other cells

### Text Cells

This effect is most efficiently rendered by filling the text with a well crafted horizontal gradient. This has been mentioned before. However the solution which will be proposed for other cells will also work for text cells, just an increased computation.

### Checkboxes/Sparklines

These cell types should never have a fade applied. Probably other cell types fall into this as well.

### Other Cells

A generic solution to this is to record the final fill background color for each box region in a column. Then when the column draw completes, overdraw the cell ends fill each region back in with the correct colors. Group colors together into single draw calls. This will be expensive but not prohibitively so. It will be made much cheaper by blitting which is enabled by default.

## Other complications

There are other complicating factors at play here. The cell may be redrawn by a damage event at any time, so damage draws must be careful to re-apply the mask as well. This will make animations slightly more expensive.

**Comment by yusufkinatas** [comment]
This is what we're using on our custom cells to have gradient fade support. It might be helpful https://github.com/hashintel/hash/blob/f1a5dce88ff001f914b8054bfb307d18280a7d30/packages/hash/frontend/src/components/grid/utils/draw-cell-fade-out-gradient.ts

**Comment by jassmith** [comment]
I don't see how it could, this really needs proper deep integration into the render stack.

**Comment by yusufkinatas** [comment]
> Does this work properly when the cell is selected? Or when using highlightRegions?

In our case, we only use `bgColor`, and change `bgColor` manually on hover due to a specific behavior we implemented on grid. So it's not covering the cases you mentioned, just adds a gradient overlay based on `bgColor`.

**Comment by jassmith** [comment]
In 6.0.0 cellFillColor is now available in the draw args. This color is the color you need to fade to to make this effect.
