### ISSUE TITLE
GridCellKind.Text with line breaks renders incorrectly

### ISSUE THREAD

**Issue by simenbjorkhaug** [glideapps/glide-data-grid#562]
### What

The ```GridCellKind.Text``` display data causes a bug when the text contains line breaks and it won't break text correctly anymore for other cells.

### Reproduce

Row height either through custom rowHeight property or through the standard 34 ( ? ) causes the issue. With text that contains a line break.

### Work around

Normalize data to not use line breaks. 

### Type

Bug.

----

I can have a look myself and potentially submit a PR, I just don't have time for it in the foreseeable future.

**Comment by jassmith** [comment]
I'm confused, can you please provide like a super small demo? I don't get the bug.
