### ISSUE TITLE
Add link on Stories to the example code?

### ISSUE THREAD

**Issue by TravisL12** [glideapps/glide-data-grid#565]
Seeing the code behind the Storybook stories is very helpful. But to do this I have to search through the examples directly in GH. Adding a direct link to the code would be very helpful.

**Comment by jassmith** [comment]
![image](https://user-images.githubusercontent.com/30443/204414103-8d6c4a8a-7f42-4b35-a443-0c0a6e4a5d7f.png)

You should be able to see the source directly in storybook

**Comment by TravisL12** [comment]
Oh. Well there it is. 

Thanks!
