### ISSUE TITLE
Glide datagrid page pagination and widget controls. 

### ISSUE THREAD

**Issue by rockus123** [glideapps/glide-data-grid#569]
Hi,

How do we implement this this datagrid pagination with pagination controls or widgets.  For example, page 1 of 200 and display of 50 per page.   Thanks.

**Comment by jassmith** [comment]
There are no built in pagination controls, however they are not hard to implement, I will add a storybook story.

**Comment by rockus123** [comment]
> There are no built in pagination controls, however they are not hard to implement, I will add a storybook story.

Thank you.  That will be very useful for us.

**Comment by nandorojo** [comment]
Just checking, is there a storybook for this? Perhaps something like:

→ `onEndReached` to trigger infinite scroll, and/or adding a button at the footer to "load more"
→ the ability to show a loading state at the bottom (or in a row) to indicate more cells are loading

**Comment by jassmith** [comment]
`onVisibleRegionChanged` has the information you need. As for skeleton loaders, there is a spinner cell in the cell package. You could also change the loading cell to draw a grey rounded rect if you want.
