### ISSUE TITLE
Field for uploading files

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#573]
I believe it is quite common to have files associated with a particular row. 

Examples are attached documents, or reports, or invoices, or equipment specifications.

I realize that uploading interface would require some backend support, but I believe there is value in having some template of such field (e.g. I have a number of custom fields, but it isn't clear to me how to make one with simple 'upload' button)

**Comment by pzcfg** [comment]
Given how much you may want to customize the uploading UI, restraints and backend, I don't think it makes sense to add a built-in cell for this. I think your best bet is to add a custom editor using `provideEditor` and putting the input button in there, for example:

```
provideEditor={cell => {
    // add whatever other criteria you need to this condition to show this for just your file upload cell
    if (cell.kind !== GridCellKind.Custom) return undefined

    return p => {

        const inputRef = React.useRef<HTMLInputElement>()

        // add effects/hooks/etc. to handle uploading when a file is selected
        // you could also add a inputRef.current.click() useEffect to automatically click the upload

        return <div>
            <input type="file" ref={inputRef}></input>
        </div>
    }
}}
```

https://user-images.githubusercontent.com/94077014/207231216-e3b41313-c678-46e0-9999-59990f2f0064.mp4

Alternatively, you could listen to `onCellClicked` and if your upload cell is clicked, you `inputRef.current.click()` an input element hidden elsewhere on the page.

**Comment by jassmith** [comment]
I am not planning to add an upload field to the core for some time. PR welcome to the cells package.
