### ISSUE TITLE
Sporadic CanvasGradient errors

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#577]
We haven't been able to consistently repro this issue, but occasionally we encounter this
`Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN, 1, undefined, 0)') could not be parsed as a color.`

<img width="707" alt="drawHeader-gradient" src="https://user-images.githubusercontent.com/94077014/207945537-dcecb880-0b39-40a4-8048-756101b67fc8.png">

It seems the issue stems from these `withAlpha()` and `parseToRgba()` functions

<img width="472" alt="Screen Shot 2022-12-15 at 10 20 59 AM" src="https://user-images.githubusercontent.com/94077014/207945484-a4e2ccf2-bd8a-4ed3-8cf2-fddffd81bb7f.png">

<img width="655" alt="Screen Shot 2022-12-15 at 10 21 42 AM" src="https://user-images.githubusercontent.com/94077014/207945523-28f6d27d-560e-4a3d-a090-b22e1e98a45b.png">

but after testing various color formats I couldn't find a way to get this to occur. I also looked at the theme colors we're passing in to see if there is anything strange there, but they're all typical hex color strings of the form `#FFF` or `#FFFFFF`.

---

Not sure what the right fix is here, but at the very least it seems like it might be worth adding a guard to `parseToRgba()` that ensures it is actually returning numeric values, and maybe include the `normalizedColor` and `computedColor` in an error when it is non-numeric.

**Comment by jassmith** [comment]
Great idea will improve instrumentation.

**Comment by jassmith** [comment]
Fixed in 5.2.2
