### ISSUE TITLE
Make Row Height Fit Content

### ISSUE THREAD

**Issue by mjewell** [glideapps/glide-data-grid#581]
Is there any way to make it so the row heights are based on the content of the largest cell in that row? The [text wrapping demo](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--wrapping-text) looks like it fixes the row height at 80, but I want to show all the content in the cell without having to double click into it. If we had access to the cache from [this PR](https://github.com/glideapps/glide-data-grid/pull/373) I think we could use that in the `rowHeight` callback to set the height based on the number of lines, but I can't figure out how to do it otherwise.

**Comment by mjewell** [comment]
I don't think this is a particularly great solution, but I was able to get this mostly working by doing this

```ts
import { clearCache, split } from "canvas-hypertxt";

type DrawHeaderArgs = Parameters<DrawHeaderCallback>[0];

function useDynamicRowHeights() {
  const headerArgsRef = useRef<DrawHeaderArgs[]>([]);

  function saveSplitArgs(col: number, args: DrawHeaderArgs) {
    headerArgsRef.current[col] = headerArgsRef.current[col] || args;
  }

  function getTextHeight(col: number, text: string) {
    if (!headerArgsRef.current[col]) {
      return 0;
    }

    // copied from https://github.com/glideapps/glide-data-grid/blob/2b003b8c6bdb93045d4effb6a3e089d98fcd3e79/packages/core/src/data-grid/data-grid-lib.ts#L454
    const {
      ctx,
      rect: { width },
      theme,
    } = headerArgsRef.current[col];
    const fontStyle = `${theme.fontFamily} ${theme.baseFontStyle}`;
    ctx.font = `${theme.baseFontStyle} ${theme.fontFamily}`; // for some reason this needs the order switched
    clearCache(); // why do we have to call this every time?
    const lines = split(
      ctx,
      text,
      fontStyle,
      width - theme.cellHorizontalPadding * 2
    );
    return lines.length;
  }

  return [saveSplitArgs, getTextHeight] as const;
}

function MyComponent() {
  const [saveSplitArgs, getTextHeight] = useDynamicRowHeights();

  return (
    <DataEditor
      getCellContent={getContent}
      columns={columns}
      rows={rows.length}
      drawHeader={(args) => {
        saveSplitArgs(args.columnIndex, args);
        return false;
      }}
      rowHeight={(rowIndex) => {
        const cellHeights = Array.from({ length: columns.length }).map(
          (_, colIndex) =>
            getTextHeight(
              colIndex,
              getContent([colIndex, rowIndex]).displayData
            ) * 17
        );
        return Math.max(...cellHeights, 34);
      }}
    />
  );
}
```

The biggest issues being

1) I have to call `clearCache` every time a row height is calculated. Seems like it would lead to pretty significant performance degradation but fortunately for my use case the grid is very small and I don't expect this to be an issue.
2) I read from an example that `ctx.font = ` is slow so ideally we could avoid doing that so often too.
3) Since `drawHeader` only gets called when the header is visible, it could be that there's a large cell off screen and once you scroll to it the row will resize. Not a huge deal to me but not ideal either.

**Comment by jassmith** [comment]
not sure what version of canvas-hypertxt you are on but `clearCache` only clears out caches. The canvas-hypertxt `fontStyle` argument is just a key. The order of the parameters you are passing do not matter at all. It can take the same string ctx.font takes. The reason you are having to set the ctx.font every time is you are trying to re-use the canvas's the data grid is using. Just make an offscreen canvas and store it in your hook. This will eliminate the need to call ctx.font so much (more than once) and also I suspect fix your clearCache issue.

Point 3 is also fixed by simply having your own canvas. Basically there is nothing magical about the ctx canvas-hypertxt uses, it just needs one that has the font property already set correctly.

**Comment by YousefED** [comment]
@jassmith this is not a built-in option yet right? So we'd need to implement something like @mjewell suggested?

@mjewell would you be open to sharing your (fixed) snippet?
