### ISSUE TITLE
When zoomed out (in storybook), the pointer events are not targeting the right element

### ISSUE THREAD

**Issue by janwirth** [glideapps/glide-data-grid#582]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/7485959/210161550-5880e792-e11d-4b42-83cd-cec1d9358f05.png">

**Actual**
1. I go here (https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--all-cell-kinds) and zoom out using the storybook zoom buttons
2. I double-click click the 10th cell in the ID column
3. the 5th element is selected

**Expected**
After 2. I expect the 10th cell in the ID column to be selected.

**Comment by jassmith** [comment]
This is due to the iframe and `getBoundingClientRect` not working as expected in that context in Chrome. Works correctly in firefox. Unless someone has a performant method of getting the effective scaling factor in chrome in an iframe I don't think there is much I can do.

**Comment by jassmith** [comment]
Quick note: it works fine not in an iframe.
