### ISSUE TITLE
Update storybook to use `react-popper` instead of `react-laag`

### ISSUE THREAD

**Issue by homanp** [glideapps/glide-data-grid#584]
`react-laag` seems like it's unmaintained. I implemented header menus using `react-popper` instead. `react-popper` is used by many bigger component libraries such as `Chakra`. 

I can support by sharing some code if that helps.

**Comment by jassmith** [comment]
I'd be more than happy to receive an example of using react-popper. Will add it in there alongside react-laag. I just happy to like react-laag a smidge more, damned shame it's gone unmaintained.

**Comment by homanp** [comment]
@jassmith Sure I implemented it like so:

```
import React, {useMemo, useRef} from 'react';
import {usePopper} from 'react-popper';

export default function ContextMenu({bounds, children, ...properties}) {
	const popperReference = useRef();
	const virtualReference = useMemo(
		() => ({
			getBoundingClientRect() {
				return {
					left: bounds?.x || 0,
					top: bounds?.y || 0,
					width: bounds?.width || 0,
					height: bounds?.height || 0,
					right: (bounds?.x || 0) + (bounds?.width || 0),
					bottom: (bounds?.y || 0) + (bounds?.height || 0),
				};
			},
		}),
		[bounds],
	);

	const {styles, attributes} = usePopper(virtualReference, popperReference.current, {
		placement: 'bottom',
	});

	return (
		<div
			ref={popperReference}
			style={styles.popper}
			{...attributes.popper}
			{...properties}
		>
			{children}
		</div>
	);
}
```

`children` could of course be any component you might want to pass.

**Comment by jassmith** [comment]
Going to close this as wont fix for now. hopefully new maintainers will come along and offer a PR here.
