### ISSUE TITLE
downFill triggers "add to bookmarks", and not filling the next cell

### ISSUE THREAD

**Issue by arogozhnikov** [glideapps/glide-data-grid#585]
Hi Folks, I can't make downFill work.

Right now I've tried two combinations:
```
keybindings: {downFill: true},
```

and 
```
keybindings: {downFill: true, copy: false, paste: false},
```

Second one confirms that I configure it right (copy and paste shortcuts don't work anymore, as expected).

In both cases 1 and 2 I was not able to use downfill (cmd+D) in Firefox, Brave (chrome-based), and Safari. Instead, a dialog to add site into bookmarks appears (default action for this shortcut).

**Comment by arogozhnikov** [comment]
Update: tried manually emitting event "fill-right" and nothing happened.

**Comment by jassmith** [comment]
I am not able to reproduce this issue on windows. Next time I'm near a mac I will double check the handler.

**Comment by jassmith** [comment]
Can you check if this is working for you here: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--fill-handle

I've enabled the keybindings in that story and they work for me just fine on a mac.

**Comment by arogozhnikov** [comment]
strange, but still does not work for me 🤷 .

Checked in Firefox and Chrome all combinations of Ctrl/CMD + R/D and neither copied the value.
I even checked that keyboard uses english-american locale, turned off key modifiers - and still that doesn't work.

Not an issue for me really, custom-defined shortcuts with handlers seem to work fine, and that covers my needs.

**Comment by jassmith** [comment]
Thank you I will keep attempting to repro

**Comment by jassmith** [comment]
I still cannot repro with 6.0.0, please re-open if you are still having issues.
