### ISSUE TITLE
`onColumnResizeEnd` trigger twice if resizing column is not the selected (highlighted) column

### ISSUE THREAD

**Issue by nightire** [glideapps/glide-data-grid#586]
I have two video clips to demonstrate this bug:

1. ✅ resizing column is also the selected column (or no selected column at all)

https://user-images.githubusercontent.com/1104018/211193818-9a74f797-8f1d-4670-bddc-1d1788eec12c.mov

2. ❌ resizing column is not the selected column or not any of multiple selected columns

https://user-images.githubusercontent.com/1104018/211193981-216d51b2-c7b3-41b7-8ba8-3503307a91c9.mov

I believe the `onColumnResizeEnd` callback should be called only once, even if (an)other column(s) has been selected.

In addition, if users select one or more columns and then resize one (one must be selected), `onColumnResizeEnd` could be fired multiple times to resize multiple columns once and for all.

**Comment by jassmith** [comment]
Fixed in 5.2.2
