### ISSUE TITLE
Force column resizing

### ISSUE THREAD

**Issue by ralake** [glideapps/glide-data-grid#588]
Hi - just wondering if there is a way to force a resize of all columns? If i have some data available when I render the grid, then some other data loads in async that would impact the column sizes, i'd like to be able to resize the columns at that point. I would have thought it might be a method on the ref if anything

Thanks for any help with this

**Comment by jassmith** [comment]
Good idea. Proposed API will be just on the ref, the ability to pass a CompactSelection to a function which will normal size every column in the selection. Work for your need?

**Comment by ralake** [comment]
That sounds like it would do the trick nicely. For now I have adjusted my app to wait for the async data to load in before rendering the grid

**Comment by jassmith** [comment]
`remeasureColumns` has been added in main
