### ISSUE TITLE
Support overwriting the copy-to-clipboard value for all cell types via `copyData`

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#592]
If the user copies data to the clipboard, the copied value of a cell will depend on the cell type: 

https://github.com/glideapps/glide-data-grid/blob/77ee5dee0847dde2d078f337f8da9c61cb0ded43/packages/core/src/data-editor/data-editor-fns.ts#L232

In some situations, it might be good to have some additional control over the value that is copied to the clipboard. For example, a text cell with `null` as data might be shown as an empty string in the `displayData` but if a user copies it to the clipboard, an `NA` placeholder might be preferred. Or maybe you want to use the JSON list syntax for `GridCellKind.Bubble` instead of just a comma-separated list etc...

My suggestion would be to support `copyData` as part of `BaseGridCell` for all cell types as an optional property to overwrite the value used for copy-to-clipboard. This could be also very useful for features that allow downloading/exporting the data to a file format.

An alternative might be to provide an `onCopy` callback that can be used to overwrite the value that is used when a cell is copied. 

_I might have some time at the end of the month to investigate this feature & potentially provide a PR for this._

**Comment by jassmith** [comment]
I like extending copyData everywhere, thinking about implications

**Comment by jassmith** [comment]
Done
