### ISSUE TITLE
IndexSizeError with range cell when the cell space is not enough

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#594]
The range cell throws an `IndexSizeError` if the column doesn't provide enough space to render the range bar:

```
IndexSizeError: Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-0.43998) is negative.
```

https://user-images.githubusercontent.com/2852129/211860777-8939bacb-f805-4844-bdf2-cddbda112ab3.mov

![image](https://user-images.githubusercontent.com/2852129/211859980-71b9f7bf-70f6-47c3-b89d-6bb5def12af0.png)

**Comment by jassmith** [comment]
Fixed in main
