### ISSUE TITLE
Expose additional configurations for NumberCell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#595]
The number cell uses [NumericFormat form react-number-format](https://s-yadav.github.io/react-number-format/docs/numeric_format) for the input element. `NumericFormat` provides some additional configurations to limit the user input. Especially `decimalScale`  and `allowNegative` would be very useful to expose as part of the [`NumberCell`](https://github.com/glideapps/glide-data-grid/blob/77ee5dee0847dde2d078f337f8da9c61cb0ded43/packages/core/src/data-grid/data-grid-types.ts#L437) properties. 

_I might have some time at the end of the month to investigate this feature & potentially provide a PR for this._

**Comment by jassmith** [comment]
Done. Renamed `decimalScale` to `fixedDecimals` to more accurately match the standard JS API naming of `Number.toFixed`
