### ISSUE TITLE
Issues with copy-to-clipboard for BubbleCell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#596]
Bubble cells currently has a couple of issues with the copy-to-clipboard behavior: 

1. The value needs to be escaped [here](https://github.com/glideapps/glide-data-grid/blob/8fee367eae33b1937207216214a319049c64183f/packages/core/src/data-editor/data-editor-fns.ts#L207) in case it contains a comma. Otherwise, you won't be able to distinguish between a list item and a value containing a comma
2. If `data` is an empty array you get the following error:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/2852129/211872167-117948c2-ad26-47d7-840e-c52090fc7ef5.png">

3. If `data` is `null` you would get an: 
```
TypeError: Cannot read properties of null
```

_I might have some time at the end of the month to investigate this feature & potentially provide a PR for this._

**Comment by jassmith** [comment]
Will fix 1 and 2, 3 is not a valid usage of BubbleCell. The Data is not allowed to be null, it can be an empty array

**Comment by jassmith** [comment]
Fixed in main
