### ISSUE TITLE
Improved error messages for missing kind

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#598]
One of my coworkers encountered this error yesterday and was unsure how to proceed

<img width="466" alt="image-7" src="https://user-images.githubusercontent.com/94077014/212386501-bc6fba3c-9dac-460d-b363-bcf1ee621688.png">

It looks like this is because of the `assertNever(cell)` at the end of `isReadWriteCell()`

https://github.com/glideapps/glide-data-grid/blob/77ee5dee0847dde2d078f337f8da9c61cb0ded43/packages/core/src/data-grid/data-grid-types.ts#L365-L379

and there's a similar `default: assertNever(target)` in `formatCell()`

https://github.com/glideapps/glide-data-grid/blob/77ee5dee0847dde2d078f337f8da9c61cb0ded43/packages/core/src/data-editor/data-editor-fns.ts#L237-L264

I think it might be good to have some sort of `cell.kind != null` check that throws a more descriptive error about the kind being missing or otherwise unrecognized

**Comment by jassmith** [comment]
Im VERY curious how your co-worker encountered that error without first getting a build-time error.

**Comment by jassmith** [comment]
to add some further context. That error almost certainly means you lied to the type system somewhere.

**Comment by pzcfg** [comment]
Ah in our case we were refactoring our data api and the field got left off. So the type system definitely got lied to, but I still think it could help to have more descriptive errors where possible.

**Comment by jassmith** [comment]
Error message is improved in main.
