### ISSUE TITLE
Adding custom styles on top of existing cells without drawing a brand new custom cell?

### ISSUE THREAD

**Issue by NicholasEwing** [glideapps/glide-data-grid#599]
Hi there,

I'd love to achieve this Google Sheets-like effect when another user is highlighting / editing a cell, it allows all other clients can see this in real-time.

I have no problem implementing the `WebSocket` logic itself, but I'd love to know if there's a way to render custom styles on top of existing cells and keeping their functionality - WITHOUT rendering a brand new custom cell.

I simply want to wrap some kind of border effect around specific cells based on `WebSocket` `broadcast` events.

Since `DataGrid` is built on top of HTML Canvas - is there an elegant solution for this, or will I need to rebuild every single cell type that I want that feature on from scratch (including each `GridCellKind`'s functionality)?

My needs are somewhere between "draw new cell" and "use existing cell", so this is a unique use case.

I simply need pointing in the right direction, if I find a good solution I'd love to submit a PR to make this feature easily accessible for others!

**Example:**
![image](https://user-images.githubusercontent.com/24522500/212488975-54a37b0e-49ba-4630-a0f9-ec48c001e9a7.png)

**Comment by jassmith** [comment]
You want to use `GridSelection.current.rangeStack`

**Comment by NicholasEwing** [comment]
> You want to use `GridSelection.current.rangeStack`

Thanks, what's the best way to get this info? It's not clear in the documentation which handler or function I can use to get that value.

If I add a function to `onGridSelectionChange`, it'll simply overwrite the default highlighting behavior which prevents me from ever getting the `rangeStack`.

**Comment by jassmith** [comment]
you can respond to `onGridSelectionChange` and then save its output but modify the `rangeStack` to whatever you want it to be.
