### ISSUE TITLE
Storybook stuck at "loading source..." for `HighlightCells` example

### ISSUE THREAD

**Issue by NicholasEwing** [glideapps/glide-data-grid#600]
Simply visit the [Storybook link for the `HighlightCells` example](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--highlight-cells) and you'll see the example code stuck on `loading source...`.

I noticed this while doing research for my previous issue. 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/24522500/212491396-e540b7f0-295d-4c49-a8db-48e573653ba7.png">

**Comment by jassmith** [comment]
Huh, weird.

**Comment by jassmith** [comment]
Figured it out, turns out it was just the storybook not being about to parse `import { type Foo, Bar } from baz;`  style imports.
