### ISSUE TITLE
Error on last row "Enter"

### ISSUE THREAD

**Issue by mddanishyusuf** [glideapps/glide-data-grid#601]
Hi, 

I'm having this issue that there is no row and I click Enter it's not moving to `trailingRowOptions` button `New row...` & giving error.

Here is the code https://codesandbox.io/s/vibrant-fire-6mi33e?file=/src/App.js

Thanks.

**Comment by jassmith** [comment]
Repro confirmed, writing test case now.

**Comment by jassmith** [comment]
This will be fixed in the next point release.

**Comment by mddanishyusuf** [comment]
My bad, I fixed the issue. there was some error in my code. Thanks
