### ISSUE TITLE
Ghost selection

### ISSUE THREAD

**Issue by jerebtw** [glideapps/glide-data-grid#602]
If I have a grid cell selected and the data grid is refreshed (which makes the list smaller), selection stays on the old cell that is now empty. 
(The double-click editor is deactivated)

![image](https://user-images.githubusercontent.com/49494752/212688296-3517e35a-569d-43bb-a9b8-e626c897be4a.png)

**Comment by jassmith** [comment]
Are you setting the gridSelection manually by chance?

**Comment by jassmith** [comment]
This is now fixed in main

**Comment by jerebtw** [comment]
Thanks
