### ISSUE TITLE
Last column is not selectable with latest beta

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#603]
I just tried the latest beta (`5.2.2-beta1`). If row markers are activated, the last column in the table isn't selectable anymore:

https://user-images.githubusercontent.com/2852129/212783646-c35e1541-bcee-434f-bccb-6e1e05cc5bb4.mov

https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--add-data

**Comment by jassmith** [comment]
Fixed thanks
