### ISSUE TITLE
Product using

### ISSUE THREAD

**Issue by AndreewMelnik** [glideapps/glide-data-grid#604]
Jason, good day! 

i really like your product and especially - https://glideapps.github.io/glide-data-grid 

I need a paid consultation for using your product and ready to pay for Zoom + for using your solution on every month basis, we want to use your solutions - GlideApps and Data Grid 

Are you free for a 15 min Zoom call today or the nearest time (i'll be happy to compensate your time for Zoom also) ?

**Comment by jassmith** [comment]
We have [experts](https://www.glideapps.com/experts) you can book for Glide Apps and I only do consultations for Glide Data Grid to help people integrate it into their software. That is free, however. Show me what you are trying to do, I am happy to help. If you are under NDA or can't post publicly, send me more details at jason@heyglide.com and we can discuss a potential zoom based onboarding there.

**Comment by AndreewMelnik** [comment]
Jason, thanks for your reply!
I sent you all the details at jason@heyglide.com.

**Comment by jassmith** [comment]
I didn't receive any follow up.

**Comment by AndreewMelnik** [comment]
I duplicated my message again, probably got into spam.
Or i can write you in Linkedin maybe.

**Comment by jassmith** [comment]
Found it :)
