### ISSUE TITLE
Unexpected scrolling and resizing on mouse move with latest beta

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#607]
I'm not sure what exactly happens, but with the latest beta (5.2.2-beta1) I'm getting strange/unexpected scrolling and resizing effects by just moving the mouse. This is somehow correlated with the scroll handle usage and the column resizing feature.

https://user-images.githubusercontent.com/2852129/213314747-2cc57bfb-641f-4cad-a4ac-20cbd568055b.mov

https://user-images.githubusercontent.com/2852129/213314852-6edd9a50-ebb6-4953-abab-9d7b5c79829e.mov

**Comment by jassmith** [comment]
this is unique to 5.2.2-beta1? I can't think of any reason offhand it would be...

**Comment by LukasMasuch** [comment]
Yep, if I downgrade to `5.2.1` without changing anything implementation related, I'm not getting these unexpected movements. Btw. this only appears to happen if the rowMarkers row is activated. Maybe it is somehow correlated with the issue from: https://github.com/glideapps/glide-data-grid/issues/603

**Comment by LukasMasuch** [comment]
Here is the same table/implementation with the only change being the different glide version. 

`5.2.1`:

https://user-images.githubusercontent.com/2852129/213502301-391f85ca-f54a-426e-8d6f-a2a6d1ba2514.mov


`5.2.2-beta1` (issue can be reproduced reliably with this version):

https://user-images.githubusercontent.com/2852129/213500033-bf2eaca4-9ad4-4039-8d34-be1e80077d66.mov

Maybe there are even two unrelated issues: 
1) the end of resizing is not correctly triggered (maybe related to [this](https://github.com/glideapps/glide-data-grid/commit/77ee5dee0847dde2d078f337f8da9c61cb0ded43)?)
2) The table somehow is auto-scrolled just by moving the mouse... the only commit that seems to be related to anything with scrolling is [this one ](https://github.com/glideapps/glide-data-grid/commit/9e0d3ce76235649fceb3a7706be13d821adfab1a). But it does not really look like it could cause this issue

**Comment by LukasMasuch** [comment]
This commit also looks suspicious for the unexpected scrolling via mouse movements: https://github.com/glideapps/glide-data-grid/commit/0cd2704ff812a7d1eb20de860dc6008eb9731486 or maybe [this](https://github.com/glideapps/glide-data-grid/blame/f3bac4925a93f7e7083c11e4d816a94428d09189/packages/core/src/data-editor/data-editor.tsx#L2223) line is adding some unexpected issues.

**Comment by LukasMasuch** [comment]
One more video on the mouse scrolling issue:
 
It's triggered by clicking on any of the scrollbars and moving the mouse. This is independent of browsers (Chrome & Firefox).

https://user-images.githubusercontent.com/2852129/213516677-ce0a40ab-8099-4015-9abd-cf6d600f0382.mov

Sometimes a cell gets selected which is causing a drag-like multi-cell selection:

https://user-images.githubusercontent.com/2852129/213517701-5ad5776d-86ab-48e9-9447-ff27764dfe15.mov

**Comment by jassmith** [comment]
Okay I think I found a fix. I was too ambitious before.
