### ISSUE TITLE
Assertion failed error when using fillHandle

### ISSUE THREAD

**Issue by rakutek** [glideapps/glide-data-grid#608]
Hi 

Using fillHandle={true} and setting the number of rows to 0 after clicking on a cell seems to cause an Assertion failed error

i have prepared a sample where the error occurs with minimal code with [codesanbox](https://codesandbox.io/s/modest-morning-gk8dsn?file=/src/App.js)

If fillHandle is set to false or rows is set to non-zero, no error will occur.

This is an error i noticed when i implemented own Filter function.

**Comment by jassmith** [comment]
Thanks will fix

**Comment by jassmith** [comment]
This is already fixed in 5.2.2
