### ISSUE TITLE
Edits fail to save when touching outside active cell on touch screen

### ISSUE THREAD

**Issue by bjgrosse** [glideapps/glide-data-grid#609]
Can reproduce this simply using the chrome device simulator as shown in the gif below.

Double-tap a cell to edit, change the value, tap outside the cell... the changes are lost. With a mouse, clicking outside the edited cell saves the changes. 

![JLpuela0nb](https://user-images.githubusercontent.com/14151299/213551187-0887173f-9b41-4e27-a371-6bc3a5811a23.gif)

**Comment by jassmith** [comment]
Fixed in 5.2.2
