### ISSUE TITLE
Allow override of keyboard navigation events

### ISSUE THREAD

**Issue by hyusetiawan** [glideapps/glide-data-grid#610]
Is it possible to override the default keyboard behavior? Specifically, after hitting [Return] key the focus goes to the next row, I would really like it to go to the next column instead.

Thank you!

**Comment by jassmith** [comment]
Not currently, sorry. That is on my roadmap.

**Comment by timobetina** [comment]
Firstly, thank you for this awesome project!
And I would like to bump this up. In my project we have global hotkeys which are in conflict with some of the default keybindings in glide-data-grid. Specifically Ctrl+left/right arrows and Shift+left/right arrows.

**Comment by jassmith** [comment]
This is fixed by #831

**Comment by jassmith** [comment]
Fixed in 6.0.0

**Comment by iamrakhmatov** [comment]
is there any update on this front @jassmith?
