### ISSUE TITLE
[bug] date picker cell is not correctly formatted

### ISSUE THREAD

**Issue by hyusetiawan** [glideapps/glide-data-grid#611]
the form for date grid cell converts date to iso string, but it should be substring if not, it will throw the following error
```does not conform to the required format. The format is "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS```

so this line:
https://github.com/glideapps/glide-data-grid/blob/main/packages/cells/src/cells/date-picker-cell.tsx#L28
needs to be ```val = date.toISOString().substring(0, 16)```

**Comment by jassmith** [comment]
shouldn't it be .substring(0, 23)?

**Comment by jassmith** [comment]
Yeah testing confirms that if you pass a Date that evaluates the seconds to :00.000 the picker wont show em. So this provides optimal flexibility.
