### ISSUE TITLE
Best way to do high frequency inserts

### ISSUE THREAD

**Issue by camposfyi** [glideapps/glide-data-grid#618]
I need to insert anywhere from 10-1000 rows every 100ms. What's the best to do this while not degrading performance?

It seems like all rows need to be redrawn after each update. The docs recommend to memoize getCellContent, but if my data is changing every 100ms it actually needs to see the new data, so memoization seems redundant. 

I looked through the storybook examples with millions of rows, but it seems like all rows need to be available initially.

**Comment by jassmith** [comment]
just increment the rows number and make sure the getCellContent callback identity doesn't change. Addding that many rows 10 times a second is no problem.

**Comment by jassmith** [comment]
are you top posting or bottom posting the rows?

**Comment by camposfyi** [comment]
Thanks I'll give that a try. I'm inserting at the bottom of the grid.

**Comment by camposfyi** [comment]
There's one thing I don't quite understand. If we need to wrap getCellContent is useCallback so that it doesn't change
```
    const getData = useCallback(([col, row], isX) => {
        const person = persons[row];
        if (col === 0) {
            return {
                kind: GridCellKind.Text,
                data: person.firstName,
                allowOverlay: false,
                displayData: person.firstName,
            };
        } else if (col === 1) {
            return {
                kind: GridCellKind.Text,
                data: person.lastName,
                allowOverlay: false,
                displayData: person.lastName,
            };
        } else {
            throw new Error();
        }
    }, []);
```

but getData is using my property `persons` as a data source, and since `persons` is changing every 100ms as new persons are being added, this function always sees an empty array which is what `persons` was when the function was first defined. And if I add `persons` to the dependency array, the function changes all the time.

**Comment by jassmith** [comment]
```tsx
    const personsRef = React.useRef(persons);

    const getData = useCallback(([col, row], isX) => {
        const person = personsRef.current[row];
        if (col === 0) {
            return {
                kind: GridCellKind.Text,
                data: person.firstName,
                allowOverlay: false,
                displayData: person.firstName,
            };
        } else if (col === 1) {
            return {
                kind: GridCellKind.Text,
                data: person.lastName,
                allowOverlay: false,
                displayData: person.lastName,
            };
        } else {
            throw new Error();
        }
    }, []);
```

**Comment by camposfyi** [comment]
Thanks, that worked. It seems like a parent component of the grid still needs to re-render for the grid to update, but that's a react thing. Thanks, this grid is blazing fast compared to the ag-grid which is what I'm trying to replace due to terrible performance with high frequency updates.

**Comment by jassmith** [comment]
That is what lead me to build it in the first place :) Well that and ag-grid's accessibility story is "you can have accessibility or scrolling performance but not both"
