### ISSUE TITLE
Custom Header Menu icon

### ISSUE THREAD

**Issue by homanp** [glideapps/glide-data-grid#620]
Hi, 

Is there anyway to set a custom header menu `icon` and always have it visible instead of visible `onHover`?

Something like this: 

<img width="802" alt="Screenshot 2023-01-27 at 10 43 38" src="https://user-images.githubusercontent.com/2464556/215055973-5f2dea92-c7aa-4d80-8a38-f3c4ce80f789.png">

The implementation above uses a `Portal` but that doesn't work well with the horizontal scrolling etc.

Would be nice if there was an API for this. would that be possible to add?

**Comment by jassmith** [comment]
lemme see what I can do. Good idea.

**Comment by homanp** [comment]
> lemme see what I can do. Good idea.

Amazing!

**Comment by homanp** [comment]
@jassmith I believe we can close this since the `drawHeader` method already has an API for this.
