### ISSUE TITLE
Bug on getData function after removing column from the columns array

### ISSUE THREAD

**Issue by anovazzi1** [glideapps/glide-data-grid#622]
Ithink I found a bug on getData callbackFunction:
here is my piece of code: 
`const getData = useCallback(`
`([col, row]: Item): GridCell => {`
 `let columnType;`
 `let actualColumn;`
 `    try {`
`        actualColumn = columns[col];`
`        columnType = actualColumn.dataType;`
`      } catch (error) {`
`        console.log(error);`
`        console.log(columnType);`
`        console.log(columns);`
`        console.log(actualColumn);`
`        console.log(col);`
`      }`
i get this console log when i trigger this function:
`  function hideColumn(id: string) {`
`    setColumns((columns) => {`
`      const newColumns = columns.filter((col) => col.id !== id);`
`      return newColumns;`
`    });`
`  }`
![image](https://user-images.githubusercontent.com/70824914/215173299-7de007c6-2104-4e30-8f3d-226c61d318b6.png)

This is my DataEditor component:
`<DataEditor
        width={"100%"}
        customRenderers={[SparkRender, renderer, SpinnerRender]}
        height={height ?? undefined}
        onCellEdited={onCellEdited}
        onDelete={onDelete}
        onColumnResize={onColumnResize}
        showSearch={showSearch}
        getCellsForSelection={true}
        onSearchClose={() => setShowSearch(false)}
        gridSelection={selection}
        onColumnMoved={onColMoved}
        onGridSelectionChange={setSelection}
        getCellContent={getData}
        smoothScrollY={true}
        smoothScrollX={true}
        onHeaderMenuClick={onHeaderMenuCLick}
        rightElement={
          <TableAddColumnButton width={"w-48"}>
            <button
              className="hover:bg-[#c9c9c9] ease-in duration-200 h-9 text-lg"
              onClick={() => alert("add column trigger")}
            >
              +
            </button>
          </TableAddColumnButton>
        }
        rightElementProps={{ fill: false, sticky: false }}
        columns={columns}
        rows={data.length}
        rowMarkers="both"
        isDraggable={false}
        verticalBorder={false}
      ></DataEditor>`

**Comment by jassmith** [comment]
Did you figure out your issue?
