### ISSUE TITLE
problems with padding inside portal

### ISSUE THREAD

**Issue by anovazzi1** [glideapps/glide-data-grid#624]
### Discussed in https://github.com/glideapps/glide-data-grid/discussions/623

<div type='discussions-op-text'>

<sup>Originally posted by **anovazzi1** January 30, 2023</sup>
![image](https://user-images.githubusercontent.com/70824914/215594512-a607bbad-2124-4bff-b8be-50dda5520aa9.png)
my text cell is getting this weird padding, have anyone else faced this before?
it occurs after i set row height dynamically to each row based on i's content:
        `rowHeight={(index) => {`
          `let height = 40;`
          `columns.map((col, idxCol) => {`
            `if(col.dataType === dataTypes.TEXT) {`
              `let newHeight = 10 + measureTextHeight(data[index][col.title].toString(), col.width-5, 14);`
              `height = (height < newHeight ? newHeight : height);`
            `}`
            `return height;`
        `})`
        `return height;`
        `}}` </div>

**Comment by jassmith** [comment]
Note for future Jason. This is because with wrapped text we should assume that we shouldn't attempt to align the text input with the display text. The fix here is just to set the padding to the nominal value.

**Comment by anovazzi1** [comment]
is there any workaround to this? by now?

**Comment by jassmith** [comment]
oh I added a fix in 5.2.2, just wait for me to roll the next beta.

**Comment by jassmith** [comment]
Beta is rolling out now

**Comment by anovazzi1** [comment]
thanks a lot
