### ISSUE TITLE
How to write tests of code using the grid component?

### ISSUE THREAD

**Issue by larsthorup** [glideapps/glide-data-grid#625]
Thank you for a great - and fast! - grid component.

I have been trying, and failing, to write tests for our code that uses the DataEditor component. I was hoping to use the accessibility tree to query the structure of the generated grid, so for example doing something like: `getByRole('columnheader')` and `getByTestId('glide-cell-0-0')`.

I have been looking at the tests here:

https://github.com/glideapps/glide-data-grid/blob/main/packages/core/test/data-editor.test.tsx

and when extending one of them to output the DOM, I can see that the accessibility tree is rendered just fine:

![image](https://user-images.githubusercontent.com/1202959/215820136-8a38dc4a-a8b3-4a1e-b9e7-12803e5d0cae.png)

Thoses tests does quite a bit of magic mocking with several DOM element attributes (width, height, clientWidth, clientHeight, getBoundingClientRect, offsetWidth, scrollTo, scrollBy), which I would like to avoid if possible.

Here is a simple reproduction repo where the output doesn't contain neither the `<canvas>` element, nor the accessibility tree:

https://github.com/larsthorup/glide-data-grid-testing

What am I missing?

![image](https://user-images.githubusercontent.com/1202959/215820976-0a6b6b7e-c188-41be-84e4-7eb2862b9de5.png)

**Comment by jassmith** [comment]
If you don't mock out the basic sizes, it thinks it is a zero sized canvas and thus displays nothing and outputs nothing.

**Comment by rferreira98** [comment]
@jassmith  I'm also having this issue, using jest. What should be done to fix it?
