### ISSUE TITLE
How to apply an animation to the column icon?

### ISSUE THREAD

**Issue by lucaseduoli** [glideapps/glide-data-grid#626]
Hello, I'm looking to replace the column header icon with a spinner when my data is loading. I want to do this in the header because I don't want to use a spinner cell, because there is previous data and I want the user to keep looking at it until the new data is there.

What I've already done is create a custom header icon, like this:
```const headerIcons = useMemo<SpriteMap>(() => {
    return {
      spinner: (p) =>
       `<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_P7sC{transform-origin:center;animation:spinner_svv2 .75s infinite linear}@keyframes spinner_svv2{100%{transform:rotate(360deg)}}</style><path d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z" class="spinner_P7sC"/></svg>`,
    };
  }, []);
```

But, when I run the code, the animation does not work. Is there something that I'm missing to make the SVG spin? Or is there an pre-made icon that is a spinner?

![image](https://user-images.githubusercontent.com/62335616/215913460-2b38ceeb-ce14-4403-b211-50d982c03186.png)
The spinner appears like that, and it doesn't move.

**Comment by jassmith** [comment]
At this time you can't, sorry.
