### ISSUE TITLE
copy lines missing last column when using rowMarkers

### ISSUE THREAD

**Issue by luania** [glideapps/glide-data-grid#628]
https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--copy-support

<img width="1053" alt="215932311-0dbb15ec-955e-4fc9-aa68-d1a5b5a217c3" src="https://user-images.githubusercontent.com/5110993/215933068-edbb603b-4da0-4d9b-a7ae-71cee76691c6.png">

**Comment by jassmith** [comment]
1 sec
