### ISSUE TITLE
Header drawing scale messes up at every 100% zoom

### ISSUE THREAD

**Issue by ALMaclaine** [glideapps/glide-data-grid#629]
I can make an example if needed but wanted to get this posted since I found it a week ago.

If you zoom the browser over 100%, header drawing scaling is messed up by a factor of 2 in several dimensions.

Here is my adjustment code:

```ts
const { x, y, width, height } = rect;
  const zoomed = window.devicePixelRatio > 1;
  const zoomFactor = zoomed ? 2 : 1;

  const stateSet = stateHistory.find((state) => state.key === id);
  const isSorted = stateSet !== undefined;
  const sortState = stateSet?.state || SORT_STATES.initial;

  const image = getHeaderSortImage({
    isSorted,
    sortState,
    backgroundColor: headerThemePriority(headerProps),
    fillColor: theme.textHeaderSelected,
    zoomed,
  });

  const pos = positioner({
    containerWidth: width,
    containerHeight: zoomFactor * height,
    itemWidth: image.width,
    itemHeight: image.height,
    position: 'midRight',
    padding: theme.cellHorizontalPadding,
  });

  ctx.putImageData(image, zoomFactor * (pos.x + x), pos.y + y);
```

If `const zoomed = window.devicePixelRatio > 1;` is true, then I have to multiply my container height by 2 and change my draw x position by a factor of 2.

This happens every 100% increase, so when you hit 210%, the factor is off again. I've only compensated for 110-200.

Let me know if you need a demo created.

**Comment by ALMaclaine** [comment]
I think this has to do with mac retina because I get different rendering results depending on which mac version I'm on, but not which chrome version I'm using.

**Comment by jassmith** [comment]
Which mac version? Like which MacOS version?

**Comment by jassmith** [comment]
Oh i think I know what the problem is, will fix.

**Comment by ALMaclaine** [comment]
I'm on two versions of mac.
12.6.2 and 12.2.1

**Comment by jassmith** [comment]
Okay I was wrong. Turns out the problem here is that `putDrawImage` is totally ignorign the transformation matrix of the canvas. This is apparently to spec. Can you not use `drawImage` instead?

**Comment by jassmith** [comment]
Either way, this is not something we can fix, this is the "expected" behavior. If you want to use putImageData you will need to apply the current transform matrix by hand.

**Comment by ALMaclaine** [comment]
@jassmith thanks for the info, I haven't used canvas extensively so I just used the first method I saw.
