### ISSUE TITLE
Custom header menu icon [maybe new feature]

### ISSUE THREAD

**Issue by camposfyi** [glideapps/glide-data-grid#633]
Is there a way to change the down-arrow icon that appears when `hasMenu=true` is set?

I'm adding a custom filter menu to each column and I would like to use a filter icon instead of a dropdown arrow.

I couldn't find anything in the docs besides headerIcon which shows an icon at the beginning of the header.

![image](https://user-images.githubusercontent.com/5265784/216455222-9e341664-dc9d-40d0-8cc4-f7f1fc5f10ca.png)

**Comment by jassmith** [comment]
heh no I will add it as a feature request. You're not the first.

**Comment by camposfyi** [comment]
Thanks. I was able to just draw the header I needed by using the drawHeader function.
