### ISSUE TITLE
Additional configurations for NumberCell

### ISSUE THREAD

**Issue by elloodev** [glideapps/glide-data-grid#634]
The NumberCell uses react-number-format for the input. This library provides some configurations that are very useful when we work with localization. I would like to expose `decimalSeparator` and `thousandSeparator` to add the possibility of customize the decimal separator and use a custom thousands separator or remove it.

**Comment by jjmartinmelero** [comment]
I’m also interested on remove the thousands separator from the editor

**Comment by elloodev** [comment]
Done. Added `thousandSeparator` and `decimalSeparator` properties to number cell.
