### ISSUE TITLE
custom-cell-editing / The above error occurred in the <Editor> component / Invalid hook call

### ISSUE THREAD

**Issue by imranypatel** [glideapps/glide-data-grid#636]
Trying to locally test Dropdown cell editing based on https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cell-editing

Grid with cells rendered appropriately.
However, clicking on a cell to choose value from Dropdown, crashes and produces:

    The above error occurred in the <Editor> component:

    at Editor (http://localhost:3000/static/js/bundle.js:67391:12)
    at div
    at div
    at render (http://localhost:3000/static/js/bundle.js:68194:13)
    ....

"above error" is
        
    Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for 
    one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

Code extracted and changed from https://github.com/glideapps/glide-data-grid/blob/8085cd8e0d04c865ab5963af961b734fb053ded9/packages/cells/src/cell.stories.tsx:
```

import * as React from 'react';
import DataEditor, {
    GridCellKind,
    DataEditorProps
} from "@glideapps/glide-data-grid";

import { useExtraCells, DropdownCell as DropdownRenderer, DropdownCellType } from "@glideapps/glide-data-grid-cells";

import type { DropdownCell } from "@glideapps/glide-data-grid-cells";

import "@glideapps/glide-data-grid/dist/index.css";

const defaultProps: Partial<DataEditorProps> = {
    smoothScrollX: true,
    smoothScrollY: true,
    isDraggable: false,
    rowMarkers: "none",
    width: "100%",
};
export const CustomCellEditing: React.VFC = () => {
    const cellProps = useExtraCells();

    const data = React.useRef<string[]>([]);
   
    return (

        <DataEditor
            {...defaultProps}
            {...cellProps}
            onPaste={true}
            onCellEdited={(cell, newVal) => {
                if (newVal.kind !== GridCellKind.Custom) return;
                if (DropdownRenderer.isMatch(newVal)) {
                    data.current[cell[1]] = newVal.data.value;
                }
            }}
            getCellsForSelection={true}
            getCellContent={cell => {
                const [, row] = cell;
                const val = data.current[row] ?? "A";
                return {
                    kind: GridCellKind.Custom,
                    allowOverlay: true,
                    copyData: val,
                    data: {
                        kind: "dropdown-cell",
                        allowedValues: ["A", "B", "C"],
                        value: val,
                    },
                } as DropdownCellType;
            }}
            columns={[
                {
                    title: "Dropdown",
                    width: 200,
                },
            ]}
            rows={5}
        />

    );
};

export default CustomCellEditing;
```
index.html body last element:

```
<div id="portal" />

```
Config:

```
{
  "name": "xp-ts-mui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@glideapps/glide-data-grid": "^5.2.1",
    "@glideapps/glide-data-grid-cells": "^5.2.1",
    "@mui/icons-material": "^5.10.3",
    "@mui/material": "^5.10.3",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.46",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "lodash": "^4.17.21",
    "marked": "^4.2.12",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-responsive-carousel": "^3.2.23",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.6",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Initial rendering success as:
![image](https://user-images.githubusercontent.com/4316514/217477019-6df2ce0d-8827-4040-923b-3d0597d09a07.png)

Crashes when clicking as:
![image](https://user-images.githubusercontent.com/4316514/217477245-362867ac-36fe-4d9c-9ea7-5f193dedba94.png)

Extracted and tested another from same https://github.com/glideapps/glide-data-grid/blob/8085cd8e0d04c865ab5963af961b734fb053ded9/packages/cells/src/cell.stories.tsx example based on https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cells

All other Custom Cells (e.g. Tag, DatePicker) are working fine with respective editors.

Normal behavior of Tag:
![image](https://user-images.githubusercontent.com/4316514/217992357-0a056ecb-d88e-4020-a904-b7c1a34a365e.png)

and DatePicker:
![image](https://user-images.githubusercontent.com/4316514/217993531-15eaf819-1f8e-48de-a934-ed87e84b0246.png)

Only DropdownCell crashes when clicking for selection.

Any advice please?

**Comment by flash2k2** [comment]
Same problem for me. Trying to use DropdownCell with React and Electron.

**Comment by samuelvernon** [comment]
Same here :-( Any sugestions?

**Comment by jassmith** [comment]
I suspect you have multiple versions of react installed. npm ls react may be insightful
