### ISSUE TITLE
[new feature request] scrollTo function, allow position configuration (top, middle, bottom)

### ISSUE THREAD

**Issue by camposfyi** [glideapps/glide-data-grid#637]
It would be nice to be able to specify where in the grid viewport (top, middle or bottom) we want the grid to scroll to.

i.e. 
scrollTo(col=0, row=1000, position: 'bottom')

I specifically want the cell I'm scrolling to at the bottom of the viewport.. and in other use cases I want it to be in the middle. I could just call this instead 
scrollTo(col=0, row=1000, position: 'middle')

The api interface might need to be different as the grid supports scrolling both vertically and horizontally. In my scenario I just need to scroll vertically.

**Comment by jassmith** [comment]
These are now available.
