### ISSUE TITLE
RowMarker size dependent on row height

### ISSUE THREAD

**Issue by pho7on** [glideapps/glide-data-grid#639]
As a title suggests, Checkbox inside RowMarker columns is dependent on row height. Is there a way to restyle this? maybe even pass custom component as I would ideally like to have my own custom checkbox there?

Here is the example of the issue:

![image](https://user-images.githubusercontent.com/31965678/217855372-ce797866-8a69-4020-bfae-0581e7f6f69f.png)

**Comment by jassmith** [comment]
THis is fixed in 5.2.2, check the beta
