### ISSUE TITLE
Unnecessary horizontal scrollbar when container width is in sub-pixels

### ISSUE THREAD

**Issue by tb-viktor** [glideapps/glide-data-grid#645]
Hi,

When columns are set to stretch and fill the table container using the `grow` property, an unnecessary scrollbar that just scrolls one pixel to the right can appear depending on the screen size. This happens when the width of the container that shows the table ends up having sub-pixel values, e.g. `1283.25px` instead of of a round value.

Demo: ![glide-data-grid-subpixel-horizontal-scrollbar](https://user-images.githubusercontent.com/96176911/219044308-29354103-0510-49f3-b056-50c8253240ad.gif)

On: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--stretch-column-size

This is a problem in responsive layouts, where CSS widths are set with percentages or automatically calculated. Depending on the device, the default view can have these for an empty table state, which looks sloppy.

Is it possible to have this fixed?

Thanks!

**Comment by jassmith** [comment]
Note to future Jason, the inner padder width need only be as big as the minimum column width not the current column width. This is the ultimate cause of this flicker and trivially fixed provided this data gets passed to the scroller form the column sizer.

**Comment by jassmith** [comment]
Fixed in 6.0.0
