### ISSUE TITLE
Disable selectAllRowMarkers

### ISSUE THREAD

**Issue by DusanNikcevic** [glideapps/glide-data-grid#646]
I have been wondering if it is possible to disable `selectAllRowMarkers` functionality, as some of my tables require only one row to be selected

**Comment by SejanasJoshua** [comment]
Just pass the **rowSelect** prop as '**single**'.

```
<DataEditor
      {...cellProps}
      rowSelect='single'
/>
```

**Comment by jassmith** [comment]
Asked and answered, ya love to see it.
