### ISSUE TITLE
Vertical and horizontal borders issues

### ISSUE THREAD

**Issue by anguedev** [glideapps/glide-data-grid#647]
There are some minor visual issues related with borders:

#### Top and bottom borders are cut on first and last rows when highlight regions are configured

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/84323714/220113835-d4bdbae3-27ed-45ff-84f4-3184e2ad2459.png">
<br />
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/84323714/220114417-519f3245-591a-46f2-9e81-054ed413bc38.png">

#### Bottom border is cut on last row when cell is selected

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/84323714/220115400-b3f974d8-edbe-41ff-97ef-099265ecedf5.png">

#### Right border is cut on last column

<img width="495" alt="image" src="https://user-images.githubusercontent.com/84323714/220116190-7b09ae41-ec20-4a45-9a6a-74b1e44e885f.png">

Another issue is when highlighting regions is used in combination with fill down to draw a border on selection, when the new value is applied the border is thinner and if you scroll it appears correctly.

All these issues have been detected on Mac OS Ventura and are replicable on Safari, Chrome and Firefox.

**Comment by jassmith** [comment]
This is fixed in 6.0.0
