### ISSUE TITLE
selectionOutOfBounds bug

### ISSUE THREAD

**Issue by ralake** [glideapps/glide-data-grid#649]
https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L3331

The columns check needs to be updated to something like

```JS
gridSelection.current.cell[0] >= columnsIn.length + rowMarkerOffset
```

Otherwise, when using row markers, the last column cannot be focussed or edited since the grid selection is immediately cleared as it is considered out of bounds. Not a problem when not using row markers...

**Comment by BrianHung** [comment]
Fixed in 5.3.0 release
https://github.com/quicktype/glide-data-grid/pull/758/files#diff-3e4b00d273a625e520929f36335bd67bab65f8c4c042a4a56b580c1fc706e2e0R3362
