### ISSUE TITLE
How can I get selected rows or columns?

### ISSUE THREAD

**Issue by fakob** [glideapps/glide-data-grid#650]
Hi, 
I am trying to add an option to delete multiple columns or rows at the same time and was wondering how I would get the column selection. In the storybook I found `onSelectedColumnsChange`, but it seems to not be supported anymore? I also found `onGridSelectionChange`, but could not figure out how to actually get the info of which columns/rows are selected. It breaks for me, like mentioned in this ticket https://github.com/glideapps/glide-data-grid/issues/515. Unfortunately I do not understand what is meant by
> if you set onGridSelectionChange you should also be passing a gridSelection value.

Any help would be appreciated :-)

<img width="420" alt="Screenshot 2023-02-21 at 21 04 25" src="https://user-images.githubusercontent.com/4619772/220449936-8c8c6be0-8ddf-4a54-a669-20a01d64f298.png">

**Comment by BrianHung** [comment]
`onGridSelectionChange` returns an object with

```
{
  current: {
    cell: [number, number],
    range: { x: number, y: number, width: number, height: number },
    rangeStack: { x: number, y: number, width: number, height: number }
  },
  rows: CompactSelection,
  columns: CompactSelection
}
```

Would dig into source code to be more specific.

**Comment by fakob** [comment]
Ok, thanks. I will have a look.

**Comment by SejanasJoshua** [comment]
//Import CompactSelection
import DataEditor, { CompactSelection } from '@glideapps/glide-data-grid';

//Initialize an initial State
const initialSelection = {
  columns: CompactSelection.empty(),
  rows: CompactSelection.empty(),
};

//create a useState to manage the selection
const [gridSelection, setGridSelection] = React.useState(initialSelection);

//Pass them as props in DataEditor
<DataEditor
            {...cellProps}
            gridSelection={gridSelection}
            onGridSelectionChange={setGridSelection}
/>
