### ISSUE TITLE
Freeze Rows functionality

### ISSUE THREAD

**Issue by trentwatt** [glideapps/glide-data-grid#653]
Hi there, 

I noticed that there is the `freezeColumns` [option](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--freeze-columns). Is there an analogous functionality for rows, or a recommended way to achieve it?

Thanks

**Comment by jeffersonswartz** [comment]
This would be a great feature if implemented.

**Comment by jassmith** [comment]
Some thoughts for future jason. This is actually fairly easy to implement if you just render the freeze columns into the header canvas.

**Comment by jassmith** [comment]
This is planned in https://github.com/glideapps/glide-data-grid/issues/823

Closing this issue to track there.
