### ISSUE TITLE
Prevent editor from closing

### ISSUE THREAD

**Issue by yazmeyaa** [glideapps/glide-data-grid#659]
Hello. 👋
I am using @glideapps-datagrid v5.2.1
I've implemented an _custom editor component_, but I'm running into an issue with the mouse click event listener.

The problem is that when I click on the _table_, the editor automatically closes. At the same time, the `click-outside-ignore` class has been added to the DataEditor and its container.

How can I prevent the editor from closing when the DataEditor itself is clicked?
Or how can I manage the state of the editor? (Opened or closed)

I tried using the code below, but then it becomes impossible to close the editor
```js
useEffect(() => {
         document.addEventListener('mousedown', event => event.stopPropagation())
         return document.removeEventListener('mousedown', event => event.stopPropagation())
     }, [])
```

**Comment by BrianHung** [comment]
I would just use `patch-package` to achieve the behavior you are looking for. 

> The problem is that when I click on the table, the editor automatically closes. 
What table is this?
