### ISSUE TITLE
Error when pasting values ​​into a custom cell of type Dropdown-cell

### ISSUE THREAD

**Issue by gilsonterra** [glideapps/glide-data-grid#660]
When I paste a value for dropdown-cell the app throw this exception:

![Screenshot from 2023-03-07 13-08-45](https://user-images.githubusercontent.com/2127096/223479833-209ee26d-4a9a-4b2a-abcf-2b438a778c71.png)

There is a little problem in `dropdown-cell.tsx` on method `onPaste` should have one `?` after allowedValues to avoid the exception:
```ts
 onPaste: (v, d) => ({
        ...d,
        value: d.allowedValues?.includes(v) ? v : d.value,
    })
```

**Comment by mayneyao** [comment]
same problem, I think I have found the reason. 

The interface is defined as "data" passed into onPaste of custom cells, but "cell" is passed in the implementation. 

I'm not sure which standard should be followed for modification. It looks like we should follow the interface. @jassmith 


https://github.com/glideapps/glide-data-grid/blob/c9e1f3df5d545171ccca2226c0c55e253fb6cc83/packages/core/src/data-editor/data-editor.tsx#L3043-L3062

https://github.com/glideapps/glide-data-grid/blob/c9e1f3df5d545171ccca2226c0c55e253fb6cc83/packages/core/src/data-grid/cells/cell-types.ts#L84-L95

**Comment by LukasMasuch** [comment]
@jassmith This issue is solved by https://github.com/glideapps/glide-data-grid/pull/726 and can be closed or?

**Comment by jassmith** [comment]
Yes I believe so.
