### ISSUE TITLE
Scope css classes

### ISSUE THREAD

**Issue by ALMaclaine** [glideapps/glide-data-grid#662]
These unscoped classes such as `hidden` can conflict with global css styles in the app. While I'd like to remove our global css, I can't yet and this seems like a problem regardless.

![Screen Shot 2023-03-08 at 3 24 20 PM](https://user-images.githubusercontent.com/16461670/223853528-d725e535-33c3-4ead-a48d-814ac8238de0.png)

**Comment by jassmith** [comment]
https://github.com/quicktype/glide-data-grid/pull/760

**Comment by jassmith** [comment]
Fixed in 6.0.0
