### ISSUE TITLE
`fillHandle` for cells in different columns

### ISSUE THREAD

**Issue by homanp** [glideapps/glide-data-grid#667]
Hi there, 

Does anyone know how one could achieve selection of cells in different columns using the `fillHandle` prop?

Seem to only working with cells in a specific column right now. 

This would be the expected behaviour:

<img width="346" alt="Screenshot 2023-03-14 at 10 05 49" src="https://user-images.githubusercontent.com/2464556/224950689-d805a561-e00f-4ce9-ac29-b5f99a6d1ed5.png">

**Comment by BrianHung** [comment]
Think further implementation of fillHandle will be needed; don't think the original purpose of glide was for spreadsheets although it works pretty well for it. Would love a fillHandle that had `"none" | "row" | "column" | "both"`, and more customizable fillDown fillRight behavior.

**Comment by jassmith** [comment]
Honestly as I recall the problem here is mostly I sat down to look at how to do the drawing of this efficiently and then started crying.

**Comment by BrianHung** [comment]
Wah, it feels pretty similar to highlight regions (which seem performant).

**Comment by jassmith** [comment]
It's not that it can't be done, but it's tied to the drawing of the focus ring right now and these would need to be decoupled and tracked independently.

**Comment by jassmith** [comment]
This is done
