### ISSUE TITLE
Editable Text Cell with Single Click instead of Double Clicking

### ISSUE THREAD

**Issue by codeBelt** [glideapps/glide-data-grid#668]
1. Is it possible to make a text cell editable with one click? Currently you have to double click to edit the value.

2. I am having a hard time figure out how to get to text cell editing overlay working in my Next.js app. I searched the web for a working example which is `a)` below. I took `a)` and put it in my Next.js and it didn't work so I created an example `b)` with the `a)` code and it too doesn't work. Can you help me figure out what the difference is and why `b)` is not working?

`a)` [Someone else code I forked that works](https://codesandbox.io/s/goofy-feather-h270kf?file=/src/App.tsx)
`b)` [Same code as `a)` but doesn't work 😞 ](https://codesandbox.io/p/sandbox/glide-data-grid-react-vite-hfpj1v?file=%2Fsrc%2Fcomponents%2Fui-table%2FUiTable.tsx)

**Comment by jassmith** [comment]
1) I will look into it, pretty sure this is doable. If not it wont be hard to make this doable without issue.

2) You forgot to add a <div id="portal" /> to your html. At least for now GDG looks for a portal target for the overlay editors.

**Comment by jassmith** [comment]
This is fixed in 6.0.0 entirely now. You can override the cellActivationBehavior.
