### ISSUE TITLE
Right clicking rightElement triggers onCellContextMenu

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#669]
If you have a `onCellContextMenu` callback and right click in the `rightElement`, it will still trigger `onCellContextMenu` for the underlying cell. It seems like the `rightElement` should (at least by default) capture this event for its own use and not trigger `onCellContextMenu`.

https://user-images.githubusercontent.com/94077014/225767933-a832dd59-104d-4ae0-8980-63b576c6356e.mp4

**Comment by dilipthakkar** [comment]
Hi @jassmith 
I want to fix this bug.
Could you please assign it to me.

Thanks

**Comment by jassmith** [comment]
Assigned, happy hunting.

**Comment by jassmith** [comment]
Fixed in 6.0.0
