### ISSUE TITLE
onCellActivated event fires for single clicks even if cell is the same as previously clicked

### ISSUE THREAD

**Issue by ScarletJack** [glideapps/glide-data-grid#687]
**Issue:**

The onCellActivated event is triggered when a cell is clicked, even if it's the same cell as previously clicked, without considering any delay between clicks. This leads to confusion, as users may expect a double-click event instead of single-click behavior.

**Possible Cause:** 

`data-editor.tsx` contains the following code in the `onMouseUp` callback: 

```tsx
if (
  !isPrevented.current &&
  mouse?.previousSelection?.current?.cell !== undefined &&
  gridSelection.current !== undefined
) {
  const [selectedCol, selectedRow] = gridSelection.current.cell;
  const [prevCol, prevRow] = mouse.previousSelection.current.cell;
  if (col === selectedCol && col === prevCol && row === selectedRow && row === prevRow) {
      onCellActivated?.([col - rowMarkerOffset, row]);
      reselect(a.bounds, false);
      return true;
  }
}
```

**Suggested Solution:**

It would be helpful to either:

1. Pass additional arguments to the onCellActivated event as a second parameter, indicating how the event was triggered (e.g., with mouse event information).
2. Implement an extra check in the condition for handling double-click events specifically.

**Comment by jassmith** [comment]
This is now fixed in 6.0.0
