### ISSUE TITLE
How to auto resize columns when content changes

### ISSUE THREAD

**Issue by tomfrew** [glideapps/glide-data-grid#689]
When changing the data of a grid or when data is added asynchronously once the component is mounted, sometimes the columns adjust width to fit content but sometimes do not. 

What's the best way to always resize columns when the data changes?

I've tried using the `remeasureColumns` from current main 
```
ref.current?.remeasureColumns(
      CompactSelection.fromSingleSelection([0, columns.length])
    );
```

But triggered that when the data changes causes the columns to flash and jump around (I assume a race condition with something internal also remeasuring) 

Have also seen incorrect auto widths on first mount once the `onColumnResize` prop is added. Some columns wrap all the data but some columns don't expand to fit all the content. 

e.g. in this screenshot description column only fits the column title but cuts off content but project_id column expands to fit the content. Some rows of ID are longer wider than the column. All these columns are string columns with no width value set
![Screenshot 2023-04-14 at 3 45 35 pm](https://user-images.githubusercontent.com/845195/232076963-b8d75394-8f6d-47e3-9dbf-4e08410620a4.png)

When the component mounts and `onColumnResize` function get's initially called it has the width based on the shorter data but when `remeasureColumns()` is called later then it takes into account all cells.

**Comment by jassmith** [comment]
A reproduction case would be needed.
