### ISSUE TITLE
can I get row data by rowMarkers ? 

### ISSUE THREAD

**Issue by ParkAward** [glideapps/glide-data-grid#701]
i'm wondering to know to use RowMaker's Event 

help.. TT

<img width="1173" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/101157141/089ba608-c44b-4228-a5cf-296d84f3e0c4">

**Comment by fabianTMC** [comment]
+1

**Comment by fabianTMC** [comment]
Use the `onCellClicked` event. If the column number is `-1`, it indicates that row was selected.

**Comment by ParkAward** [comment]
> Use the `onCellClicked` event. If the column number is `-1`, it indicates that row was selected.

thank you for telling me. I'll try
