### ISSUE TITLE
Allow to specify label and value in items for custom dropdown-cell

### ISSUE THREAD

**Issue by msmshazan** [glideapps/glide-data-grid#704]
Looking at the code it has the facility but glide data grid only accepts a single string.
https://github.com/glideapps/glide-data-grid/blob/main/packages/cells/src/cells/dropdown-cell.tsx#L63

**Comment by LukasMasuch** [comment]
This is implemented in https://github.com/glideapps/glide-data-grid/pull/830 and will be released with 6.0.0

**Comment by msmshazan** [comment]
Thank you. Appreciate 👍
