### ISSUE TITLE
Custom color for gridSelection

### ISSUE THREAD

**Issue by DusanNikcevic** [glideapps/glide-data-grid#707]
As the title suggests I would like to assign custom color to selected/highlighted rows inside of the table, but I can't seem to find any property that would help me achieve this functionality. Do you think that would work?

**Comment by camposfyi** [comment]
It's in the docs:
`highlightRegions={highlights}`

sample:
```
    const highlights = useMemo(() => {
        if (!gridSelection.current) {
            return;
        }

        const selectedIndex = gridSelection?.current?.range?.y;
        return [{
            color: 'rgba(0,0,0,0.2)',
            style: 'solid',
            range: {x: 0, y: selectedIndex, width: columns.length, height: 1},
        }];
    }, [gridSelection, columns.length]);
```

**Comment by DusanNikcevic** [comment]
not sure how I missed this. Thanks @camposfyi !
