### ISSUE TITLE
Focus escapes data grid with caret browsing

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#725]
I accidentally turned on caret browsing in Chrome with F7, and noticed that arrow keys on the boundaries of the data grid will escape focus to a nearby in dom tree element. Think we should use a focus-trap such as https://github.com/focus-trap/focus-trap-react to prevent this, and maintain focus in the grid. Important part would also be implementing an escape hatch for accessibility: https://codemirror.net/examples/tab/

**Comment by jassmith** [comment]
At this time we are not planning to focus trap. I'd be open to a PR to do it conditionally however.

**Comment by jassmith** [comment]
`focusTrap` now available in 6.0.0
