### ISSUE TITLE
Is there a way to add a custom footer at column level with on click functionality and custom css?

### ISSUE THREAD

**Issue by SiddarthaIO** [glideapps/glide-data-grid#729]
I have a use case where I want to display the aggregate value of each column at the bottom as a footer with some custom styling similar to the below picture and want to perform some action on click of it. Is it possible?

<img width="145" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/35519342/0ff4bd1b-6abc-4b18-af13-41aa3aff5cfa">

I was able to achieve it partially with `trailingRowOptions` at the column level. But not able to align the content and there is no column level `onClick` functionality, we only have `onRowAppended` at `DataEditor` level.

<img width="143" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/35519342/02524a4a-443b-43f6-8c94-97bd4925f972">

storybook is not loading for `Trailing row options`

<img width="1673" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/35519342/29413a65-5dff-4549-b6dd-8df1f5354bb1">

**Comment by SiddarthaIO** [comment]
Please let us know if there is an alternative solution for this.

**Comment by dragthelake** [comment]
I'm also interested in this for the same use case (calculating totals for the column)

**Comment by jassmith** [comment]
nothing I can think of right now.

**Comment by LukasMasuch** [comment]
This feature would also be quite useful for us to show column metrics. Maybe in addition to the trailing row, we could allow to freeze the last X rows via: 

```typescript
interface DataEditorProps {
    // ...other props
    readonly freezeTrailingRows: number;
}
```

This would allow the user to use any of the available cell types and functionalities.

**Comment by jassmith** [comment]
Working branch: https://github.com/glideapps/glide-data-grid/tree/jason/freeze-trailing-rows

**Comment by jassmith** [comment]
It works minus some issues with selection rects. There are probably other issues with scrolling, not sure.

**Comment by saharaying** [comment]
How can I prevent drawing a row marker for the frozen trailing row?

**Comment by jassmith** [comment]
just curious, why? I will find a way to add a control for this soon. There are other reasons this is needed as well, but I want to collect the use case :)

**Comment by jassmith** [comment]
Freeze trailing rows are impelemented. Adding a footer component that is drawn with DOM under the grid can be done externally and does not require first party support.
