### ISSUE TITLE
Bug: Links rendered outside the boundaries of the grid are no longer clickable

### ISSUE THREAD

**Issue by bartbroere** [glideapps/glide-data-grid#757]
I am using the markdown cell type to put multiple links in a cell. This works quite nicely most of the time. 

However If I put the markdown with links in the rightmost column however, double clicking will open the rendered markdown, but if this view is rendered slightly outside the boundaries of the table containing the cell, the links no longer work when I click them.

I'll try to write an example that can be used to reproduce this and post that here as well.

**Comment by bartbroere** [comment]
I have been trying for a bit, but I haven't yet been able to isolate this issue in a storybook entry. Perhaps the behaviour varies across browsers or depends on how you integrate the data grid in your code. I'll continue trying to make a reproducible example. Unfortunately I can't share the project it originally occurred in.

**Comment by bartbroere** [comment]
My theory now is that `overflow: hidden` in a `div` that contains the `DataEditor` might be causing the issue. When you double click a cell to open the rendered, the part of the link that renders outside the `div` that has `overflow: hidden` is not clickable. Perhaps this is not something that can be fixed in this project. but we could consider documenting it once it's confirmed.

**Comment by bartbroere** [comment]
For now I'll end my debugging session. I have found that unsetting the CSS attributes `contain: strict`, `width` and `height` on the `canvas` element of the data grid also influences the "clickability". Of course this is not the fix yet, as it might introduce other problems, but it will probably help narrowing down the issue.

If anyone has any thoughts on what might be causing this, please let me know here.

**Comment by jassmith** [comment]
Thank you for the deeper insight. I think the contain strict I added there was purely for performance reasons. It shouldn't matter if we remove it too much.

**Comment by jassmith** [comment]
This should be fixed in 6.0.0
