### ISSUE TITLE
Storybook is 404

### ISSUE THREAD

**Issue by webdevsyd** [glideapps/glide-data-grid#774]
Is this still the link for storybook? https://quicktype.github.io/glide-data-grid it's 404 error page currently.

**Comment by SourceCipher** [comment]
Yeah yesterday I was looking at it and was working now its 404

**Comment by jassmith** [comment]
Sorry we are juggling repos, will update in a bit. It's back on the glideapps repo instead of typeguard

**Comment by SourceCipher** [comment]
Where can we access full docs while this page is down?

**Comment by KyDenZ** [comment]
https://glideapps.github.io/glide-data-grid/

**Comment by jassmith** [comment]
will fix

**Comment by jelling** [comment]
Storybook link is still broken.

**Comment by jassmith** [comment]
Fixed now
