### ISSUE TITLE
Documentation Request: Working with Selected Rows in the Grid

### ISSUE THREAD

**Issue by SyedSibtainRazvi** [glideapps/glide-data-grid#778]
**Issue Title:**

Documentation Request: Working with Selected Rows in `rowMarkers` Grid

**Issue Description:**

I am using the `rowMarkers` feature in GlideApps to allow users to select rows in a grid. However, I am having trouble figuring out how to work with the data of the selected rows programmatically. There seems to be a lack of documentation or guidance on this topic.

**Steps to Reproduce:**

1. Enable `rowMarkers` in a GlideApps grid.
2. Select multiple rows using checkboxes.
3. Attempt to perform an action on the selected rows programmatically. Let's say console.log all the rows data that have been selected.

**Additional Notes:**

I have attempted to use the `onGridSelectionChange` event handler with the following code:

```javascript
onGridSelectionChange={(selectedCells) => console.log(selectedCells)}
```
However, the information provided by this event handler is not sufficient for accessing the data of the selected rows. It returns the following object:

`{current: undefined, rows: _CompactSelection, columns: _CompactSelection}`

**Expected Behavior:**

It would be helpful if GlideApps provided documentation or examples on how to access and work with the data of selected rows when `rowMarkers="checkbox"` is enabled.

Thank you
Reagrds

**Comment by BrianHung** [comment]
Why does `rows` in the selection not work for your usecase?

**Comment by SyedSibtainRazvi** [comment]
@BrianHung Regarding the question, "Why do `rows` in the selection not work for your use case?" – I would like to clarify that I wish to select multiple rows and execute a function for all of them.  The challenge I'm facing is to comprehend how to accomplish my objective using the currently available documentation.

I would greatly appreciate it if you could provide practical examples or offer more detailed guidance to understand how to achieve the goal using the existing features and documentation.
Thank you for your assistance.

**Comment by SejanasJoshua** [comment]
You will need to make use of gridSelection & onGridSelectionChange props to get the selected rows.
```
//1. Import CompactSelection
import DataEditor, { CompactSelection } from '@glideapps/glide-data-grid';

//2. Initialize an initial State
const initialSelection = {
  columns: CompactSelection.empty(),
  rows: CompactSelection.empty(),
};

3. create a State to manage the selection
const [gridSelection, setGridSelection] = React.useState(initialSelection);

//4. Pass them as props in DataEditor
<DataEditor
     {...cellProps}
     gridSelection={gridSelection}
     onGridSelectionChange={setGridSelection}
/>
```
The onGridSelectionChange returns an object with three values including current, columns & rows. You can just console.log to see them.

I hope this solves your issue @SyedSibtainRazvi

**Comment by jassmith** [comment]
I've added this as a starter part of the docs. https://docs.grid.glideapps.com/extended-quickstart-guide/working-with-selections
