### ISSUE TITLE
How to customize cell from a React component cell?

### ISSUE THREAD

**Issue by nhonnh2** [glideapps/glide-data-grid#782]
How to customize cell from a React component cell? Is this not possible and I have to customize cell using drawing canvas ?
I have a table rendered using another technology and now I want to migrate it to glide-data-grid. If the above problem has a solution, I can reuse the component cell

**Comment by jassmith** [comment]
You cannot do that. The reason canvas was picked is our particular use case demanded extremely high performance. We could not get to the performance and quality levels required with DOM based approaches.
