### ISSUE TITLE
Using `preventDefault` in `onCellClicked` does not prevent cell selection

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#785]
If I use `preventDefault` in `onCellClicked`, I would expect that it also prevents the cell from being selected:
  
```typescript
onCellClicked={(cell: Item, args: CellClickedEventArgs) => {
    args.preventDefault()
}}
```

However, this still changes the cell selection and only seems to prevent cell activation. 

**Edit:** The `onCellClicked` is only triggered after the full click is completed. But the selection is already changed for `mousedown` event. There isn't any equivalent to prevent a `mousedown` event, or?

**Comment by jassmith** [comment]
Why does controlling the gridSelection not work for you?

**Comment by LukasMasuch** [comment]
gridSelection doesn't provide the exact location of the mouse click. The underlying use case is to get custom overlay scrollbars to work properly with cell selection if the scroll handle is clicked 😅 However, I can anyways easily get this resolved via a wrapper div. No need for any changes within glide-data-grid.

**Comment by jassmith** [comment]
I wish we had a package for doing custom scrollbars :P

**Comment by LukasMasuch** [comment]
Our solution feels quite hacky, but it seems to work well to get customized overlay scrollbars to work in most browsers (not Firefox):

1) Use `webkit-scrollbar` to customize the scrollbar. E.g.:

```CSS
  ::-webkit-scrollbar {
    background: transparent;
    border-radius: 100px;
    height: 6px;
    width: 6px;
  }
```

2) Use negative padding for the data grid matching the width/height of the custom scrollbar (only if webkit browser and current view requires scroll):

```typescript
experimental={{
  ...(isWebkitBrowser && {
     paddingBottom: hasHorizontalScroll ? -6 : undefined,
     paddingRight: hasVerticalScroll ? -6 : undefined,
  }),
}}
```

3) Wrap the data grid into a div and prevent clicks on the scrollbar to propagate: 

```tsx
<div
  ref={tableWrapperRef}
  onMouseDown={e => {
    if (tableWrapperRef.current && isWebkitBrowser) {
      const boundingClient =
        tableWrapperRef.current.getBoundingClientRect()

      if (
        hasVerticalScroll &&
        boundingClient.height - 6 < e.clientY - boundingClient.top
      ) {
        e.stopPropagation()
      }
      if (
        hasHorizontalScroll &&
        boundingClient.width - 6 < e.clientX - boundingClient.left
      ) {
        e.stopPropagation()
      }
    }
  }}
>
```
