### ISSUE TITLE
Export the cell value formatting used by copy-to-clipboard to use for other data export features

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#792]
I'm currently implementing a CSV data export/download feature, and I would like to apply the same formatting logic to cell values that are also used for the copy-to-clipboard feature (e.g. the [`formatCell` function](https://github.com/glideapps/glide-data-grid/blob/0ea52f371a5e2aaa8595aceefa40722d35410b1a/packages/core/src/data-editor/data-editor-fns.ts#L233)). For this, it would be very useful if there is an exported function to format a cell object to a string which can be reused for implementing other data export features as well. 

Btw. I'm also happy to contribute a hook for (stream) downloading the data as CSV once I have a stable solution.

**Comment by jassmith** [comment]
Formatting for copy is much more complicated than just formatting the strings. To get copy to work correctly cross application you really want to form an HTML structure. This is... somehow... like this depresses me in a way not many things have... the defacto standard for how to copy tabular data between spreadsheets.

**Comment by jassmith** [comment]
This is now exported. The methods are fun.
