### ISSUE TITLE
Textbox overlay not visible even with allowOverlay

### ISSUE THREAD

**Issue by ktjh123** [glideapps/glide-data-grid#795]
Hi I cant seem to enter edit mode. 

Attached is my code below. Not sure what im doing wrong

Saw this error message in the inspector

Cannot open Data Grid overlay editor, because portal not found.  Please add `<div id="portal" />` as the last child of your `<body>`.
console.error @ client.js:1
window.console.error @ setup-hydration-warning.js:18
DataGridOverlayEditor @ index.js:631
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19595
beginWork @ react-dom.development.js:21601
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
eval @ react-dom.development.js:25651

import type { DataEditorRef, EditableGridCell, GridCell, GridColumn, Item } from "@glideapps/glide-data-grid";
import DataEditor, { GridCellKind } from "@glideapps/glide-data-grid";
import { useCallback, useEffect, useRef, useState } from "react";

const columns: GridColumn[] = [
    { title: "A", width: 100 },
    { title: "B", width: 100 },
    { title: "C", width: 100 },
    { title: "D", width: 100 },
    { title: "E", width: 100 },
    { title: "F", width: 100 },
    { title: "G", width: 100 },
    { title: "H", width: 100 },
    { title: "I", width: 100 },
    { title: "J", width: 100 },
    { title: "K", width: 100 },
    { title: "L", width: 100 },
    { title: "M", width: 100 },
    { title: "N", width: 100 },
    { title: "O", width: 100 },
    { title: "P", width: 100 },
    { title: "Q", width: 100 },
];

const GlideSheet = ()=>{
    const dataRef = useRef<(string)[][]>([
        [
            'Bob','Johnson','32','32','123','1','2','3','4','5','6','7','8','9','0','10','A'
        ],
        [
            'Bob','Johnson','32','32','123','1','2','3','4','5','6','7','8','9','0','10','A'
        ],
        [
            'Bob','Johnson','32','32','123','1','2','3','4','5','6','7','8','9','0','10','A'
        ],
        [
            'Bob','Johnson','32','32','123','1','2','3','4','5','6','7','8','9','0','10','A'
        ]
    ])
    const ref = useRef<DataEditorRef>(null);

    const getData = useCallback(([col, row]: Item): GridCell =>{
        console.log('col',col)
        console.log('row',row)
        var personData = dataRef&&dataRef.current
        if(personData){
            if(typeof personData[row][col]==='string') {
    
                return {
                    kind: GridCellKind.Text,
                    data: personData[row][col],
                    allowOverlay: true,
                    readonly: false,
                    displayData: personData[row][col]
                };
            }else{
    
                return {
                    kind: GridCellKind.Text,
                    data: 'Error',
                    readonly:false,
                    allowOverlay: true,
                    displayData: 'Error'
                }
            }
        }else{
            return {
                kind: GridCellKind.Text,
                data: 'Error',
                readonly:false,
                allowOverlay: true,
                displayData: 'Error'
            }
        }
    
    },[])
    
    const generatePersons = async ()=>{
        console.log('ref',ref.current)

        var newData = []
        for(var i=0;i<1000;i++){
            var row = []
            var rowValues = ['Bob','Johnson','32','32','123','1','2','3','4','5','6','7','8','9','0','10','A']
            for(var n=0;n<17;n++){
                row.push(rowValues[n])
                ref.current?.appendRow(n, false);
            }
            newData.push(row)
        }

        var updatedData = dataRef.current.concat(newData)
        console.log('personData',updatedData)

    }

    const onCellEdited = useCallback((cell: Item, newValue: EditableGridCell) => {
        console.log('editing')
        if (newValue.kind !== GridCellKind.Text) {
            // we only have text cells, might as well just die here.
            return;
        }

        const [col, row] = cell;
        dataRef.current[row][col] = newValue.data;

    }, []);
    

    const onRowAppended = useCallback(() => {
        console.log('row appended')
    }, []);

    return <div>
        <button onClick={generatePersons}>Generate</button>
        <DataEditor 
            onCellEdited={onCellEdited}
            rowMarkers='both'
            onRowAppended={onRowAppended}
            ref={ref} 
            getCellContent={getData} 
            columns={columns} 
            rows={dataRef.current.length} 
                
        />

    </div> 
}
export default GlideSheet

**Comment by newpepsi** [comment]
![image](https://github.com/glideapps/glide-data-grid/assets/5549164/b31af1c2-ea45-4280-930c-8b831ef8c38e)

this can work for me

**Comment by devxpy** [comment]
Adding the portal like this fixed it for me

```html
<body>
   <div id="portal" style="position: fixed; left: 0; top: 0; z-index: 9999;">
   ...
````
