### ISSUE TITLE
Row selection retention between clicks

### ISSUE THREAD

**Issue by craigjohnson123** [glideapps/glide-data-grid#800]
I've setup a grid with "checkbox-visible" to always show checkboxes.
However, my users have a difficult time holding the control/shift keys down to multi-select rows. :-(
Is there a way to have the grid retain selections between clicks? 
Thanks

**Comment by jassmith** [comment]
Set `rowSelectionMode` to multi

**Comment by craigjohnson123** [comment]
Thanks Jason!
And thanks again for an incredible grid!
