### ISSUE TITLE
Html Webpack Plugin: Cannot read properties of undefined ( reading 'addFileToAssets')·

### ISSUE THREAD

**Issue by nhonnh2** [glideapps/glide-data-grid#801]
I'm using webpack version 4.44.0. When I start project that webpack throw error "Cannot read properties of undefined (reading 'addFileToAssets')" .  Can you resolve this problem?

![ERROR addFileToAssets](https://github.com/glideapps/glide-data-grid/assets/85781206/86b34b11-5568-4809-a427-0c0679f4ecef)

**Comment by nhonnh2** [comment]
@jassmith can you help me

**Comment by nhonnh2** [comment]
I installed version 3.4 and below with no problem, but from version 4.0.0 and above it got the error "Cannot read properties of undefined (reading 'addFileToAssets')" when start project

**Comment by jassmith** [comment]
Im sorry I really wish I could help you here. If I had to guess (and it is a guess) something is wrong with the way your webpack config with how it handles css files.
