### ISSUE TITLE
Storybook links lead to 404

### ISSUE THREAD

**Issue by mcpar-land** [glideapps/glide-data-grid#803]
https://quicktype.github.io/glide-data-grid At time of writing, this link leads to a Github Pages 404.

![image](https://github.com/glideapps/glide-data-grid/assets/55669980/ecb975e3-9bf3-484d-93fc-e9c031c5f35d)

**Comment by KyDenZ** [comment]
Duplicate of https://github.com/glideapps/glide-data-grid/issues/774
