### ISSUE TITLE
Impossible to duplicate cell content on the last column due to scrollbar

### ISSUE THREAD

**Issue by benasse** [glideapps/glide-data-grid#808]
When a cell in the last column is selected, it is not possible to click and drag to duplicate it in other cells.

This is because the scroll bar is displayed first and does not allow you to click and drag.

Example :
![image](https://github.com/glideapps/glide-data-grid/assets/5676729/73064dde-c476-4422-bb00-30afb7380ba5)

**Comment by jassmith** [comment]
There are overscroll properties that you can set to allow this to be resolved. Unfortunately the browser does not really make this viable for us to "just fix".
