### ISSUE TITLE
onCellClicked doesn't fire when cell is clicked.

### ISSUE THREAD

**Issue by jasonlor** [glideapps/glide-data-grid#81]
Hey there! Amazing library! I'm trying to configure the datagrid to show a dropdown menu when a non-header cell is clicked. Both `onHeaderMenuClick` and `onHeaderClicked` option work perfectly, but when I try to do the same with onCellClicked, it never fires. Any ideas why this might be?

Thanks!

```
    const onCellClicked = React.useCallback((cell: readonly [number, number])  => {
        console.log(cell)
    }, []);
    const onHeaderMenuClick = React.useCallback((col: number, bounds: Rectangle) => {
        setMenu({ col, bounds });
    }, []);
    const onHeaderClicked = React.useCallback(() => {
        console.log("Header clicked");
    }, []);
```

```
                        <DataEditor
                            {...defaultProps}
                            columns={cols}
                            rowMarkers={"both"}
                            getCellContent={getCellContent}
                            rows={numRows}
                            onCellClicked={onCellClicked}
                            onHeaderClicked={onHeaderClicked}
                            onHeaderMenuClick={onHeaderMenuClick}
 />
```

**Comment by jassmith** [comment]
Maybe it broke in 3.0, checking. I will get a point release out today if there is a problem.

**Comment by jassmith** [comment]
The documentation was unclear and the actual behavior was confusing to say the least. While it made sense to me it definitely wasn't expected. 3.0.2 makes the click handler work the same way the documentation states.
