### ISSUE TITLE
cut does not fire onDelete

### ISSUE THREAD

**Issue by zackrw** [glideapps/glide-data-grid#812]
From reddit thread: https://www.reddit.com/r/reactjs/comments/17y7djo/you_favorite_datagrid_component_and_why/kb2wii6/?context=8&depth=9

When, for example, I cut and paste 4 cells, then undo it, it takes multiple undos (one for the paste [great] and one per cell for the deletions [should just be one total]) to get the original state back.

I usually fix this by doing the following. Shouldn't onDelete fire as I do a cut?

```
onDelete={quickHistoryPause}  
```

**Comment by jassmith** [comment]
Fixed in 6.0.0 branch. beta coming soon.
