### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by shayfrendt** [glideapps/glide-data-grid#817]
## Problem

The data grid will not load on Apple devices running Safari on iOS 15.7.2 due to this new exception. This was confirmed on an iPad Air 2.

The exception in the console is:

`SyntaxError: Invalid regular expression: invalid group specifier name`

## Origin

It's believed to be a Lookbehind error in the following regex:

https://github.com/glideapps/glide-data-grid/blame/2c3e7e45a3befd546a8ebea099c37a21dc8b769b/packages/core/src/data-editor/copy-paste.ts#L155

![Blaming_glide-data-grid_packages_core_src_data-editor_copy-paste_ts_at_de0ab9779fb03e81011ceab4e2e4183905643122_·_glideapps_glide-data-grid](https://github.com/glideapps/glide-data-grid/assets/32535/ba07764d-f669-40f9-958f-df478c3af4d6)

## Affects

https://github.com/glideapps/glide-data-grid/tree/v5.3.1, which was shipped in https://github.com/glideapps/glide/pull/24111

## Next steps

- [ ] Get a failing test to reproduce
- [ ] Ship a patch release to v5.3

**Comment by shayfrendt** [comment]
From https://caniuse.com/?search=lookbehind, we can understand better when this regex feature became available in iOS:

![_lookbehind____Can_I_use____Support_tables_for_HTML5__CSS3__etc](https://github.com/glideapps/glide-data-grid/assets/32535/29932797-79d0-490e-9fd1-173054449c78)

**Comment by shayfrendt** [comment]
Helpful article:
https://prathamesh.tech/2023/01/17/workaround-for-lookbehind-regex-in-safari/#browser-compatibility

**Comment by shayfrendt** [comment]
@jassmith pushed a fix for this in https://github.com/glideapps/glide-data-grid/commit/82beb1369cadfb50a66fc24ea77abfad1adacdd2.

**Comment by jassmith** [comment]
This is fixed in 5.3.2
