### ISSUE TITLE
Scroll Viewport when Active Selection Grows Out of View

### ISSUE THREAD

**Issue by BrianHung** [glideapps/glide-data-grid#819]
This is a feature request.

When a user is modifying the active selection with their cursor, and the area of the selection grows off screen, the viewport should shift to keep it in view. This already exists when you grow a selection using arrow keys, and is the behavior in google sheets / excel.

We can maybe re-use `useAutoscroll` for this?

https://github.com/glideapps/glide-data-grid/blob/2ad08c86f43e78de6512ed4e1378494a2c5b97d3/packages/core/src/data-editor/data-editor.tsx#L2196

**Comment by jassmith** [comment]
Great idea. Will see what can be done.

**Comment by jassmith** [comment]
So I cannot reproduce the behavior in google sheets. When I extend a selection to include a partially offscreen cell in google sheets, it does not scroll into view. Like with google sheets if you move your mouse outside of the grid it will start scrolling.

**Comment by BrianHung** [comment]
@jassmith Oops, I should've included a gif, but this is what I see in Google Sheets on MacOs.

https://github.com/glideapps/glide-data-grid/assets/15721634/c1ae3e58-6568-4000-a99e-0eb94e1480b5

**Comment by jassmith** [comment]
Oh actually this is just a bug not a feature request. This works correctly in storybook.

**Comment by jassmith** [comment]
https://github.com/glideapps/glide-data-grid/blob/6.0.0/packages/core/src/internal/data-grid/data-grid.tsx#L513

**Comment by BrianHung** [comment]
> This works correctly in storybook. I could make that larger.

Yeah; it does seem to work in storybook with a pretty sensitive window; would it be possible to adjust it such that it scrolls in the direction of the cursor when it is off-screen?

https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--one-million-rows

**Comment by jassmith** [comment]
Well more accurately the selection doesn't change until the cursor moves again :P

**Comment by BrianHung** [comment]
```ts
            const scrollEdge: GridMouseEventArgs["scrollEdge"] = [
                x < stickyX ? -1 : rect.width < x ? 1 : 0,
                y < totalHeaderHeight ? -1 : rect.height < y ? 1 : 0,
            ];
```

This seems to work whenever cursor is off the main canvas area; not sure how to change selection when scrollEdge is active but mouse does not move (but is offscreen).

**Comment by jassmith** [comment]
Thank you for implementing Brian :)
