### ISSUE TITLE
AllowOverlay returns error

### ISSUE THREAD

**Issue by EFRIPP1** [glideapps/glide-data-grid#825]
Hi! I'm trying to do a basic editable table, whenever I do allowoverlay true it gives me this error
`console.js:213 Cannot open Data Grid overlay editor, because portal not found.  Please add `<div id="portal" />` as the last child of your <body>. `

This is the code I'm using
`
interface Table2Props {
    columns: GridColumn[];
    data: any[]; // Change the type according to your data structure
    columnNames: string[]; // Change the type according to your columnNames structure
    }

const TestTable: React.FC<Table2Props> = ({ columns, data, columnNames }) => {
    
    const getContent = useCallback(([col,row]: Item): EditableGridCell => {
        const dataRow = data[row];
        const index = columnNames[col];
        const d = dataRow[index];
        return {
            kind: GridCellKind.Text,
            allowOverlay: true,
            displayData: d.toString(),
            data: d,
        };
    },[]);

    return (
        <div>
            <DataEditor getCellContent={getContent} columns={columns} rows={data.length}/>
        </div> 
    )
}`

I'm not sure how to approach this error?

**Comment by jassmith** [comment]
Your html document needs to have a <div id="portal" /> as its last child element.
