### ISSUE TITLE
Changing `decimalSeparator` has no effect on displaying a decimal number

### ISSUE THREAD

**Issue by romanstetsyk** [glideapps/glide-data-grid#827]
According to the [docs](https://docs.grid.glideapps.com/api/cells/numbercell#decimalseparator):

> decimalSeparator
Allows overiding the decimal separator, normally passing either "," or "."

But I can't seem to get it working. The string passed as a `decimalSeparator` value does not affect how the number is displayed.

Link to the [codesandbox](https://codesandbox.io/p/devbox/gdg-decimal-fz4g5l?file=%2Fsrc%2FApp.tsx%3A54%2C33) to reproduce the issue.

Please tell me what I'm doing wrong or point me in the right direction.

**Comment by romanstetsyk** [comment]
I've just realized that `thousandSeparator` doesn't work on my end, either. I've edited the code sandbox accordingly.

**Comment by jassmith** [comment]
Your codesandbox has a couple errors:

1) It doesn't have the portal element in the index.html as required.

2) You are passing the `displayData` string to the grid without applying the formatting. The displayData is always represented exactly. The options you are setting are for the editor experience (which doesn't work in your example due to point 1).

**Comment by jassmith** [comment]
I will update the docs to make this clearer

**Comment by romanstetsyk** [comment]
> The `displayData` is always represented exactly. The options you are setting are for the editor experience

Ah, this applies to `fixedDecimals`, `allowNegative`, `thousandSeparator`, and `decimalSeparator`. Thanks for the clarification!


A quick unrelated question: Is the `getCellContent` callback supposed to fire up when you hover over the cell? A `console.log` inside the callback reveals that it's called every few milliseconds.

**Comment by jassmith** [comment]
Depends on the cell type. If the cell has hover effects yes it will be. Your `getCellContent` callback should be hitting a local cache you manage.

**Comment by romanstetsyk** [comment]
It doesn't have any hover effects. It's from the codesandbox linked above. Just want to make sure I'm not missing anything.

https://github.com/glideapps/glide-data-grid/assets/25715951/74887379-b365-4ecc-b6d2-41b464b14114
