### ISSUE TITLE
How to set column width to 100% of data grid if there's only a single column

### ISSUE THREAD

**Issue by huypham50** [glideapps/glide-data-grid#833]
I'd like to span the entire column to 100% and lock it (not allowing column resize) if `columns.length === 1`, what's the most ergonomic way to do this?

Big fan of this library!

**Comment by jassmith** [comment]
Update the column definition to include `grow: 1` and make sure not to pass `onColumnResize` when columns.length === 1

**Comment by jassmith** [comment]
Curious what retool is using GDG for :)
