### ISSUE TITLE
Allow customizing the header menu icon 

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#836]
The default header menu icon is a triangle. It would be great if this could be configured by providing an arbitrary SVG.  

<img width="161" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/2852129/c5d9b60a-d6e4-4aec-bda3-14a55b729ed8">

https://github.com/glideapps/glide-data-grid/blob/2ad08c86f43e78de6512ed4e1378494a2c5b97d3/packages/core/src/data-grid/data-grid-render.tsx#L787

Two potential API options:

1) Make it configurable on a per column-basis by adding a `menuIcon` property to `GridColumn` that works the same way as the `icon` property. 
2) Add a `headerMenuIcon` property to the data editor that allows to configure it globally: 
```typescript
interface DataEditorProps {
    // ...other props
    headerMenuIcon?: Sprite;
}
```

**Comment by jassmith** [comment]
Option 2 is very doable. It has the additional advantage of letting us leave it undefined so we can use simpler drawing techniques when it is not needed.

**Comment by LukasMasuch** [comment]
Wouldn't Option 1 also allow us to leave it undefined and thereby fall back to the current `roundedPoly`? 

```typescript
export interface BaseGridColumn {
   // .. other props
   readonly menuIcon?: GridColumnIcon | string;
}
```

**Comment by jassmith** [comment]
Yeah I don't see why either couldn't be supported.

**Comment by jassmith** [comment]
This is merged
