### ISSUE TITLE
Multi-select cell

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#839]
Similar to the dropdown cell, it would be a great addition to also have a multi-select cell as part of the `cells` package. E.g.:

<img width="385" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/2852129/c1fa3d85-0f09-4a39-afa8-9a9d88b5e68e">

I think this should be pretty doable using `react-select` (also used for the `dropdown-cell`).

Proposed API:

```typescript
type SelectOption = string | { value: string; label: string };

interface MultiSelectCellProps {
    readonly kind: "multiselect-cell";
    readonly value: string[] | undefined | null;
    readonly allowedValues: readonly SelectOption[];
}
```

An additional feature could also be to allow adding values that are not part of the `allowedValues` ([react-select creatable docs](https://react-select.com/creatable)), e.g.:

```typescript
interface MultiSelectCellProps {
    // .. other props
    readonly creatable: boolean;
}
```

**Comment by jassmith** [comment]
This is in effect what the TagsCell is. That said it could definitely use some cleanup.

**Comment by LukasMasuch** [comment]
Oh indeed, tags cell is basically what is requested here. But I think it can really benefit from switching to the `react-select` multi-select input

**Comment by jassmith** [comment]
Agreed
