### ISSUE TITLE
Sparkline cell improvements

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#840]
Two small improvements for the sparkline cell:

1) The current version of `line` chart is usually called an `area` chart. It would be a nice addition if we had a proper line chart kind as well. And have the current version of `line` chart supported via the `area` graph kind. 
2) Add a configuration to hide the x-axis line.

Proposed API: 

```typescript
interface SparklineCellProps {
   // ... other props
    readonly graphKind?: "line" | "bar" | "area";
    readonly hideAxis?: boolean;
}
```

**Comment by jassmith** [comment]
Lets ship these. Great improvements, simple to implement.

**Comment by LukasMasuch** [comment]
Implemented by https://github.com/glideapps/glide-data-grid/pull/854
