### ISSUE TITLE
Unify rounding radii into theme property 

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#845]
Maybe it makes sense to introduce a single rounding radius theming option (e.g. `roundingRadius`) which is used as a default/fallback for rounded rects in GDG:

- Skeleton of loading cell (current value: 3)
- Checkbox (current value: 4)
- Image cell (current value: 4)
- Button cell (current value:  configurable, default is 0)
- Tags cell (current value: height / 2) 
- Bubble cell (current value: height / 2)
- Drilldown cell (current value: dynamic)

**Comment by jassmith** [comment]
I like

**Comment by jassmith** [comment]
This is now merged!
