### ISSUE TITLE
Fill for columns and rows, like on the landing page example

### ISSUE THREAD

**Issue by jorgeochoareyes2** [glideapps/glide-data-grid#851]
When `fillHandle` is set to true it works for columns:
 
![image](https://github.com/glideapps/glide-data-grid/assets/106556358/a728c567-3fda-4a8b-a3cd-40044362aa6c)

But not for rows: 

![image](https://github.com/glideapps/glide-data-grid/assets/106556358/65bc4a8b-7b25-4e2c-bb16-2919bdd28173)

The example demo seems to have the ability to this but I could not find anything in docs on how to add a function to handle this or any way to set it to true. 

![image](https://github.com/glideapps/glide-data-grid/assets/106556358/286360e8-6268-4c8b-9f98-024d56c772c6)

**Comment by jassmith** [comment]
Please try with the latest 5.99.9 package. There have been massive improvements in this area.

**Comment by jassmith** [comment]
Closing assuming things are fine now.
