### ISSUE TITLE
How to implement SparklineCell?

### ISSUE THREAD

**Issue by ecdeaver** [glideapps/glide-data-grid#860]
Hi, just found your library. How are Sparklines implemented like on the homepage?
 I didn't see it in the documentation website and only a few issues here on github.

**Comment by LukasMasuch** [comment]
You can find an example in the storybook: [code](https://github.com/glideapps/glide-data-grid/blob/3068d54a921cef472aca717f6739d8f786420944/packages/cells/src/cell.stories.tsx#L197), [demo](https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cells)
