### ISSUE TITLE
Modifying values with onClick

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#867]
For `provideEditor`/`ProvideEditorComponent`, you're provided with an `onChange` callback, which allows you to modify data and trigger `onCell(s)Edited` etc., but there isn't such a method provided to `CustomRenderer`'s `onClick`. I think I could work around this by including some of my own callback functions in the cell data itself, but that feels pretty hacky and it's breaking the clean separation between pure data and mutations. Would it be possible to provide an `onChange` or similar to `onClick`?

In my current case, I'm building a number increment/decrement cell like this and would like to be able to increment and decrement the value by clicking on that region of the cell directly instead of double-clicking to open an editor and then interacting.

<img width="186" alt="increment/decrement" src="https://github.com/glideapps/glide-data-grid/assets/94077014/0fb0a2ed-d2aa-4ac7-8d0b-22b5f8afef53">

**Comment by jassmith** [comment]
The onClick handler return type allows return a new cell that is the mutated value of the original cell. This then gets passed to onCellsEdited.
