### ISSUE TITLE
@glideapps/glide-data-grid-cells not exporting useExtraCells

### ISSUE THREAD

**Issue by FilipJurkovic** [glideapps/glide-data-grid#873]
Hi I am trying to implement custom cells as by the examples given in storybook and the npm documentation but the package isn't exporting `useExtraCells`.

**Comment by jassmith** [comment]
Ah sorry I will update the docs. All you do is import `allCells` and pass it to `customRenderers`

**Comment by LukasMasuch** [comment]
A quick examples on how to use `useExtraCells` with v6 API is [here](https://github.com/glideapps/glide-data-grid/issues/889#issuecomment-1915537156).

**Comment by jassmith** [comment]
Merging with #889
