### ISSUE TITLE
The fill handler border is sometimes not shown

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#875]
In this case, it doesn't work:

https://github.com/glideapps/glide-data-grid/assets/2852129/055f8329-b815-4db4-a91c-d963a95ad970

In this case, it works:

https://github.com/glideapps/glide-data-grid/assets/2852129/1aea6748-95e2-4ea1-b202-f704f857885b

Maybe it has to do something with it being a single column?

**Comment by jassmith** [comment]
Fixed in main
