### ISSUE TITLE
Multiple row selection with a mouse click

### ISSUE THREAD

**Issue by przemo246** [glideapps/glide-data-grid#878]
Hey, 

I am currently using a workaround to be able to select multiple rows with a mouse click, unfortunately, it affected selecting the rows using the ctrl button, however using a mouse click is much more intuitive for the users in my opinion so I disregarded this fact. Are there any plans to start supporting this natively?

Thanks

**Comment by jassmith** [comment]
Im sorry what exactly do you mean? Do you mean like when you set `rowSelectionMode="multi"`?

**Comment by przemo246** [comment]
I would like to be able to select multiple rows with just a mouse click, without having ctrl key pressed. I am currently manipulating a selection using `onGridSelectionChange` to achieve that. I was curious if there are any plans to support this natively.
