### ISSUE TITLE
Errors after update: 'useExtraCells' and 'useCustomCells' not found

### ISSUE THREAD

**Issue by samuelvernon** [glideapps/glide-data-grid#889]
After Update from v5.3.1 to v6.0.1:

export 'useExtraCells' (imported as 'useExtraCells') was not found in '@glideapps/glide-data-grid-cells'

export 'useCustomCells' (imported as 'useCustomCells') was not found in '@glideapps/glide-data-grid'

**Comment by LukasMasuch** [comment]
This was changed with v6: 

For `useExtraCells`, you can just provide a list of custom cells to use in the `customRenderers` props. Or you can import all via:

```typescript
import { allCells } from "@glideapps/glide-data-grid-cells"

 <DataEditor
      # ... other props,
      customRenderers={allCells}
 />
```

And regarding `useCustomCells`, you can just do:

```
const drawCell: DrawCellCallback = React.useCallback(
    (args, draw) => {
      // Draw something below the cell drawing
      draw()
      // Draw something on top of the cell drawing
}, [])

 <DataEditor
      # ... other props,
      drawCell={drawCell}
 />
   
```

**Comment by samuelvernon** [comment]
Thank you, I'll check on my next try to update :-)
