### ISSUE TITLE
Focus ring is broken in the first colum

### ISSUE THREAD

**Issue by LukasMasuch** [glideapps/glide-data-grid#891]
In `6.0.2`, the focus ring is broken in the first column or first column after the frozen columns:

<img width="406" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/2852129/ba756c65-4f8c-42dd-a727-da5972239c82">

<img width="406" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/2852129/1b6b6d99-8045-468b-9043-a2168fceb3e2">

<img width="167" alt="image" src="https://github.com/glideapps/glide-data-grid/assets/2852129/56f025d1-eeeb-489c-b1e2-18cb5d1ac10f">

**Comment by jassmith** [comment]
Fixed in main
