### ISSUE TITLE
Feature request: Make editor activation customizable

### ISSUE THREAD

**Issue by iamrakhmatov** [glideapps/glide-data-grid#894]
## Current state: 
If cell is focused then editor gets activated on any key press or on double click

## Desired feature:
I want to activate the focused cell only when `Enter` key is pressed or on double click. 
So it would be really nice if editor activation can be configurable.

## Repro:
To see this state in action you can check any example on storybook

**Comment by jassmith** [comment]
This is now available in 6.0.3 as `editOnType`
