### ISSUE TITLE
Feature request: add onSelectAllClicked trigger

### ISSUE THREAD

**Issue by gab23r** [glideapps/glide-data-grid#901]
I would be nice catch when the checkbox select/deselect all is clicked.

**Comment by jassmith** [comment]
Do you just want to know when it happens or need the ability to cancel/override behavior?

**Comment by gab23r** [comment]
Actually, at the end what I need is to know the selected lines. I can know when a line is selected with onCellClicked (column will be -1 if I clicked on the checkbox). So I thought I could manage to keep track of the selected rows myslef but it is not possible if I can't listen the selectedAll checkbox... 

In the meantime, I realize that a I can't know if a click on a checkbox is a shift click or not, so... I don't know if it is possible to know the selected rows. I am missing something obvious ?

**Comment by jassmith** [comment]
`onGridSelectionChange` gives you the updated `gridSelection` which has a `rows` property which has all the selected rows.

**Comment by gab23r** [comment]
Oh right didn't see that, actually am I using reflex: a package that wrap you lib and make it available within python but today this event is not available. I will see with them, thanks.
I let you close this then, except if there is other use case for it.
Thanks!
