### ISSUE TITLE
How to prepend rows instead of append?

### ISSUE THREAD

**Issue by zachdaniel** [glideapps/glide-data-grid#96]
Hello! So I've been able to almost get it working to make the append button prepend a row, but the main issue is that it scrolls to the bottom row every time, whereas I'd like to configure it to scroll to the top. Is there a built in way to do this?

**Comment by jassmith** [comment]
I'll add an option for the next release, should be easy enough to do.

**Comment by jassmith** [comment]
You can now return Promise<"bottom" | "top" | undefined> from the onRowAppended callback and it will assume the append is happening at the specified location.

**Comment by jassmith** [comment]
Expect to see this in 3.1.0

**Comment by zachdaniel** [comment]
Thanks so much!
